### ISSUE TITLE
Setting Primary color does not change the label color

### ISSUE THREAD

**Issue by anddrzejb** [SamProf/MatBlazor#103]
When changing the primary & secondary color in App.razor

`MatTheme themeNeelyc = new MatTheme()`
`    {`
`            Primary = "#29b6f6",`
`            Secondary = "#757575",`
`    };`

this does not seem to affect the label, which keeps the default color.
![image](https://user-images.githubusercontent.com/6518006/59306590-406eb380-8ca5-11e9-9faf-288baa15449e.png)

When the field is set to Required="true", then it is changing to red.

**Comment by SamProf** [comment]
Yes. Thank you.
For now - not all colors can be changed by Themes.
So, will be in next releases - not now.

**Comment by beb3704** [comment]
Is there a way to change it manually for now?

**Comment by enkodellc** [comment]
@beb3704  review this: https://github.com/SamProf/MatBlazor/issues/90#issuecomment-499230723

**Comment by Telexx** [comment]
@enkodellc I've reviewed that and I'm still unsure how to change this away from themes are you able to help?

**Comment by DouglasRiddle** [comment]
@beb3704 @Telexx I was able to manually change the focused label color by creating my own stylesheet that loads after the MatBlazor styles and setting the below

`.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label {
    color: #000;
}`

**Comment by lindespang** [comment]
Hi! Good news, this has been added in the latest MatBlazor release! Closing issue.
