### ISSUE TITLE
Ref in TextField is actually keeping reference to div

### ISSUE THREAD

**Issue by anddrzejb** [SamProf/MatBlazor#104]
When using MatTextField Ref attribute, the Ref method of MatTextField property bound to the component, should return me an ElementRef. It does that, but in this case it is a reference to the parent div not to the input field. I wanted to send an ElementRef and set focus to it. It is still possible by accessing the child elements of the div and then executing focus() method on the input. 

Maybe it would be a good idea to allow choosing which ElementRef is actually reqested (parent div/input/ouline div if has/etc)?

**Comment by SamProf** [comment]
field InputRef

**Comment by anddrzejb** [comment]
I missed that. Thanks!
