### ISSUE TITLE
Docs site looks to show bug for expansion panel

### ISSUE THREAD

**Issue by dazinator** [SamProf/MatBlazor#107]
I'm on the docs site looking at expansion panel example.

![Screenshot_20190613-230551_Chrome](https://user-images.githubusercontent.com/3176632/59470660-52c92880-8e30-11e9-8380-c1b522694706.jpg)

Note how it loops from 1 to 10 but all the panel headers show 10.. ?

**Comment by IvanJosipovic** [comment]
I wonder if its the same issue mentioned here, https://docs.microsoft.com/en-us/aspnet/core/blazor/components?view=aspnetcore-3.0#event-handling

![image](https://user-images.githubusercontent.com/9521987/59478936-fe15b580-8e0f-11e9-8492-9e4e332d98a4.png)
