### ISSUE TITLE
Snackbar zoom issue

### ISSUE THREAD

**Issue by dazinator** [SamProf/MatBlazor#108]
On the docs site, looking at the snackbar example.
I'm using an android mobile (using chrome browser) not tried this on desktop. I noticed that if I pinched to zoom in slightly on the page, and then clicked the button to open the snackbar - it shows off the bottom of the page so I cant see it. If I change the zoom level back to 100% it works fine. See screenshot: 

Zoomed in slightly then click button - doesnt show as expected:

![Screenshot_20190613-232638_Chrome](https://user-images.githubusercontent.com/3176632/59471556-4a262180-8e33-11e9-8073-b8deb111daa9.jpg)

Zoom out fully then click button - this works as expected: 

![Screenshot_20190613-233212_Chrome](https://user-images.githubusercontent.com/3176632/59471697-c28ce280-8e33-11e9-9d05-1470e158ae45.jpg)

**Comment by SamProf** [comment]
For my opinion that normal. Bacause when you use  pinched to zoom -  page have same size and Snackbar will have position of bottom of page. But you don't see bacause you in zoom mode.

**Comment by dazinator** [comment]
@SamProf
> and Snackbar will have position of bottom of page.

It doesnt though. When fully zoomed out, even though I'm not scrolled to the bottom of the page (see 2nd screenshot) the snackbar shows in my visible view area.

**Comment by SamProf** [comment]
Pinched to zoom and zoom is not same.
When you for example zoom on desktop computer - all your fonts and will be bigger and recalculation of all sizes and so on.
But pinched to zoom do not change page - hust make picture of this bugger - page don't recieve any events about that.

**Comment by dazinator** [comment]
@SamProf ah ok I understand. Yes I see you are right and I guess that does make sense after all. Apologies - glad it's not a bug :-)
