### ISSUE TITLE
Table font size bug when changing paging

### ISSUE THREAD

**Issue by dazinator** [SamProf/MatBlazor#109]
Using chrome on my android mobile again.
I'm on the docs site, looking at table component.

I changed the page size to 10 and new rows appeared as expected. However some of the text of the new rows used a larger font size for no discernable reason. See screenshot:

![Screenshot_20190613-233800_Chrome](https://user-images.githubusercontent.com/3176632/59472019-e7ce2080-8e34-11e9-904f-81c33f3a4da5.jpg)

**Comment by SamProf** [comment]
Can not reproduce on my Android Phone.

![image](https://user-images.githubusercontent.com/5611593/59526190-9f683e80-8ed8-11e9-8334-8976a32926c0.png)

**Comment by dazinator** [comment]
I can no longer repro this either. Very odd. I'll close and reopen if I come across it again in future.
