### ISSUE TITLE
Using custom sass

### ISSUE THREAD

**Issue by marcusjm** [SamProf/MatBlazor#119]
Are there any plans to implement custom sass to make custom themes easier? I see there are some plugins for Blazor, not sure about MatBlazor.

**Comment by enkodellc** [comment]
@marcusjm with the latest MatBlazor you can more easily add custom CSS after the MatBlazor.css include. This should make custom themes much easier. Please comment if you have some additional suggestions or want to contribute to more theme customizations. Thanks
