### ISSUE TITLE
MatTable. 'PageSize' attribute

### ISSUE THREAD

**Issue by IgorGutsaev** [SamProf/MatBlazor#122]
It seems that changing the 'PageSize' attribute does not take effect

MatBlazor ver 1.2.0
Net core 3.0.0-preview6.19307.2

![MatBlazor error](https://user-images.githubusercontent.com/13364181/59979693-8c015580-95f3-11e9-923b-2c7aa504a58c.png)

**Comment by enkodellc** [comment]
This is now working in the latest version of MatBlazor
