### ISSUE TITLE
Implement Modal mode for Dialog

### ISSUE THREAD

**Issue by astecenko** [SamProf/MatBlazor#125]
Block the remaining controls on the page outside the dialog (for example, using the z-index overlap) until the dialog buttons are pressed (the dialog is closed). Do not close the dialog by clicking on an empty area.

**Comment by SamProf** [comment]
Thanks for your issue/idea. In the near future will be implemented.

**Comment by lindespang** [comment]
Hi!

This is now possible using the CanBeClosed property set to false in MatDialog.

Closing issue!
