### ISSUE TITLE
Cascading navigation drawer implementation request

### ISSUE THREAD

**Issue by AlseinX** [SamProf/MatBlazor#127]
It is really widely needed. Any plan for it?
It may be not hard to implement as just list + expansion panel + fixing style.

**Comment by enkodellc** [comment]
@AlseinX is this feature request complete with the Nav Menu I created?
https://www.matblazor.com/NavMenu
https://blazorboilerplate.com/

 If so please close this issue. If not please describe in more detail what you were thinking.
