### ISSUE TITLE
MatTexField padding issue on FullWidth="true"

### ISSUE THREAD

**Issue by ctrl-alt-d** [SamProf/MatBlazor#129]
When `FullWidth="true"` the MatTexField's padding turns to `0`  and input letters are too close to label:

![Selection_559](https://user-images.githubusercontent.com/3105983/60271342-742b1980-98f2-11e9-8dad-53d3c23407d9.png)

Check it here: https://blazorfiddle.com/s/sbz2ftht

**Comment by ctrl-alt-d** [comment]
I created PR https://github.com/SamProf/MatBlazor/pull/131 with a more specific css selector.

**Comment by Herdo** [comment]
@ctrl-alt-d I'm not sure, but I just found #158 - would this be fixed by that PR as well?

**Comment by ctrl-alt-d** [comment]
Uhmmm ... I guess no.

El dg., 28 de jul. 2019, 21:35, Stefan Over <notifications@github.com> va
escriure:

**Comment by ctrl-alt-d** [comment]
Closed by https://github.com/SamProf/MatBlazor/pull/131
