### ISSUE TITLE
MatTable: showPaging and PageSize

### ISSUE THREAD

**Issue by Rocky-25** [SamProf/MatBlazor#133]
When setting a value for PageSize, if ShowPaging is set to false the PageSize reverts back to 5.

`<MatTable Items="CoursesList" ShowPaging="true" PageSize="10">`
10 records in the table

`<MatTable Items="CoursesList" ShowPaging="false" PageSize="10">`
5 records in the table

I'm simply using this to show all the records as paging is done outside of this component as it's using odata.

**Comment by Rocky-25** [comment]
I believe it's this bit of code:

` if (PageSizes == null)
        {
            PageSizes = new PageSizeStructure[]
            {
                new PageSizeStructure() { Text = "5", Value = 5 },
                new PageSizeStructure() { Text = "10", Value = 10 },
                new PageSizeStructure() { Text = "25", Value = 25 },
                new PageSizeStructure() { Text = "50", Value = 50 },
                new PageSizeStructure() { Text = "100", Value = 100 },
                new PageSizeStructure() { Text = "*", Value = -1 }
                };
            PageSize = 5;
        }`

If I pass new PageSizes in just for the one value of 10 it works.

Could this check that ShowPaging is on before adjusting the values? Or maybe if the PageSize is not in the list of PageSizes then reset it to 5?

**Comment by intiharj** [comment]
Here's a fiddle that demonstrates this problem: https://blazorfiddle.com/s/i0oqhfes

**Comment by intiharj** [comment]
Here's an updated fiddle that also includes the work-around suggested by @Rocky-25 above.
https://blazorfiddle.com/s/c6ngzgeo

**Comment by NPadrutt** [comment]
The work around works for me. But a solution over the PageSize Parameter would definitly be nicer. 

It's btw kinda funny, that the work around uses the PageSizes which according to the documentation does not work ^^
![image](https://user-images.githubusercontent.com/1764367/66639743-bcf3ad80-ec17-11e9-99d3-4c27f6cfe215.png)

**Comment by enkodellc** [comment]
PagSize is now working.
