### ISSUE TITLE
Filter on multiple columns

### ISSUE THREAD

**Issue by ikkyGH** [SamProf/MatBlazor#136]
Sorry if i am missing this feature, but is there any ability to apply filtering across multiple columns or even all columns?  Thanks in advance.

**Comment by lindespang** [comment]
Hi,
Going through old issues so late reply...

It's not possible using the component interface, I think the easiest thing you could do is to have some Textfields that alter a query you send in to the IEnumerable<Items> to the table.

**Comment by zaina97** [comment]
how to filter multi-column by  FilterByColumnName in matblazor!!
