### ISSUE TITLE
MatSelect - binding to integer values

### ISSUE THREAD

**Issue by dinonovak** [SamProf/MatBlazor#142]
HI,

it would be good to have ability to bind to integer column and also accept integers in MatOption as a value.

Lot of ID columns are integer based.

**Comment by cs2090** [comment]
I would also add it would be good to be able to bind to Enumerators as well.  I quite often use and come across Enumerators used as the basis for fixed list options.

**Comment by tespheakdeyesoftix** [comment]
This is what I really need because I mostly use relational database. Hope it will be available  on the next update.

**Comment by mluckasavage** [comment]
Hi, This is also very important to me to be able to bind to integer column and also accept integers in MatOption as a value.

**Comment by GriesmarThomas** [comment]
I would love to have some news about this probklem. I'm facing the exact same issue now.

**Comment by lindespang** [comment]
Hello!

Binding to integers is possible since MatBlazor 2.1.0, see fiddle below for example
https://blazorfiddle.com/temp/6617ced9-5582-4eeb-aace-8bbc35c25ffe

Closing issue, please let me know if your implementation doesn't work.
