### ISSUE TITLE
FileNotFoundException: Mono.WebAssembly.Interop 

### ISSUE THREAD

**Issue by dmarciano** [SamProf/MatBlazor#145]
I followed the instructions regarding using MatBlazor for server-side deployment and tried using the Tooltip component, however when I test the site I get the following error:

**FileNotFoundException: Could not load file or assembly 'Mono.WebAssembly.Interop, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.**

And the stack trace shows the error is occurring on the line **@(await Html.RenderComponentAsync<App>())**.  In order to get rid of the error, I had to comment out both the tooltip component markup and the **/app.UseEmbeddedBlazorContent(typeof(MatBlazor.BaseMatComponent).Assembly);** line in the Startup.cs file.

**Comment by enkodellc** [comment]
@dmarciano, this issue is very old. Please comment / re-open if you are still having issues.
