### ISSUE TITLE
MatToolTip: breaks css-grid-layout

### ISSUE THREAD

**Issue by Garios** [SamProf/MatBlazor#147]
I have a simple grid-layout like,

```
<div style="display: grid; grid-auto-rows: 30px auto; height: 100vh;">
  <div>Header</div>
  <div style="overflow: auto;">
<!-- CONTENT -->

<!-- overflowing items -->
@foreach(var item in items){
  <div >
     <MatTooltip Tooltip="Test"><span>test</span></MatTooltip>
  </div>
}
  </div>
</div>
```

Items:
many items for overflowing the "content-div"

Result:
I get two scrollbars. One for the content-div and one for the site. The reason is, that in ".mat-tooltip" the position is set to absolute.

**Comment by Garios** [comment]
It happens fundamental, when an elements overflow is larger than the window-size:

```
<div style="height: 100px; overflow-y: auto">
    <div style="height: 7000px">overflow</div>
    <MatTooltip Tooltip="test"><span>test</span></MatTooltip>
</div>
```

Solution:
```
.mat-tooltip{
position: fixed;
}
```

**Comment by Garios** [comment]
A solution could be wrapping the two elements of the tooltip to one div with position set to relative.

```
<div style="height: 100px; overflow-y: auto">
    <div style="height: 7000px">overflow</div>

    <div style="position: relative">
        <MatTooltip Tooltip="test test test test test test"><span @ref="@context.Current">test</span></MatTooltip>
    </div>


</div>
```

In some cases the tooltip can be very small. Therefore I had to set the width of mat-tooltip to max-content:
```
.mat-tooltip
{
    width: max-content;
}
```

**Comment by enkodellc** [comment]
@Garios  Is this still an issue? If so could you create a BlazorFiddle example for me to test?

**Comment by Garios** [comment]
seems to be resolved. thanks!
