### ISSUE TITLE
Is the snackbar duration configurable?

### ISSUE THREAD

**Issue by rshillington** [SamProf/MatBlazor#148]
At the moment it looks like the snackbar goes away after a set time or when the bound bool value is set false.  It would be nice to configure that behaviour, for example to only disappear on the bound bool set too false.  Perhaps this is possible, and I'm just not seeing the appropriate properties.

**Comment by henon** [comment]
Now it is. I implemented a Timeout property for MatSnackbar and requested @SamProf to pull. The issue can be closed as soon as it is merged.

**Comment by Christian-Oleson** [comment]
@rshillington ,
This should be good to close out?

**Comment by henon** [comment]
yes, I implemented this moths ago @rshillington please close!
