### ISSUE TITLE
recommended changes to v1.3.0 install instructions

### ISSUE THREAD

**Issue by intiharj** [SamProf/MatBlazor#152]
a.) change "Used EmbeddedBlazorContent library" to "Install EmbeddedBlazorContent by running the following command in the Visual Studio NuGet Package Manager Console: install-package EmbeddedBlazorContent -Version 1.3.0"

b.) change...
     _1) Startup.cs
     app.UseEmbeddedBlazorContent(typeof(MatBlazor.BaseMatComponent).Assembly);_

  ...to...
     _1)Startup.cs
            i) add "using EmbeddedBlazorContent;"
           ii) add the following line to the end of the Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) method:
                     app.UseEmbeddedBlazorContent(typeof(MatBlazor.BaseMatComponent).Assembly);_

**Comment by enkodellc** [comment]
@intiharj please submit a PR for these changes. I am sure @SamProf  will merge.

**Comment by AlseinX** [comment]
Why are we still using EmbeddedBlazorContent?
preview6 and preview7 has solved the static assets loading problem

**Comment by manuel3108** [comment]
@intiharj Thanks for this issue, took me a while to figure it out

**Comment by enkodellc** [comment]
This appears to be resolved with the newer versions of MatBlazor.
