### ISSUE TITLE
Using MatDrawer

### ISSUE THREAD

**Issue by genifycom** [SamProf/MatBlazor#153]
Are there some examples somewhere of using MatDrawer?

Vladimir's example on YouTube is very helpful, but the Menu is not functional.

**Comment by enkodellc** [comment]
@genifycom You can take a look at https://blazorboilerplate.com/ for another example of the MatDrawer. I just submitted a PR for a NavMenu as well with expansion / sub menus. I think that will help a lot of people out.

**Comment by enkodellc** [comment]
@genifycom did you review my example: https://github.com/enkodellc/blazorboilerplate? Please close this issue if you have. Thanks

**Comment by genifycom** [comment]
Thank you for your help.
