### ISSUE TITLE
Fill width text field with leading icon overwrites icon

### ISSUE THREAD

**Issue by Herdo** [SamProf/MatBlazor#158]
From https://samprof.github.io/MatBlazor/TextField - the text overwrites the icon:
![grafik](https://user-images.githubusercontent.com/651191/62011477-0e43e300-b179-11e9-9f01-3659e6d9381e.png)

I guess the text should be right of the icon, the same way it is with a normal width text field:
![grafik](https://user-images.githubusercontent.com/651191/62011470-fe2c0380-b178-11e9-8473-1ebb3d36ebdd.png)

**Comment by enkodellc** [comment]
This css is a temporary fix, I will submit a PR for the permanant fix
```
div.mdc-text-field--fullwidth-with-leading-icon:not(.mdc-text-field--textarea) > input.mdc-text-field__input {
    padding: 20px 16px 6px 48px !important;
}
```

**Comment by enkodellc** [comment]
It looks like the like SSB:  https://samprof.github.io/MatBlazor/ is still on Version 2.3.0 which has the issue. 

CSB demo version 2.5.0-develop-004 the padding is fixed but the label is now missing:  
https://www.matblazor.com/TextField
https://www.matblazor.com/textfield
