### ISSUE TITLE
MatSelect component doesn't render correctly

### ISSUE THREAD

**Issue by Herdo** [SamProf/MatBlazor#159]
Found on https://samprof.github.io/MatBlazor/Select - when binding multiple `MatSelect` components to the same value, and updating one, this happens:
![grafik](https://user-images.githubusercontent.com/651191/62011748-aee7d200-b17c-11e9-8526-f9d7369810a8.png)

My guess is, this would also happen when `Val1` is set from the code.
The `MatSelect` should evaluate if the bound value has changed, and then hide the `Label` text.

**Comment by lindespang** [comment]
Closing this one as it seems fixed with #162 . Thanks @henon and @ctrl-alt-d !
