### ISSUE TITLE
MatTable loses Material look on 1.3.0

### ISSUE THREAD

**Issue by ctrl-alt-d** [SamProf/MatBlazor#160]
I feel that MatTable has lost Material look on 1.3.0.

Now ( from current Matblazor sample website ):

![Selection_597](https://user-images.githubusercontent.com/3105983/62028347-55b18a00-b1e0-11e9-9a47-25030ea9196f.png)

Before (from random screenshot):

![Selection_598](https://user-images.githubusercontent.com/3105983/62028352-59451100-b1e0-11e9-95c9-188c18decb8e.png)

**Comment by enkodellc** [comment]
@ctrl-alt-d - Yes we updated it the styling as others suggested the change. If you feel that the old or another styling is needed maybe you want to come up with some different classes for styling?

**Comment by ctrl-alt-d** [comment]
Hi @enkodellc ,

Can you confirm this is not an issue, is this the new look? Width table columns is uncompensated.

You know I post PRs to MatBlazor to fix issues and to contribute with new controls as MatNumericUpDow. See PR history to check my PRs if you want.

About to contribute to MatTable, may be some day I will start to do it because I need several features like fetch pages through an interface service and not directly with a request (to make server and client hosted mode compatible). Also, I think, users will need closer pages links to skip directly from current page to another (from 1 to 4 without visit pages 2 and 3) Also, I will need a TreeView and, maybe, a TreeGridView. I will code all them some day, IDK when.

Thanks to share your code and your contributions.

Regards.

Dani.

**Comment by enkodellc** [comment]
Dani,

I can confirm that it is not an issue. If there are problems with the actual width of the table columns "Width table columns is uncompensated" then that could be a real issue. I have contributed a lot to MatTable but as you know that component can be its own beast!

I do see you contributing a lot and I am sure @SamProf appreciates it, as I do. I am like you, someone who uses MatBlazor and contributes. I have no authority or say on what gets merged so in the end you can discuss it with @SamProf.  I try to answer some questions and issues with MatBlazor to help SamProf out in areas that I know a bit about but my focus is BlazorBoilerplate https://github.com/enkodellc/blazorboilerplate.  I will continue to contribute to MatBlazor where I need more functionality to grow BlazorBoilerplate. 

I really appreciate your contributions to MatBlazor. It is great to have a community of devs to create these opensource tools.

Thanks,
Keith

**Comment by ctrl-alt-d** [comment]
>It is great to have a community of devs to create these opensource tools.

:+1:
