### ISSUE TITLE
MatDatePicker/MatNumericUpDownField - Please support HelperText & HelperTextPersistent

### ISSUE THREAD

**Issue by ArryMatt** [SamProf/MatBlazor#172]
HelperText & HelperTextPersistent work really well on MatSelect & MatTextField, but not on MatDatePicker.

MatNumericUpDownField also missing HelperTextPersistent.

**Comment by sandrohanea** [comment]
Hi!
Now as MatNumericUpDownField and MatDatePicker are inherited from MatInputTextComponent, HelperText should be available on all of them.

@enkodellc, I think this can be closed.
