### ISSUE TITLE
[Documentation]: SlideToggle: Add example on how to use CheckedChanged event

### ISSUE THREAD

**Issue by SeppPenner** [SamProf/MatBlazor#177]
The SlieToggle component from https://www.matblazor.com/SlideToggle should document how the  `CheckedChanged` event is used.

Simple Example:

```razor
<MatSlideToggle Label="Switch" CheckedChanged="@((e)=>Toggle(e))" />

@code{
    private async void Toggle(bool toggled)
    {
        if (toggled)
        {
            Console.WriteLine("Toggle true");
        }
        else
        {
            Console.WriteLine("Toggle false");
        }
    }
}
```

**Comment by SeppPenner** [comment]
@SamProf This one is quite easy to add. I sadly don't know where you have the examples (or how your [website](https://www.matblazor.com/) is done), so I can't do it.

**Comment by lindespang** [comment]
Hello @SeppPenner 

Demo components in `...\MatBlazor\src\MatBlazor.Demo\Demo`
Much appreciated if you would like to submit a PR with this or any other documentation👍

**Comment by SeppPenner** [comment]
Hi @lindespang, I will see what I can do.

By the way, if anyone searches for this, the code should now look like this:

```csharp
<MatSlideToggle TValue="bool" Label="Switch" ValueChanged="@((e)=>Toggle(e))" />

@code{
    private async void Toggle(bool toggled)
    {
        if (toggled)
        {
            Console.WriteLine("Toggle true");
        }
        else
        {
            Console.WriteLine("Toggle false");
        }
    }
}
```

**Comment by lindespang** [comment]
Thanks @SeppPenner !
