### ISSUE TITLE
New component: Password

### ISSUE THREAD

**Issue by Satukan** [SamProf/MatBlazor#183]
Do you plan to create an input type="password" specific component? Similar like the TextField just with masked characters.

**Comment by enkodellc** [comment]
@Satukan   Here is how you can accomplish the password:

 <MatTextField @bind-value="@loginParameters.Password" Label="Password" Icon="lock_outline" IconTrailing="true" FullWidth="true" Required="true" Type="password"></MatTextField>

You can see a real example here: https://blazorboilerplate.com/account/login

My repo is here: https://github.com/enkodellc/blazorboilerplate

**Comment by enkodellc** [comment]
@Satukan  if that solved your issue please close this! Thanks for using MatBlazor!
