### ISSUE TITLE
Problem after upgrade to .Net Core 3 Preview 8

### ISSUE THREAD

**Issue by snerting** [SamProf/MatBlazor#185]
After upgrade to .Net Core Preview 8 I always got the following error message:

TypeLoadException: Could not load type 'Microsoft.AspNetCore.Components.ElementRef' from assembly 'Microsoft.AspNetCore.Components, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.

I read the doc [(Upgrade info)](https://devblogs.microsoft.com/aspnet/asp-net-core-and-blazor-updates-in-net-core-3-0-preview-8/) that the following must be done from preview 7 to 8:
* Rename ElementRef to ElementReference.
Think this is the reason for the problem

**Comment by SamProf** [comment]
MatBlazor supports now only Preview 7.

Work in progress. Today will release with Preview 8

**Comment by andreiiiC** [comment]
@SamProf that's great news. Thank you

**Comment by SamProf** [comment]
Looks like complete =)
