### ISSUE TITLE
MatDialog: IsOpenChanged not fired on first open

### ISSUE THREAD

**Issue by dga711** [SamProf/MatBlazor#187]
When i subscribe to `IsOpenChanged` in MatDialog, it does not fire when the dialog is opened for the first time.

See [Fiddle](https://blazorfiddle.com/s/hxetpxgt)

**Comment by dga711** [comment]
After debugging i saw there is only a handler for closing. So IsOpenChanged always just fires on close. I can try to fix it.

**Comment by SamProf** [comment]
Thank you if you can fix this.

**Comment by dga711** [comment]
It's fixed. See #200
