### ISSUE TITLE
MatAppBar

### ISSUE THREAD

**Issue by AJB-Sharp** [SamProf/MatBlazor#188]
MatAppBar does not sseem to be working in 1.6 and on www.MatBlazor.com.

**Comment by AJB-Sharp** [comment]
Solved the problem in my code by disabling prerendering and updating EmbeddedBlazorContent.

**Comment by mdhcindioglu** [comment]
Does net support RTL

**Comment by lindespang** [comment]
Closing this issue since it's quite old and it doesn't seem to be any problems with the MatAppBar as of now. Thanks for using MatBlazor.

@mdhcindioglu Please open a separate issue if you have problems and we'll take it from there.
