### ISSUE TITLE
MatDrawer Component parameter "opened" should not be set outside of its component.

### ISSUE THREAD

**Issue by PlmMaster** [SamProf/MatBlazor#191]
<MatDrawer Mode="@MatDrawerMode.Modal" Style="width:180px;" @ref="TempMatDrawer">
.
.
.
@code 
{
 private void close()
{
TempMatDrawer.Opened = false;
}
}

BL0005 : MatDrawer Component parameter "opened" should not be set outside of its component. warning is displayed.
In .Net core preview 7, there is no problem. the warning code is displayed after upgrade .NET Core preview 8 and Mat version 1.6.0.
 
Thanks.

**Comment by SamProf** [comment]
Hi!
It's not good idea to set Component parameters using Ref.
It's right if you have field in your Model and then bind parameter Opened to this parameter.

I can not reproduce this warning, but right way is - https://blazorfiddle.com/s/9yvzy9yn

**Comment by PlmMaster** [comment]
Thanks. SamProf.
