### ISSUE TITLE
Toast in BlazorFiddle

### ISSUE THREAD

**Issue by Ratomir** [SamProf/MatBlazor#197]
The request URI is too long in BlazorFiddle for Toast example.
It looks like you are trying to put a whole content of the page.
![image](https://user-images.githubusercontent.com/8688494/63225316-a3615700-c1ce-11e9-8591-a3022a1823d6.png)

**Comment by SamProf** [comment]
Yes, it's too long source code example.
For now it's restriction of BlazorFiddle.com

This issue is separated to 2 things.
1) Make small example for MatToast
2) Improve BlazorFiddle.com

**Comment by Ratomir** [comment]
Thanks, @SamProf, if you need more help for the BlazorFiddle or the MatToast, I would like to help you. Currently, I'm writing an application with the Blazor and MatBalzor template.

**Comment by Ratomir** [comment]
No, it is not. Closing the issue.
