### ISSUE TITLE
MatTextField @Bind-Value=not number

### ISSUE THREAD

**Issue by github809** [SamProf/MatBlazor#201]
<MatTextField @Bind-Value="@IntegerNumber" /> not work

**Comment by 2nd4ce** [comment]
yeah, same with enums. It is in one ballpark with [#207 ](https://github.com/SamProf/MatBlazor/issues/207)

**Comment by 2nd4ce** [comment]
Hi @github809 ,

I am not sure if you look for a solution, but I found one which can continue using the same input until there is another component for numbers or else.
I have a field in a loop with multiple items (Master/Detail Create). Hence, I pass the value of the field plus item(row) to the ValueParse Method.

<MatTextField Value="@(item.Quantity.ToString())"
                    OnInput="@((UIChangeEventArgs __e) => ValueParse(__e.Value.ToString(), item))"
                                        Label="Quantity"></MatTextField>


    ```
private void ValueParse(string eInput, MatDetailMvt item)
    {   
        decimal Quantity;
        var IsDecimal = Decimal.TryParse(eInput.ToString(), out Quantity);
        if(IsDecimal)
        {
            item.Quantity = Quantity;
        } else {
            item.Quantity  = 0.0m;      //The d or D suffix converts a literal to a double.
                                        //The f or F suffix converts a literal to a float.
                                        //The m or M suffix converts a literal to a decimal.
        }
    }
```

**Comment by CAccountant** [comment]
The above works when form validation is not in use (<EditForm>).

**Comment by github809** [comment]
wew
