### ISSUE TITLE
TextArea Label Outside of Box

### ISSUE THREAD

**Issue by ArryMatt** [SamProf/MatBlazor#206]
If you BlazorFiddle the Text Area example and add background colours you'll see the floating label on a text area has gone too far up and goes outside of the box.

![image](https://user-images.githubusercontent.com/13235255/63516677-54c0ff00-c4e5-11e9-9f6d-6e6ae3644512.png)

**Comment by enkodellc** [comment]
With current version 2.6 the label floats above the textarea.   
It seems it is inline with Material Design Web components:  https://material-components.github.io/material-components-web-catalog/#/component/text-field
