### ISSUE TITLE
MatSelect - Accepting Enums [Future Request]

### ISSUE THREAD

**Issue by etcircle** [SamProf/MatBlazor#207]
Hi,

Currently, MatSelect is limited to a string. I wished to pass an enum in the drop-down which works with the standard select. I have a workaround to convert from and to, but if you can make in the future, that will be nice!

BaseMatSelect.cs
```
line 62
        [Parameter]
        public string Value
```

Thanks,
Emiliyan

**Comment by 2nd4ce** [comment]
Hi, I found a workaround to work with that issue. Rather than trying to bind Enum, I am parsing a string. So the select looks like following. Surely is not ideal, but it does the job.

```
<MatSelect Label="MaterialType" Enhanced="true" 
 OnInput="@((UIChangeEventArgs __e) => matMasterMvts.MatMasterMvtType = 
         (MatMasterMvtType)Enum.Parse(typeof(MatMasterMvtType), __e.Value.ToString()))">
@foreach (var matMvtType in Enum.GetNames(typeof(MatMasterMvtType)))
{
 <MatOption>@matMvtType</MatOption>
 }
</MatSelect>
```

**Comment by lindespang** [comment]
Thanks for using MatBlazor, as of now MatSelect accept generic types! Closing this one.

**Comment by kurtnelle** [comment]
Can we see a code example of the enum generic type? Cause it's not working!

**Comment by kurtnelle** [comment]
In the event some poor soul lands on this page in the future:

`<MatSelect` Label="Pick a Food Group" TValue="int" OnInput="e=> myClassInstance.Food = (Foods)int.Parse((string)e.Value)">
    @foreach(int val in Enum.GetValues(typeof(Foods))){
        <MatOption TValue="int" Value=@val>@Enum.GetName(typeof(Foods),val)</MatOption>
    }
</MatSelect>

 <span>@myClassInstance.Food</span>

@code
{
    myClass myClassInstance = new myClass();

    class myClass {
        public Foods Food{get;set;} = Foods.None;
    }

    enum Foods : int{
        None = 0,
        Bread = 1,
        Veges = 2,
        Fruit = 3
    }
}"

**Comment by trdsolutions** [comment]
> Can we see a code example of the enum type? Cause it's not working!

Same here and I would also be glad to see an example :-)

**Comment by kurtnelle** [comment]
` <MatSelect Label="Its actually and Enum" TValue="int" ValueChanged="@(v => propertyInfo.SetValue(Item, v))" Value="@((int)propertyInfo.GetValue(Item))" FullWidth="true">
                                        @foreach (int val in Enum.GetValues(propertyInfo.PropertyType))
                                        {
                                            <MatOption TValue="int" Value="@val">@Enum.GetName(propertyInfo.PropertyType, val)</MatOption>
                                        }
                                    </MatSelect>`

Here's my workaround in the meantime for Enums. Cast it to int then cast it back to Enum. "propertyInfo" is of type PropertyInfo, since this came from a razor control that dynamically generates the form at runtime. It doesn't need to be though.
