### ISSUE TITLE
MatDatePicker not moving Label when value is set in function.

### ISSUE THREAD

**Issue by hluikart** [SamProf/MatBlazor#227]
When clicking the Update the MatTextField label move out of the way of the text. The MatDatePicker does not.
Below is the code:
`@page "/"
 
        <p>
            <MatDatePicker @bind-Value="@Date1" Label="something"></MatDatePicker>
        </p>        
        <p>            
            <MatTextField  @bind-Value="@TextField" Label="text" Outlined="true" />
        </p>
       
        <button type="button" class="btn btn-primary" @onclick="Update">Update</button>
 
 
        @functions
        {
            public DateTime? Date1 { get; set; } 
            public String TextField { get; set; } = "";
           
            public void  Update() {
                Date1 = DateTime.Now.AddDays(-10);
                TextField = "something";
                this.StateHasChanged(); 
            }
        }
 `
Looking something like 
![image](https://user-images.githubusercontent.com/35969933/64189802-0398ff80-ce43-11e9-967f-d8daa95f6ce2.png)

**Comment by novfal** [comment]
that working correctly kindly check with below fiddle
https://blazorfiddle.com/s/cvwd9v0j

**Comment by hluikart** [comment]
No. This is not working correctly. when the MatDatePicker gets focus and losses it. the label is smaller and move up out of the way of the value. not behind it. I would think that it should that the MatDatePicker would work the same as the MatTextField and the label would be above the value in the  box not through it.

**Comment by novfal** [comment]
![screencapture-blazorfiddle-s-cvwd9v0j-2019-09-05-15_35_41](https://user-images.githubusercontent.com/9216348/64332841-eacf4c00-cff2-11e9-95aa-840fe0d6a88f.png)

**Comment by hluikart** [comment]
This is still not fixed. 
Clicking 'Update' still put the date over the text. it does correct the view if the user selects the date picker and then select something else. but, that is not what the behavior should be. The User should not have to go through each MatDatePicker and select just to see the value in it.

**Comment by lindespang** [comment]
Hi. This seems to have been fixed in recent MatBlazor release. If you still have problems with this please reopen with a fiddle that is showing the error. (The provided fiddle worked for me when I used fresh MatBlazor)

**Comment by hluikart** [comment]
Hi,
Thanks for the Update. I found that it was fixed in resent version. This could be closed as fixed.

Thanks again,
Harry
