### ISSUE TITLE
Enhanced MattSelect throws exception

### ISSUE THREAD

**Issue by aviezzi** [SamProf/MatBlazor#231]
Hi @SamProf 

I tested the code introduced in this pr https://github.com/SamProf/MatBlazor/pull/221.

The code throws an exception how is described in your issue on Dotnet core repo https://github.com/aspnet/AspNetCore/issues/11159.

I have a fix ready and also an improvement of data binding. I will open a new pr after a couple of day of test.

Please assign this issue to me. 

Thanks, sorry Alberto :D

PS: you can find my temp work here 
https://github.com/aviezzi/MatBlazor/commit/29afaae8b7e4aeddf076f14e93ad762d8b249513
https://github.com/aviezzi/MatBlazor/commit/abae10e80dea1689b7f1887e46fdc28c4ee6263f

**Comment by SamProf** [comment]
Hey, I have started to develop MatSelect Enhanced mode, but not completed....
I think that I don't push this, but you already found this bug.  =)

**Comment by SamProf** [comment]
If you want to complete this - of course you are welcome. Otherwise  I will do this. What you think about it?

**Comment by aviezzi** [comment]
Hi @SamProf 
I saw the changes in preview 9 for DotNetObjectRef, I saw your work and it's ok. 
The last thing to do is data binding I'll do asap.

**Comment by aviezzi** [comment]
The pr is here https://github.com/SamProf/MatBlazor/pull/242.
