### ISSUE TITLE
MatAutocomplete - Custom Style

### ISSUE THREAD

**Issue by moonreign** [SamProf/MatBlazor#240]
Using Class or Style for MatAutocomplete doesn't seem to work. It would be useful to be able to change its appearance, for example its height, etc...

**Comment by dga711** [comment]
As MatAutoComplete consists of several elements it would be hard to direct you style to something specific. For example when you set height through style...should it affect the input or the list. 

To style the list you could use some custom css on the class _mat-autocomplete-popup_

**Comment by moonreign** [comment]
I see you point. I'll close the ticket.
