### ISSUE TITLE
Could not load file or assembly after upgrading to asp.net core RC1

### ISSUE THREAD

**Issue by fnils** [SamProf/MatBlazor#257]
I have tried removing an reinstalling MatBlazor but I get the same error,
It was working as late as yesterday before the upgrade to RC1.

An error occurred while starting the application.
FileNotFoundException: Could not load file or assembly 'EmbeddedBlazorContent, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Trebor.BlazorTest.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)

FileNotFoundException: Could not load file or assembly 'EmbeddedBlazorContent, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Trebor.BlazorTest.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env)
System.RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(object instance, IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.ConfigureBuilder+<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
Microsoft.AspNetCore.Hosting.GenericWebHostBuilder+<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter+<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter+<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.HostFilteringStartupFilter+<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
Trebor.BlazorTest.Program.Main(string[] args) in Program.cs
+
            CreateHostBuilder(args).Build().Run();

**Comment by katiep23** [comment]
I'm having same issue. Did you figure it out?
