### ISSUE TITLE
MatprogressBar inside MatDialog 

### ISSUE THREAD

**Issue by m3awadhi** [SamProf/MatBlazor#258]
Hello ,
When i use Progressbar inside dialog i get the following javascript error 
matBlazor.js:1 Uncaught Error: You can't have a focus-trap without at least one focusable element
    at g (matBlazor.js:1)
    at y (matBlazor.js:1)
    at Object.activate (matBlazor.js:1)
    at Object.trapFocus (matBlazor.js:1)
    at matBlazor.js:1
Here is my component 

@if (_IsBusy)
{
    <MatDialog @bind-IsOpen="@_IsBusy" CanBeClosed="false">
      
     
        <MatDialogContent>
            <MatProgressBar Indeterminate="true"></MatProgressBar>
        </MatDialogContent>
       
    </MatDialog>
  
}

@code{

    [Parameter]
    public bool _IsBusy { get; set; } = false;
   

   
}

**Comment by dga711** [comment]
See here
https://material.io/develop/web/components/dialogs/  Handle Focus Trapping
