### ISSUE TITLE
Toaster does not work when injected into a service

### ISSUE THREAD

**Issue by groogiam** [SamProf/MatBlazor#275]
I am attempting to create a ui service to encapsulate common ui functionality for my application. This service is not a component. Attempting to inject IToaster through the constructor does not appear to work.  E.g.

`public UiService(ClientConfigSettings configSettings, IMatToaster notifier)
`

The object is created but calling add does not display anything. The service is added as singleton. I noticed IToaster is registered scoped but based on the documentation for blazor web assembly scoped and singleton are the same thing. Any ideas on why this does not work?

**Comment by iAmBipinPaul** [comment]
Hi , @groogiam It works in my case.
make sure you have added ```<MatToastContainer />``` on your app.razor file and service is also registered in `startup.cs`

**Comment by iAmBipinPaul** [comment]
> The service is added as singleton. I noticed IToaster is registered scoped but based on the documentation for blazor web assembly scoped and singleton are the same thing. Any ideas on why this does not work?

This may be the issue, I have faced similar issue before , with Blazored Toast
https://github.com/Blazored/Toast/issues/12#issuecomment-492965200

**Comment by groogiam** [comment]
I have it registered in startup and added <MatToastContainer /> to the app.razor. I tried registering my services as scoped and that seemed to fix the issue. So maybe there is an issue with the Blazor documentation stating that scoped and singleton are the same for web assembly.

**Comment by iAmBipinPaul** [comment]
It's same but i don't  know why it does not work when injecting scoped to singleton on client  side `Blazor`.

Here is a blog post about service life time in `Blazor` client side.
https://chrissainty.com/service-lifetimes-in-blazor/

**Comment by groogiam** [comment]
See how declaring scoped fixes the issue, I'm going to close this. Even though the underlying implementation should be the same, technically speaking scoped instances should not be injected into singletons.
