### ISSUE TITLE
MatNumericUpDownField binding value

### ISSUE THREAD

**Issue by dannyaguilerar** [SamProf/MatBlazor#286]
Hi! First of all, kudos on a great library!

I have an issue regarding MatNumericUpDOwnField component and binding values to it. I have a class:

`public class Line {
     ...
     public decimal Quantity { get; set; }
     ...
}`

So after creating a instance of the Line class to keep as a current line holder, I want to bind the property value of line to the said component as follows:

`<MatNumericUpDownField Label="Quantity" @bind-Value="@currentLine.Quantity" Step="1" DecimalPlaces="2" />`

Only that I get an error (translated from spanish)

> CS1503	Argument 2: Cant convert  'Microsoft.AspNetCore.Components.EventCallback<decimal>' to 'Microsoft.AspNetCore.Components.EventCallback'	...\NewQuote.razor	1	Active

I have followed the Usage guide in www.matblazor.com but Im not sure what am I missing. Any idea would be kindly received.

**Comment by navodbopitiya** [comment]
Try changing Quantity to a nullable decimal, since that's what's required by the component.

@dannyaguilerar

**Comment by dannyaguilerar** [comment]
> Try changing Quantity to a nullable decimal, since that's what's required by the component.
> 
> @dannyaguilerar

Thanks @navodbopitiya ! This helped me, I guess I ignored the nullable decimal in documentation.
