### ISSUE TITLE
Not compatible with Asp.net core 3.0 can not build project

### ISSUE THREAD

**Issue by sokolej79** [SamProf/MatBlazor#297]
Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1202	Package System.Text.Json 4.6.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Text.Json 4.6.0 does not support any target frameworks.	MatBlazor.Demo.ClientApp	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo.ClientApp\MatBlazor.Demo.ClientApp.csproj	1	
Error	NU1202	Package System.Text.Json 4.6.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Text.Json 4.6.0 does not support any target frameworks.	MatBlazor	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor\MatBlazor.csproj	1	
Error	NU1202	Package System.Text.Json 4.6.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package System.Text.Json 4.6.0 does not support any target frameworks.	MatBlazor.Demo	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo\MatBlazor.Demo.csproj	1	
Error	NU1202	Package System.Text.Json 4.6.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package System.Text.Json 4.6.0 does not support any target frameworks.	MatBlazor.DevUtils	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.DevUtils\MatBlazor.DevUtils.csproj	1	
Error	NU1202	Package System.Text.Json 4.6.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package System.Text.Json 4.6.0 does not support any target frameworks.	MatBlazor.Demo.ServerApp	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo.ServerApp\MatBlazor.Demo.ServerApp.csproj	1	
Error	NU1202	Package Mono.WebAssembly.Interop 3.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Mono.WebAssembly.Interop 3.0.0 does not support any target frameworks.	MatBlazor.Demo.ClientApp	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo.ClientApp\MatBlazor.Demo.ClientApp.csproj	1	
Error	NU1202	Package Mono.WebAssembly.Interop 3.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Mono.WebAssembly.Interop 3.0.0 does not support any target frameworks.	MatBlazor	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor\MatBlazor.csproj	1	
Error	NU1202	Package Mono.WebAssembly.Interop 3.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Mono.WebAssembly.Interop 3.0.0 does not support any target frameworks.	MatBlazor.Demo	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo\MatBlazor.Demo.csproj	1	
Error	NU1202	Package Mono.WebAssembly.Interop 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Mono.WebAssembly.Interop 3.0.0 does not support any target frameworks.	MatBlazor.DevUtils	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.DevUtils\MatBlazor.DevUtils.csproj	1	
Error	NU1202	Package Mono.WebAssembly.Interop 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Mono.WebAssembly.Interop 3.0.0 does not support any target frameworks.	MatBlazor.Demo.ServerApp	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo.ServerApp\MatBlazor.Demo.ServerApp.csproj	1	
Error	NU1202	Package Microsoft.JSInterop 3.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.JSInterop 3.0.0 does not support any target frameworks.	MatBlazor.Demo.ClientApp	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo.ClientApp\MatBlazor.Demo.ClientApp.csproj	1	
Error	NU1202	Package Microsoft.JSInterop 3.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.JSInterop 3.0.0 does not support any target frameworks.	MatBlazor	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor\MatBlazor.csproj	1	
Error	NU1202	Package Microsoft.JSInterop 3.0.0 is not compatible with netstandard2.0 (.NETStandard,Version=v2.0). Package Microsoft.JSInterop 3.0.0 does not support any target frameworks.	MatBlazor.Demo	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo\MatBlazor.Demo.csproj	1	
Error	NU1202	Package Microsoft.JSInterop 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.JSInterop 3.0.0 does not support any target frameworks.	MatBlazor.DevUtils	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.DevUtils\MatBlazor.DevUtils.csproj	1	
Error	NU1202	Package Microsoft.JSInterop 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.JSInterop 3.0.0 does not support any target frameworks.	MatBlazor.Demo.ServerApp	C:\Users\mito\Desktop\MatBlazor\src\MatBlazor.Demo.ServerApp\MatBlazor.Demo.ServerApp.csproj	1

**Comment by sokolej79** [comment]
Does anyone have similar problems with install matBlazor from nuget package with Visual Studio 2019 latest version 16.3.4. I have installed Asp.net core 3.0  dotnet-sdk-3.0.100-win-x64.
Errors when try install matBlazor nuget package (with gui nuget or by hand with console, same error):

Error Package restore failed. Rolling back package changes for 'MyProjectName hier'			
Error	NU1202	Package System.Text.Json 4.6.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package System.Text.Json 4.6.0 does not support any target frameworks.	
Package Mono.WebAssembly.Interop 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Mono.WebAssembly.Interop 3.0.0 does not support any target frameworks.	
Package Microsoft.JSInterop 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.JSInterop 3.0.0 does not support any target 
Package Microsoft.AspNetCore.Components 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.AspNetCore.Components 3.0.0 does not support any target frameworks.	
Package Microsoft.AspNetCore.Authorization 3.0.0 is not compatible with netcoreapp3.0 (.NETCoreApp,Version=v3.0). Package Microsoft.AspNetCore.Authorization 3.0.0 does not support any target frameworks.

**Comment by unencode** [comment]
It is working OK for me. Perhaps clean your project, delete bin and obj folders and try again. You may also want to check that the versions in your .csproj are correct. Perhaps there is a reference to an older version.

**Comment by sokolej79** [comment]
matblazor 1.9 not woking (errors above), but i tried also with same project and matBlazor version 1.8 and with this version is working, no build errors. Cleaned solution, deleted bin folder, rebuild with 1.9 version same error.

**Comment by sokolej79** [comment]
version MatBlazor 1.10.1 working ok.
