### ISSUE TITLE
Switch to Static Assets with RCL

### ISSUE THREAD

**Issue by chris579** [SamProf/MatBlazor#302]
Starting with the release of .NET Core 3.0 it is now possible to embed static data into a razor class library without any third party technology. This feature is described in the [Microsoft Docs](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class?view=aspnetcore-3.0&tabs=visual-studio#create-an-rcl-with-static-assets).

As there is a first party solution the dependency on `EmbeddedBlazorContent` should be removed and the first party solution should be taken. This is a breaking change. Users will need to initialize their library different than now. 

I could provide a pull request for that, if desired.

**Comment by chris579** [comment]
Will give that a try

**Comment by enkodellc** [comment]
This issue appears to be resolved. Please re-open if there is still an issue.
