### ISSUE TITLE
Outlined fields not showing Labels in MatAccordions

### ISSUE THREAD

**Issue by simonziegler** [SamProf/MatBlazor#305]
I placed some components inside an accordion, similarly to the Personal Data example at https://www.matblazor.com/ExpansionPanel. If I add `Outlined="true"` to any of those components (MatTextField, MatNumericUpDownField or MatDatePicker), the Label is empty until I click into the relevant component, at which point it appears.

If I use the default layout removing `Outlined="true"`, there is no such issue.

**Comment by navodbopitiya** [comment]
This is a duplicate of an issue I faced #255 .
The temporary css fix should work, but yeah, it's not ideal - since there's some whitespace after the label.

**Comment by lindespang** [comment]
Closing as a duplicate of #255
