### ISSUE TITLE
Use offline css and fonts

### ISSUE THREAD

**Issue by jesse51076008** [SamProf/MatBlazor#311]
Use offline css and fonts for Intranet users.
ect.

> googleapis/css/googleapis-css.css
> googleapis/css/googleapis-icon.css
> flUhRq6tzZclQEJ-Vdg-IuiaDsNc.woff2
> and so on

**Comment by teddy108** [comment]
Please fix it. I'm trying to use MatBlazor within a desktop app (using electron) and the icons work only while online.

**Comment by teddy108** [comment]
So I've created a workaround for version 1.10.1. I've basically included the requested fonts and icons into theme.css, build matBlazor.js and created a new nuget package. I'm attaching the diff in case somebody would like to use it.
[diff.txt](https://github.com/SamProf/MatBlazor/files/3950734/diff.txt)
If somebody more experienced with embedding fonts and icons could turn it into a proper PR, it'd be great. Unfortunately, I didn't manage to succesfully use the same approach to enable offline usage of version 2.0.0.

**Comment by enkodellc** [comment]
This should be resolved as of MatBlazor 2.1.0.  The fonts are still in matBlazor.css but you have more control to remove them in your project as you can edit / include the updated matBlazor.css file. Please re-open if you still have an issue.

**Comment by lejsekt** [comment]
Thank you, we've managed to override the font settings with our own css.
