### ISSUE TITLE
Bug: Clicking the "clear" button inside the MatAutoComplete will submit the whole form it's on

### ISSUE THREAD

**Issue by koskila** [SamProf/MatBlazor#315]
If a MatAutoComplete has the clear -button enabled, and it's located inside an EditForm, clicking the clear button will submit the whole form.

This is similar to #179, but you can't fix this with configuration as you can't tell the MatIconButton inside the MatAutoComplete it should be a "button" instead of "submit".

**Comment by enkodellc** [comment]
Merged fix into develop branch.
