### ISSUE TITLE
Mat Theme for buttons not working in Edge browser

### ISSUE THREAD

**Issue by whentotrade** [SamProf/MatBlazor#318]
The colors defined via themes are not rendered correctly for buttons using Edge browser. See based on MatBlazor themes site shown in Firefox (left panel) vs. Edge with Windows10 (right panel):

![image](https://user-images.githubusercontent.com/30272473/67586826-d259f300-f752-11e9-8c78-e46aec97b796.png)

**Comment by enkodellc** [comment]
This is seems now resolved with the latest MatBlazor.
