### ISSUE TITLE
DatePicker can't have value 00:00

### ISSUE THREAD

**Issue by NPadrutt** [SamProf/MatBlazor#328]
I have a DatePicker with no Calendar but only the time:

            <MatDatePicker NoCalendar="true" EnableTime="true" DateFormat="H:i" Enable24hours="true" @bind-Value="Effort" />

And I bind a new DateTime() with the goal that the time is shown as 00:00. But it always shows 00:01.
    DateTime? Effort { get; set; } = new DateTime();

 I also tried to create new DateTime with passing the concrete default values in:

    DateTime? Effort { get; set; } = new DateTime(2000, 1,1,0,0,0);

This would result in a time of 20:00

Is there some default value who kicks in as soon as this value is 00:00?

**Comment by lindespang** [comment]
Hi
Thanks for using MatBlazor.
As far as I can tell this has been fixed since you posted your issue. I updated your example with current syntax here and it seems to work: https://blazorfiddle.com/s/4usu2qsg

Please create a new issue if this is still a problem for you.
