### ISSUE TITLE
Cleanup Demo

### ISSUE THREAD

**Issue by RichiCoder1** [SamProf/MatBlazor#33]
Howdy! Wanted to post an issue before I just did it, but I was thinking about going through and doing the follow (and possibly more) for demo:
* Fix left nav buttons to nav on click anywhere (rather than just text)
* Add padding to right page
* Small tweaks like making the `iframe` for the Navigation demo component look cleaner.

If you'd take a PR, I'd be happy to do the above :)

**Comment by SamProf** [comment]
Hi!
Thank you for your interes.
- left panel (in drawer) now in experimental MatDrawer component, that's now still not completed. When it will be completed - all will be fine.
- padding ok
- iframe ok

Yes, sure you can do it.
