### ISSUE TITLE
MatButton: Link to Non-Blazor-Uris

### ISSUE THREAD

**Issue by Garios** [SamProf/MatBlazor#330]
`<MatButton Link="/Identity/Account/Login">Login</MatButton>`
=> doesn't work, because Identity is not within the component route-space

Workaround:
`<MatButton Dense="true" OnClick="@( p => UriHelper.NavigateTo("/Identity/Account/Login", true))">Login</MatButton>`

Solution could be a property LinkForceLoad.

Ryan Nowak had the same problem:
https://github.com/aspnet/AspNetCore/issues/11099

**Comment by Garderoben** [comment]
This should be fairly simple to fix, just need to install VS 2019 Preview and i will do a pull request for a fix for this, can simple add ForceLoad option to the button and iconbutton.
