### ISSUE TITLE
Multi Select component 

### ISSUE THREAD

**Issue by m3awadhi** [SamProf/MatBlazor#336]
Hi,
I created multi select component using combinations of MatButton ,MatMenu and MatCheckbox
Is there a way to close Menu after  clicking  confirm icons ?

Here is my component  
[MultiSelectEditor.txt](https://github.com/SamProf/MatBlazor/files/3828171/MultiSelectEditor.txt)

And this is how i use this component 

<MultiSelectEditor SourceItems="@SourceItems" @bind-SelectedItems="@SelectedItems" ></MultiSelectEditor>
@code{

      List<string> SourceItems = new List<string>() { "AA", "BB", "CC" , "DD" , "EE" , "FF" };
     List<string> SelectedItems = new List<string>() { "AA","DD" };

}

**Comment by Deriamus** [comment]
Just like in NavMenu.razor from the default Blazor Project, I changed the class of the MatMenu depending on the state:
`<MatMenu @ref="Menu" TargetForwardRef="@buttonForwardRef" Class="@collapseCssClass">`

And on the C# section:
```
@code {
    bool collapseDropDown = true;
    string collapseCssClass => collapseDropDown ? "collapse" : null;

    ...

    private void Open(MouseEventArgs e)
    {
        ClearSelection();
        this.Menu.OpenAsync();
        collapseDropDown = false;  //Added This****
    }
    ...

    private void ConfirmSelection()
    {
        StringSelectedItems = String.Join(ValueSeparator, SelectedItems);
        SelectedItemsChanged.InvokeAsync(SelectedItems);
        collapseDropDown = true;  //Added This****
    }
    private void ClearSelection()
    {
        SelectedItems = StringSelectedItems.Split(ValueSeparator).Where(x => !string.IsNullOrWhiteSpace(x)).ToList();
        collapseDropDown = true;  //Added This****
    }

    ...
```
This seemed to do the job, hope it helps.

**Comment by m3awadhi** [comment]
@Deriamus 
It works ,thanks

**Comment by GriesmarThomas** [comment]
Hello @m3awadhi ! I'm not sure the component is still up-to-date but it doesn't seem to run properly with the last version of Blazor.
I'm not able to check the MatCheckbox elements. Have you ever experiences this issue ?

**Comment by m3awadhi** [comment]
> Hello @m3awadhi ! I'm not sure the component is still up-to-date but it doesn't seem to run properly with the latest version of Blazor.
> I'm not able to check the MatCheckbox elements. Have you ever experiences this issue ?
Hello @GriesmarThomas 
Here is the latest file.
[Multi.txt](https://github.com/SamProf/MatBlazor/files/4176741/Multi.txt)

**Comment by GriesmarThomas** [comment]
Dear @m3awadhi ,

I'm sorry but the code you provided doesn't work.

This is how I implemented it : 

`<MultiSelectEditor SelectedItems="@MarketsFilterSelectedValuesString" SelectedItemsChanged="@(MultipleCriteriaFilterAction("MarketsId"))" SourceItems="@MarketsFilterList" />

    protected EventCallback<List<string>> MultipleCriteriaFilterAction(string queryToAdd)
    {
       return new EventCallback<List<string>>();
    }

    private List<string> MarketsFilterSelectedValuesString { get; set; }
    private List<string> MarketsFilterList { get; set; }

`

By the way, I had to change in your file  "<MatCheckbox Value=...>" by <MatCheckbox @bind-Value=...>

What am I doing wrong on this ?

**Comment by GriesmarThomas** [comment]
After having searched on my side, I updated your component, which works now : 
[Multi.txt](https://github.com/SamProf/MatBlazor/files/4184955/Multi.txt)

**Comment by pdarkness** [comment]
> After having searched on my side, I updated your component, which works now :
> [Multi.txt](https://github.com/SamProf/MatBlazor/files/4184955/Multi.txt)

Thanks for this. 

It saved me a lot of time :)

**Comment by larseggan** [comment]
I tried this component on Blazor WebAssembly .NET 5.0 MatBlazor 2.9.0-develop-042.
Get the following error when I click on the Component:
polyfills.js:222 Uncaught TypeError: Cannot read properties of null (reading 'focus')
    at Object.focusListRoot (matBlazor.js:1)
    at e.handleMenuSurfaceOpened (matBlazor.js:1)
    at HTMLDivElement.handleMenuSurfaceOpened_ (matBlazor.js:1)
    at ZoneDelegate.invokeTask (polyfills.js:447)
    at Zone.runTask (polyfills.js:218)
    at ZoneTask.invokeTask [as invoke] (polyfills.js:529)
    at invokeTask (polyfills.js:1669)
    at HTMLDivElement.globalZoneAwareCallback (polyfills.js:1706)
    at e.t.emit (matBlazor.js:1)
    at Object.notifyOpen (matBlazor.js:1)
