### ISSUE TITLE
MatDialog

### ISSUE THREAD

**Issue by TeraCorp** [SamProf/MatBlazor#337]
Is there any way to use the MatDialog with a progress bar while the server does some processing, then close the MatDialog when the server finishes?

**Comment by enkodellc** [comment]
This can be done with code and no changes to MatBlazor...

-Open MatDialog with a button click or whatever
-Create a button on the MatDialog which does the the following steps
  - Start the progress bar
  - Make the call to the server, MUST be a Synchronous call to the server
  - Once the call returns, turn off the progress bar and close the MatDialog
