### ISSUE TITLE
Does latest Blazor WASM (3.1.0-preview4.19579.2) break MatBlazor-based applications?

### ISSUE THREAD

**Issue by ChristianWeyer** [SamProf/MatBlazor#353]
Now with .NET Core 3.1 officially released there is also a new preview version of Blazor WASM:
3.1.0-preview4.19579.2

I upgraded an existing demo application to those new packages and bumped the version to netstandard2.1 - and left everything else as is.

After cleaning and rebuilding, I get a runtime exception that MatBlazor cannot be found in window.
![image](https://user-images.githubusercontent.com/888718/70147963-9301b900-16a5-11ea-9200-395b01505bba.png)

Are there other users experiencing the same issue?
Thanks.

**Comment by NPadrutt** [comment]
yep, same here unfortunately.

**Comment by qqzhw** [comment]
me too

**Comment by likj8457** [comment]
Yep... same here

**Comment by olabacker** [comment]
Seems like the demo has the same problem as well

**Comment by jernejk** [comment]
I have just copied the old scripts from `_content` folder to `bin\Debug\netstandard2.1\dist\_content` and it worked.
Not ideal as I had those files because I'm using GitHub pages.

Here are the files if you need them:
https://github.com/jernejk/CognitiveServices.Explorer/tree/master/_content

**Comment by likj8457** [comment]
@jernejk unfortionately, it did nothing for me copying _content to dist... You sure that was the onlything you had to do?

**Comment by jernejk** [comment]
Ah, based on my commit, I also updated wwwroot/index.html

``` html
    <!-- MatBlazor-->
    <script src="_content/MatBlazor/dist/matBlazor.js"></script>
    <script src="_content/Blazor.FileReader/FileReaderComponent.js"></script>
```

https://github.com/jernejk/CognitiveServices.Explorer/commit/1669bfae52c0304330fab16389fb2509da7c3a71

So 2 things, manually copied the script files and manually included them in the index.html file.

**Comment by likj8457** [comment]
Yep, that was it!

Thanks!

**Comment by abibtj** [comment]
> Ah, based on my commit, I also updated wwwroot/index.html
> 
> ```
>     
>     <script src="_content/MatBlazor/dist/matBlazor.js"></script>
>     <script src="_content/Blazor.FileReader/FileReaderComponent.js"></script>
> ```
> 
> [jernejk/CognitiveServices.Explorer@1669bfa](https://github.com/jernejk/CognitiveServices.Explorer/commit/1669bfae52c0304330fab16389fb2509da7c3a71)
> 
> So 2 things, manually copied the script files and manually included them in the index.html file.

Thank you so much. It worked.

**Comment by Flearz** [comment]
@jernejk  Worked for me too thank you, maybe some update tutorial would be good ? @SamProf 
Anyway, thanks for all the job you're doing on this project it's awesome :)

**Comment by NPadrutt** [comment]
Actually the read me contains that since a couple of days :)

![image](https://user-images.githubusercontent.com/1764367/70623944-758d9b80-1c1f-11ea-8900-c77ff18b95a7.png)

**Comment by Christian-Oleson** [comment]
@ChristianWeyer @NPadrutt 
This one should be resolved. Can you please close this?
