### ISSUE TITLE
Adding MatBlazor : but button are normal button

### ISSUE THREAD

**Issue by vd3d** [SamProf/MatBlazor#367]
Hi,

I have add MatBlazor, by:
- Adding the nuget
- adding @using MatBlazor in _Imports.razor
- adding a reference to matBlazor.js in the _Hosts.cshtml

But, the MatButton are not material button, and when I click, nothing happend !

Any idea ?

Thx

**Comment by vd3d** [comment]
For the style, I have to add the matblazor.js manually to my project !
Is it normal ? If yes, it is somehting that you should add to the documentation maybe ;-)

But for the event, when I click nothing happend !

> <MatButton OnClick="@Logout" Icon="exit_to_app" Label="Log out" />
> 
> @code {
>     public void Logout(MouseEventArgs e)
>     {
> ...
>     }
> }

The Logout method is never called !

**Comment by adriyian** [comment]
<MatButton @onclick="Logout" Icon="exit_to_app" Label="Log out" />

**Comment by sebestyn168** [comment]
You should not have any parameter on you function if your only using the function name:
<MatButton Icon="@MatIconNames.Save" OnClick="Save"/>
protected async Task Save()

Also you can use this syntax to call parameters:
<MatButton Icon="@MatIconNames.Delete" OnClick="async () => await DeleteItem(ViewModel.EditionItem)" />
protected async Task DeleteItem(Entity item)

**Comment by lindespang** [comment]
Hi!
Thanks for using MatBlazor!
Quite a late response here but better than never I guess. I was not around in 2019 but I can tell you that atleast now the MatButton and click events works fine as I use them myself every day :) If there still is something weird please create a new issue together with a blazorfiddle example.
