### ISSUE TITLE
Donation?

### ISSUE THREAD

**Issue by yberstad** [SamProf/MatBlazor#371]
Hi @SamProf!

Thank you for all the work you, and everybody else contributing, have put down into this project! I have never donated to an open source project before, but I would really like for this project to continue to exist. And if a donation could make a small difference, I would like to make a donation. Not sure what would be an appropriate amount, I was hoping that someone could give me a hint...

**Comment by Mercurial** [comment]
donate $100 or more and be done with it :)

**Comment by yberstad** [comment]
@Mercurial, I have now followed your advice, thanks! 😃
