### ISSUE TITLE
Decrementing 0 on MatNumericUpDownField<Int32> results in 65535 instead of -1

### ISSUE THREAD

**Issue by RobotJackson** [SamProf/MatBlazor#373]
Can be reproduced on the demo: https://www.matblazor.com/NumericUpDownField just press down on the "int" box in the "Generic types" section

Looks like a copy/paste error in https://github.com/SamProf/MatBlazor/blob/master/src/MatBlazor/Core/MatBlazorSwitchTInt.cs
MatBlazorSwitchTInt.Decrease casts to ushort instead of int.

**Comment by lindespang** [comment]
Closing this one since it was fixed earlier this year!
