### ISSUE TITLE
MatSnackBar console error

### ISSUE THREAD

**Issue by enkodellc** [SamProf/MatBlazor#376]
When using a MatSnackBar on a  page I receive a console error in both CSB and SSB.  
The issue can be seen with BlazorBoilerplate and has been around for several months, https://github.com/enkodellc/blazorboilerplate/issues/111  I thought it was my issue but have tracked it down to specifically a MatSnackBar issue.

To replicate I created a blank Blazor Project and just added a MatSnackBar to the index.razor and could replicate the issue with this code:

```
<MatSnackbar @bind-IsOpen="@lazySnackbarIsOpen">
    <MatSnackbarContent>If you like BlazorBoilerplate, please put a <a href="https://github.com/enkodellc/blazorboilerplate" target="_blank">star on GitHub</a>.</MatSnackbarContent>
    <MatSnackbarActions>
        <MatIconButton Icon="@MatIconNames.Stars" Link="https://github.com/enkodellc/blazorboilerplate" style="color: white !important;" target="_blank"></MatIconButton>
    </MatSnackbarActions>
</MatSnackbar>

@code{
    bool lazySnackbarIsOpen = false;

    protected override async Task OnInitializedAsync()
    {
        await base.OnInitializedAsync();

        await Task.Delay(TimeSpan.FromSeconds(3)).ContinueWith((_) =>
        {
            this.lazySnackbarIsOpen = true;
        });
    }

    public void Dispose()
    {
    }
}
```

Here are the console errors: 
CSB:

> Uncaught (in promise) Error: System.ArgumentException: There is no tracked object with id '2'. Perhaps the DotNetObjectReference instance was already disposed.
> Parameter name: dotNetObjectId

SSB:

> Uncaught (in promise) Error: There was an exception invoking 'MatSnackbarClosedHandler'. For more details turn on detailed exceptions in 'CircuitOptions.DetailedErrors'

**Comment by lindespang** [comment]
@enkodellc I can't reproduce this using your code. Maybe fixed? Is it still a problem in boilerplate?

**Comment by enkodellc** [comment]
I could not with CSB, but with Release SSB I could recreate by switching pages back a forth a bit. It was doing it consistently without the "hammering" on it to recreate so I will close this issue. Thanks for testing!
