### ISSUE TITLE
MatFileUpload error in OnChange when calling file.ReadAllAsync

### ISSUE THREAD

**Issue by centrolutions** [SamProf/MatBlazor#377]
Using v2.0.0 nuget package:

When using the MatFileUpload component and subscribing to the OnChange event -- if the  ReadAllAsync() method is called on a file, the following error occurrs in the browser's console:

> matBlazor.js:1 Uncaught (in promise) Error: Error: System.ArgumentNullException: Value cannot be null. (Parameter 's')
>    at System.Convert.TryFromBase64String(String s, Span`1 bytes, Int32& bytesWritten)
>    at MatBlazor.RemoteFileListEntryStream.DecodeBase64ToBuffer(String base64, Byte[] buffer, Int32 offset, Int32 maxBytesToRead)
>    at MatBlazor.RemoteFileListEntryStream.CopyFileDataIntoBuffer(Int64 sourceOffset, Byte[] destination, Int32 destinationOffset, Int32 maxBytes, CancellationToken cancellationToken)
>    at MatBlazor.FileListEntryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
>    at System.IO.Stream.CopyToAsyncInternal(Stream destination, Int32 bufferSize, CancellationToken cancellationToken)
>    at MatBlazor.FileListEntryExtensions.ReadAllAsync(IMatFileEntry matFileEntry, Int32 maxSizeBytes)
>    at DirectoryMap.Pages.EditFloorPlan.FileUploadChanged(IMatFileEntry[] files) in C:\Projects\DirectoryMap\DirectoryMap\Pages\EditFloorPlan.razor:line 31
>    at Microsoft.AspNetCore.Components.ComponentBase.CallStateHasChangedOnAsyncCompletion(Task task)
>     at matBlazor.js:1
> (anonymous) @ matBlazor.js:1
> Promise.then (async)
> (anonymous) @ matBlazor.js:1

Steps to reproduce:

`@using Blazor.Extensions.Canvas.Canvas2D
@using Blazor.Extensions

<form>
    <MatFileUpload OnChange="FileUploadChanged"></MatFileUpload>
</form>

@code {
protected string _imageBase64Bytes;
async Task FileUploadChanged(IMatFileEntry[] files)
    {
        if (files != null && files.Length >= 1)
        {
            var file = files[0];
            using (var ms = await file.ReadAllAsync())
            {
                _imageBase64Bytes = Convert.ToBase64String(ms.GetBuffer());
            }
        }
    }
}
`

**Comment by Christian-Oleson** [comment]
@centrolutions ,
Is this still happening for you?

**Comment by centrolutions** [comment]
@Christian-Oleson thanks for following up. I just ran a test with the v2.8.0 nuget package.
It appears the IMatFileEntry was changed to IMatFileUploadEntry and .ReadAllAsync() is no longer available. So, with some slight alteration:

`<MatFileUpload OnChange="FileUploadChanged"></MatFileUpload>`

```
    protected string _imageBase64Bytes;
    async Task FileUploadChanged(IMatFileUploadEntry[] files)
    {
        if (files != null && files.Length >= 1)
        {
            var file = files[0];
            using (var ms =  new MemoryStream())
            {
                await file.WriteToStreamAsync(ms);
                _imageBase64Bytes = Convert.ToBase64String(ms.GetBuffer());
            }
        }
    }
```
This appears to be working; I would call the problem fixed.

**Comment by Christian-Oleson** [comment]
@centrolutions ,
Thanks! I do not have access to close this issue, so can you please do so?
