### ISSUE TITLE
MatDatePicker doesn't remember selected date in calendar.

### ISSUE THREAD

**Issue by salanford** [SamProf/MatBlazor#385]
Currently the calendar always defaults to the current date instead of the selected date which is extremely annoying and user unfriendly. I only glanced at the code but I suspect it's because the Flatpickr instance must get recreated on each render cycle and the state is not being preserved and set after render. All the examples on the MatBlazor demo site exhibit this behavior so I didn't bother with a repro. 

Any chance there will be a fix for this soon? Any known workaround? Perhaps allowing the defaultDate to bet set would help???

**Comment by salanford** [comment]
> Currently the calendar always defaults to the current date instead of the selected date which is extremely annoying and user unfriendly. I only glanced at the code but I suspect it's because the Flatpickr instance must get recreated on each render cycle and the state is not being preserved and set after render. All the examples on the MatBlazor demo site exhibit this behavior so I didn't bother with a repro.
> 
> Any chance there will be a fix for this soon? Any known workaround? Perhaps allowing the defaultDate to bet set would help???

I looked closer at the MatDatePicker code and it appears to be setting the defaultDate value in the click handler when it opens Flatpickr which makes me think it's not a simple state issue as I initially assumed. I don't see any obvious reason why it doesn't work as expected so I'm hoping for a fix soon are at least a workaround.

**Comment by salanford** [comment]
> > Currently the calendar always defaults to the current date instead of the selected date which is extremely annoying and user unfriendly. I only glanced at the code but I suspect it's because the Flatpickr instance must get recreated on each render cycle and the state is not being preserved and set after render. All the examples on the MatBlazor demo site exhibit this behavior so I didn't bother with a repro.
> > Any chance there will be a fix for this soon? Any known workaround? Perhaps allowing the defaultDate to bet set would help???
> 
> I looked closer at the MatDatePicker code and it appears to be setting the defaultDate value in the click handler when it opens Flatpickr which makes me think it's not a simple state issue as I initially assumed. I don't see any obvious reason why it doesn't work as expected so I'm hoping for a fix soon are at least a workaround.

I think I may have found the issue. It looks like the defaultDate isn't actually being set on the flatpickr options on the Javascript side in matDatePicker.js

**Comment by tossnet** [comment]
Have you come up with a solution?

**Comment by lilon55** [comment]
Are you using Server side or Client side, because on the Server side demo website it starts with the current date selected (https://www.matblazor.com/DatePicker), but whereas the Client Side demo website does not (https://samprof.github.io/MatBlazor/DatePicker).

**Comment by lindespang** [comment]
Hi!

A little late, but this was fixed in commit 733f264f7fa8cb4333122cc1457c10ec910bdde8

Thanks for using MatBlazor
