### ISSUE TITLE
Question : Upgrading MatBlazor for Dotnet Core 3.1

### ISSUE THREAD

**Issue by buzzlu** [SamProf/MatBlazor#386]
It's a nice project and better user experience. 

We are trying Dotnet Core 3.1. Is there any plan to upgrade MatBlazor forDotnet Core 3.1? 

Thanks

**Comment by SeppPenner** [comment]
This is already done since version 2.0.0 I guess. Version 2.1.0 is already using the Blazor 3.2 version.

I assume that this issue can be closed @SamProf.

**Comment by Christian-Oleson** [comment]
@buzzlu ,
Per @SeppPenner 's comment, this is done. Can you close this?
@SamProf or  @enkodellc if they can close this as well

**Comment by buzzlu** [comment]
Thanks and confirmed.
