### ISSUE TITLE
Checkbox class not working

### ISSUE THREAD

**Issue by tlemmons** [SamProf/MatBlazor#390]
I am pretty new to blazor so sorry if I misunderstand something.  I am using MatCheckBox and trying to change its color and size via css.  I add a new class but it appears to get added to the back of the class list so nothing I change actually has any affect.  I can use style but when using multiple on a page that gets large and wordy.  Is there somewhere else I need to do the changes?

**Comment by RonPeters** [comment]
The old version of MatBlazor embedded the styles in the JavaScript. This made it very hard to override the default styles. Try the latest version. You can add the CSS in the head tag properly now, and then add your styles afterwards so they are properly overridden.

`<link href="_content/MatBlazor/dist/matBlazor.css" rel="stylesheet" />`

**Comment by enkodellc** [comment]
As @RonPeters described the latest version resolves this issue.
