### ISSUE TITLE
Checkbox text not centered

### ISSUE THREAD

**Issue by NPadrutt** [SamProf/MatBlazor#392]
In my Blazor WASM application I have a checkbox to allow the user to stay logged in:

            <div>
                <MatCheckbox TValue="bool" @bind-Value="@LoginParameters.RememberMe">Remember Me</MatCheckbox>
            </div>

That works so far, but the text is not really nice aligned. I would like to center it vertically. I already tried to apply a CSS class with a `text-align: center;` but that didn't change anything.

EDIT: I forgot the screenshot: 
![image](https://user-images.githubusercontent.com/1764367/72265132-3c7c8880-361c-11ea-9dcb-7b6ca3670953.png)

**Comment by Cameron097** [comment]
Possibly use the bootstrap CSS class "align-middle"?

**Comment by NPadrutt** [comment]
Thanks for your suggestion. Unfortunately that doesn't seem to change anything.
![image](https://user-images.githubusercontent.com/1764367/72264922-d7289780-361b-11ea-9c32-f9d029e9bc53.png)

**Comment by Cameron097** [comment]
Are you setting the css on the "Remember Me" text?
like:
`        <div>
            <MatCheckbox TValue="bool" @bind-Value="@LoginParameters.RememberMe"><text class="align-middle">Remember me</text></MatCheckbox>
        </div>`

Might work, otherwise it looks like it's overwriting the aligning CSS when it creates the label for the checkbox.

**Comment by NPadrutt** [comment]
Itried it with <text> and <span> but unfortunately both didn't work.

**Comment by enkodellc** [comment]
```
.mat-checkbox>label {
    margin-bottom: 0px;
}
```

I think I will need to start charging for support.

**Comment by NPadrutt** [comment]
thanks @enkodellc. That did it.
Let me know when you ever in switzerland. I invite you for some coffee or beer ;)
