### ISSUE TITLE
MatTextField: Fields are not updates on "input" event

### ISSUE THREAD

**Issue by jeisonjei** [SamProf/MatBlazor#397]
Hello, thank you for that library, could you help me to understand why does it happen?
I have simple calculation program on ASP.NET Core 3.1 and I'm trying to use MatBlazor there. So, my willing is to have fields updated on "input" event. 
When I try to use standard input html element it works - fields are updating on "keyup" event (actually I wanted to use "input" event, but as I understand for now in Blazor I should use different event to assign method when "@bind-value:event" attribute is using). 
But when I'm trying to use MatTextField - values are updated only on "change" event (as I see).
Code sample below:
`<div class="row justify-content-center">

        <div class="col-12 col-sm-10 col-md-6 col-lg-4">
            <div class="row justify-content-between">
                <div class="col-auto">
                    <label>Air flow, m³/h</label>
                    <MatTextField TValue="double" Disabled="s.DisabledAirFlow" Label="Air flow, m³/h" @onfocus="s.AssignSubScenarioAirFlow" @bind-Value="Main.AirFlowValue" @oninput="Main.AssignCompMethod"></MatTextField>
                </div>
                <div class="col-2">
                    <img src="@s.PathAirFlowLock" @onclick="s.AssignScenarioAirFlow"/>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input class="form-control" disabled="@s.DisabledAirFlow" @onfocus="s.AssignSubScenarioAirFlow" @bind-value="Main.AirFlowValue" @bind-value:event="oninput" @onkeyup="Main.AssignCompMethod" />
                </div>
            </div>
            <div class="row justify-content-between">
                <div class="col-auto">
                    <label>Air delta t, °C</label>
                    <MatTextField TValue="double" Disabled="s.DisabledAirDeltaTe" Label="Delta t, °C" @onfocus="s.AssignSubScenarioAirDeltaTe" @bind-Value="Main.AirDeltaTeValue" @oninput="Main.AssignCompMethod"></MatTextField>
                </div>
                <div class="col-2">
                    <img src="@s.PathDeltaTeLock" @onclick="s.AssignScenarioAirDeltaTe"/>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input class="form-control" disabled="@s.DisabledAirDeltaTe" @onfocus="s.AssignSubScenarioAirDeltaTe" @bind-value="Main.AirDeltaTeValue" @bind-value:event="oninput" @onkeyup="Main.AssignCompMethod" />
                </div>
            </div>
            <div class="row justify-content-between">
                <div class="col-auto">
                    <label>Heat capacity, kW</label>
                    <MatTextField TValue="double" Disabled="s.DisabledHeatCapacity" Label="Heat capacity, kW" @onfocus="s.AssignSubScenarioHeatCapacity" @bind-Value="Main.HeatCapacityValue" @oninput="Main.AssignCompMethod"></MatTextField>
                </div>
                <div class="col-2   ">
                    <img src="@s.PathHeatCapacity" @onclick="s.AssignScenarioHeatCapacity"/>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <input class="form-control" disabled="@s.DisabledHeatCapacity" @onfocus="s.AssignSubScenarioHeatCapacity" @bind-value="Main.HeatCapacityValue" @bind-value:event="oninput" @onkeyup="Main.AssignCompMethod" />
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-10 col-md-6 col-lg-4">
            <div class="card">
                <div class="card-header">
                    <h3>How to use</h3>
                </div>
                <div class="card-body">
                    <div class="card-title">
                    </div>
                    <div class="card-text">
                        <ul class="list-unstyled">
                            <li>Scenario: @Main.Scenario</li>
                            <li>SubScenario: @Main.SubScenario</li>
                            <li>_airFlow: @Main._airFlow</li>
                            <li>_airDeltaTe: @Main._airDeltaTe</li>
                            <li>_heatCapacity: @Main._heatCapacity</li>
                            <li>AirFlowValue: @Main.AirFlowValue</li>
                            <li>AirDeltaTeValue: @Main.AirDeltaTeValue</li>
                            <li>HeatCapacityValue: @Main.HeatCapacityValue</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>`

**Comment by SamProf** [comment]
For Now it's not possible to make good and gast components with dynamic event binding. This featute will be in Blazor and also in MatBlazor.

Workaround for now: https://blazorfiddle.com/s/qs69vfql
