### ISSUE TITLE
Add possibility of initial state of MatIconButton

### ISSUE THREAD

**Issue by stoepa** [SamProf/MatBlazor#401]
Hi, is it possible to add the intial state of the MatIconButton to toggled?

I see you do have a protected property on the cs file linked below:
https://github.com/SamProf/MatBlazor/blob/95819c9dfb5d30aa6d9c44af48f48777224c2479/src/MatBlazor/Components/MatIconButton/BaseMatIconButton.cs#L41

Can we add an initial state like IsToggled which is an input paramater? Or even expose the toggled propety?

**Comment by SamProf** [comment]
Thank you for idea! Implemented!

**Comment by stoepa** [comment]
Great thanks so much, was just about to do this myself.
