### ISSUE TITLE
Small bug with numeric up/down field

### ISSUE THREAD

**Issue by xXBuilderBXx** [SamProf/MatBlazor#402]
Hi there is a small bug with the numeric field, i have set the Minimum to 0 and Maximum to 8 but if the value is 0 and you click down it goes to the max value of int 65535.

**Comment by SamProf** [comment]
Thanks!
I fixed this.

**Comment by SeppPenner** [comment]
This can be closed? @SamProf

**Comment by xXBuilderBXx** [comment]
Fixed
