### ISSUE TITLE
BUG : MatToaster Demo does not work...

### ISSUE THREAD

**Issue by vd3d** [SamProf/MatBlazor#403]
I have try both the web site and the demo (server) app, but when clicking on the button there is no toaster showing.

Also, I tried to force it to show and 2 side effects :
1- it does not disappear
2 - when I click the close button, it remain visible !

**Comment by SamProf** [comment]
Looks like I fix it. It was because I have some problems in MatSelect.
Is it fixed?

**Comment by lindespang** [comment]
Works fine for me, closing this one due to inactivity.
