### ISSUE TITLE
IMatToaster Inject in class throws a NullReference Exception

### ISSUE THREAD

**Issue by Bortronx** [SamProf/MatBlazor#405]
Whenever I try to use a toaster in a class it throws the following exception:

> System.NullReferenceException: Object reference not set to an instance of an object.

Example:

```
using MatBlazor;

public class MyClass
{
        [Inject]
        protected IMatToaster Toaster { get; set; }

        public  void foo()
        {
             Toaster.Add("Hello", MatToastType.Danger); // Exception on MyClass.cs:(this line)
        }
}
```

I have moved all my MatToasts to my razor code file as a workaround. That works fine.

**Comment by Bortronx** [comment]
I have moved all my MatToasts to my razor  code file

**Comment by SamProf** [comment]
Please, send all code, because how IMatToaster Toaster was injected. If this is component - all should be automaticaly, if not - not.

**Comment by Bortronx** [comment]
> Please, send all code, because how IMatToaster Toaster was injected. If this is component - all should be automaticaly, if not - not.

https://blazorfiddle.com/s/xotpic21

**Comment by vackodegamma** [comment]
[Inject] attribute should only be used with components (must inherit ComponentBase or implement IComponent). To inject a service into a class you must provide it in the constructor and the class itself has to be injected as well.

**Comment by Panzerfury** [comment]
You can do this:
```
public class ToasterHelper
{
        private readonly IMatToaster _matToaster;

        public ToasterHelper(IMatToaster matToaster)
        {
            _matToaster = matToaster;
        }
        //Methods
}
```

And then in your startup
```
 services.AddMatToaster(config =>
            {
                config.Position = MatToastPosition.BottomCenter;
                config.PreventDuplicates = true;
                config.NewestOnTop = true;
                config.ShowCloseButton = true;
                config.MaximumOpacity = 95;
                config.VisibleStateDuration = 3000;
            });
services.AddScoped<ToasterHelper>();
```

You can also make an interface for your Helper if you want

**Comment by Bortronx** [comment]
> You can do this:
> 
> ```
> public class ToasterHelper
> {
>         private readonly IMatToaster _matToaster;
> 
>         public ToasterHelper(IMatToaster matToaster)
>         {
>             _matToaster = matToaster;
>         }
>         //Methods
> }
> ```
> 
> And then in your startup
> 
> ```
>  services.AddMatToaster(config =>
>             {
>                 config.Position = MatToastPosition.BottomCenter;
>                 config.PreventDuplicates = true;
>                 config.NewestOnTop = true;
>                 config.ShowCloseButton = true;
>                 config.MaximumOpacity = 95;
>                 config.VisibleStateDuration = 3000;
>             });
> services.AddScoped<ToasterHelper>();
> ```
> 
> You can also make an interface for your Helper if you want

Thank you very much I was able to add an instance of the ToasterHelper with the IMatToaster to my static Utilities class which allows me to call the toaster from any class method in case of an error. I'm not sure if this is good practice but seems very useful for reporting errors outside of the console.

`services.AddScoped<ToasterHelper>();`

**Comment by Christian-Oleson** [comment]
@Bortronx ,
Are you still experiencing an issue? Ideally, we should be injecting this in startup so there is one instance only of the Toaster

**Comment by Bortronx** [comment]
When you inject at startup it works.  There is still no documentation on this maybe it should be added? But other than that the issue is resolved.

**Comment by Christian-Oleson** [comment]
@Bortronx ,
The documentation does show that this is needed to be injected at startup:
https://www.matblazor.com/Toast
`1. Startup.cs
Add using MatBlazor; and then in the ConfiguresServices method include services.AddMatToaster`
If you find this documentation sufficient, do you think you can close out your issue?

**Comment by Bortronx** [comment]
Sorry maybe I wasn't specific enough. From the beginning I had added what the documentation said. I am referring to this line:

`services.AddScoped<ToasterHelper>();`

**Comment by Christian-Oleson** [comment]
I'm not aware of the ToasterHelper, but it is not needed to make the toast work @Bortronx

**Comment by Bortronx** [comment]
I re read the documentation and I understand now that  the following:

> In a class:
> `                [Inject]
>                 protected IMatToaster Toaster { get; set; }`

Refers to a **ComponentBase** class. I understood that to mean any class within my solution. Maybe is obvious for everyone else but it wasn't for me.

**Comment by Christian-Oleson** [comment]
> I re read the documentation and I understand now that the following:
> 
> > In a class:
> > `                [Inject] protected IMatToaster Toaster { get; set; }`
> 
> Refers to a **ComponentBase** class. I understood that to mean any class within my solution. Maybe is obvious for everyone else but it wasn't for me.

@Bortronx ,
Would you like to open the PR then to clarify the points of confusion then? I want to make sure the documentation is as clear as possible.

**Comment by Bortronx** [comment]
Sure I will.
