### ISSUE TITLE
Is MatAutoComplete, completely non-functioning now?

### ISSUE THREAD

**Issue by americanslon** [SamProf/MatBlazor#406]
I saw MatAutoComplete is due to get a rewrite but is it completely not functioning now?
The simplest of the examples from matblazor.com doesn't seem to work with MatBlazor 2.0.1

**Comment by sandrohanea** [comment]
MatAutocompleteList should be functional now. After https://github.com/SamProf/MatBlazor/pull/548 most of the active issues will be fixed.

**Comment by enkodellc** [comment]
Merged fix into develop branch.
