### ISSUE TITLE
Using the value field without binding after 2.0.0 doesn't work

### ISSUE THREAD

**Issue by SeppPenner** [SamProf/MatBlazor#418]
After MatBlazor version 2.0.0, not binding to a value doesn't work anymore.

E.g. if you have a MatTextField with the following:

```razor
<MatTextField TValue="string" Value="ASDF" Label="Standard"></MatTextField>
```

this doesn't work anymore. In my case, I want to only provide fixed strings to such text fields in some cases. Is there another way to do this without having to use consts or fake properties with `@bind-Value`?

Example code in the fiddle: https://blazorfiddle.com/s/jf0oirmu

**Comment by lindespang** [comment]
Hi,
If I understand you correctly (You want a string literal in the MatTextField) then this blazor syntax will help you:

```
<p>
    <MatTextField TValue="string" Value=@("ASDF") Label="Standard"></MatTextField>
</p>
```
Closing this one. Please write back if I've misunderstood!

**Comment by SeppPenner** [comment]
Well okay. This looks like a workaround as well. Is there a way to support simple string values with `Value` and properties with `bind-Value`? I believe that this was removed in a prior version but didn't really understand why. Do you have some information on this? :)

**Comment by lindespang** [comment]
@SeppPenner I don't know, but I believe it's just a consequence of overall rework of input components. I guess it's quite rare to use Textfields without a backing property so it was probably not thought of :)

**Comment by SeppPenner** [comment]
Ah ok. No problem. And I know that most of the time, you do want to bind to values, not to simple texts.
