### ISSUE TITLE
MatTextField : Label or Dense doesn't use color Theme

### ISSUE THREAD

**Issue by tossnet** [SamProf/MatBlazor#419]
Hi!, If using a color theme (primary or secondary)  or simply via the website matblazor.com , we can be seen that the label color does not change :
![matf](https://user-images.githubusercontent.com/3845786/74012593-e97fc200-498a-11ea-9b40-290496baacba.png)

**Comment by americanslon** [comment]
Same with the arrow on the matselect

**Comment by Panzerfury** [comment]
You can temp fix the label with the following css

.mdc-text-field--focused:not(.mdc-text-field--disabled) .mdc-floating-label {
    color: rgb(96, 169, 44);
}

.mdc-floating-label--float-above {
    color: rgb(96, 169, 44) !important;
}

**Comment by lindespang** [comment]
This was recently fixed in PR #488 so I'm closing this one.
