### ISSUE TITLE
[Documentation]: Getting started

### ISSUE THREAD

**Issue by hailstorm75** [SamProf/MatBlazor#428]
# Introduction

Due to common breaking changes to the way this component library is to be setup I, as a new user, am quite confused on how to make everything work.

The provided documentations cover the components but do not cover how to correctly setup a new project for server-side and client-side blazor.

# The error

As of now I'm getting the following error:

 > **fail**: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[111]
      Unhandled exception in circuit 'tCSvfc0yL6OY4MQRpiGvHlQHrYvwR6TArvtftyJyl4s'.
Microsoft.JSInterop.JSException: Could not find 'matBlazor' in 'window'.
Error: Could not find 'matBlazor' in 'window'.
    at https://localhost:5001/_framework/blazor.server.js:8:30748
    at Array.forEach (<anonymous>)
    at p (https://localhost:5001/_framework/blazor.server.js:8:30709)
    at https://localhost:5001/_framework/blazor.server.js:8:31416
    at new Promise (<anonymous>)
    at e.beginInvokeJSFromDotNet (https://localhost:5001/_framework/blazor.server.js:8:31390)
    at https://localhost:5001/_framework/blazor.server.js:1:19202
    at Array.forEach (<anonymous>)
    at e.invokeClientMethod (https://localhost:5001/_framework/blazor.server.js:1:19173)
    at e.processIncomingData (https://localhost:5001/_framework/blazor.server.js:1:17165)
   at Microsoft.JSInterop.JSRuntime.InvokeWithDefaultCancellation[T](String identifier, Object[] args)
   at MatBlazor.BaseMatComponent.JsInvokeAsync[T](String code, Object[] args)
   at MatBlazor.BaseMatIconButton.OnFirstAfterRenderAsync()
   at MatBlazor.BaseMatComponent.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle)

I have included the required static files, blazor embedded content and added the required using.

# Tasks

To solve my issue and prevent others from having it I'd suggest writing a proper documentation:

- [ ] Write documentation for setting up Client-side
- [ ] Write documentation for setting up Server-side

**Comment by Mhirji** [comment]
I followed the instructions on the demo site for server side and had no issues, have not done client side to be honest. Do you have a repo to take a look at?

**Comment by hailstorm75** [comment]
Here is my project [repo](https://dev.azure.com/DenisAkopyan/Borec).
Initially I got it to work no problem; however, after the last update it broke.

**Comment by hailstorm75** [comment]
The only working version for me is 1.10.1

**Comment by Mhirji** [comment]
My setup is slightly different to yours.  It might have to do with the changes between 1.x versions and the 2.x versions.  I'll fork your repo this weekend and try and see where the issue is.

**Comment by Mhirji** [comment]
@hailstorm75 , so I cloned your unstable branch of the repo and ran the web application and it seems to work without any errors.  I did notice you have updated a number of dependencies, are things working for you as well or are you still having issues?

**Comment by hailstorm75** [comment]
@Mhirji I had to rollback my dependencies to MatBlazor 1.10.1 to continue working. Sorry for the confusion. If you update MatBlazor to the latest version you should be able to reproduce the issue.
Thank you for your help.

**Comment by Mhirji** [comment]
Ok, I'm a bit confused, but not by your rollback.  So here is what I have done.

1. Cloned your repo.
2. Updated MatBlazor to version 2.1.2
3. Borec.Web is the startup project
4. F5

The app starts and I notice nothing in VS logs or the browser debug console.

So, I am guessing this is correct, but am now trying to figure out where this your issue is coming from.  To help answer that, can you let me know what version of dotnet you are running?  For me it is 3.1.101.  Also, I did not do this with VS Code, but with Visual Studio, but don't think that would have made a difference.

**Comment by hailstorm75** [comment]
My version is identical. I work with both VS Code and Studio, latest versions.

Are you sure you were able to build the project? I've tried it right now with the latest MatBlazor version and got an error because the MatCheckbox no longer has a bind-Checked property. 

After fixing the error and running the program again I've successfully reproduced the issue.

I will create a second branch for attempting to fix this issue - MatBlazor

If you want, you can contact me via email so that we can speed things up and then post the verdict here.

**Comment by hailstorm75** [comment]
Thank you @Mhirji for checking out the repository and fixing the issue.

The solution was:

- Remove `@Html.EmbeddedBlazorContent()` from _Host.cshtml
- Remove `EmbeddedBlazorContent` microservice from the Startup
- Add `<link href="_content/MatBlazor/dist/matBlazor.css" rel="stylesheet" />` to the `<head>` of _Host.cshtml
- Add  `<script src="_content/MatBlazor/dist/matBlazor.js"></script>` after  `<script src="_framework/blazor.server.js"></script>`

You can find the chnages [here](https://dev.azure.com/DenisAkopyan/Borec/_git/Borec/commit/1e8e8047262008801e34457a7edb859088155856/)
  

As for the documentation issue I woud welcome a clearer tutorial on how to setup the theme. The applications in the project source are setup differently and were a point of reference for me.
