### ISSUE TITLE
Page fails to load using MatAutocompleteList inside MatDialog EditForm

### ISSUE THREAD

**Issue by tkennedy13** [SamProf/MatBlazor#430]
I am trying to use an MatAutocompleteList on a dialog edit form and the page crashes every time with the following errors showing in the dev console.

![image](https://user-images.githubusercontent.com/7343218/74569210-dbf8a800-4f47-11ea-8b57-49f024180db5.png)

I copied the code from the [sample](https://www.matblazor.com/AutocompleteList) into the root of my page and tried

`<MatAutocompleteList Items="@options2" TItem="Car" Label="Select car" CustomStringSelector="@(i => i.Name)" @bind-Value="@value" />`

and 

```
<MatAutocompleteList Items="@options2" TItem="Car" Label="Select car" CustomStringSelector="@(i => i.Name)" @bind-Value="@value">
     <ItemTemplate>
         <div style="display: flex; flex-direction: row; width: 100%;">
              <div style="flex: 1;">@context.Name</div>
             <div style="width: 150px;">@context.Price$</div>
        </div>
    </ItemTemplate>
</MatAutocompleteList>
```

and both autocomplete's loaded. When I put the same code inside of a

```
<MatDialog @bind-IsOpen="@dialogIsOpen">
	<MatDialogTitle>Create</MatDialogTitle>
	<MatDialogContent>
		<EditForm Model="@obj" OnValidSubmit="@CreateObj">
			<DataAnnotationsValidator />
			<ValidationSummary /> 
			<MatAutocompleteList Items="@options2" TItem="Car" Label="Select car" CustomStringSelector="@(i => i.Name)" @bind-Value="@value" />
		</EditForm>
	</MatDialogContent>
	<MatDialogActions>
		<MatButton OnClick="@(e => { dialogIsOpen = false; })">Cancel</MatButton>
		<MatButton OnClick="@CreateObj">Create </MatButton>
	</MatDialogActions>
</MatDialog>
```

it consistently gives the above referenced errors and the razor page will not load.

**Comment by tkennedy13** [comment]
Here is a related pull request. I didn't see this prior to opening this issue. https://github.com/SamProf/MatBlazor/pull/316

**Comment by enkodellc** [comment]
Merged fix into develop branch.
