### ISSUE TITLE
Upload files stop working

### ISSUE THREAD

**Issue by ALMLAMBO** [SamProf/MatBlazor#432]
I want to ask why after I upload a file with mat blazor the whole app stops working?

**Comment by SamProf** [comment]
Can you show me example of source code? It is because you have some exception

**Comment by ALMLAMBO** [comment]
I fix that. I want to ask how can I upload multiple files?

**Comment by Christian-Oleson** [comment]
@ALMLAMBO @SamProf @enkodellc 
This is not an issue. Can we please close out this issue?
