### ISSUE TITLE
MatDrawer selected indicator seems broken

### ISSUE THREAD

**Issue by NPadrutt** [SamProf/MatBlazor#438]
With the new Version 2.2 of the MatDrawer thge indicator for the currently selected item seems to be broken. For me the first item stays selected no matter which item I select besides:

![image](https://user-images.githubusercontent.com/1764367/75251202-6cea4180-57da-11ea-9ee9-0932cffc1944.png)

The same seems to be the case on the matblazor website:

![image](https://user-images.githubusercontent.com/1764367/75251192-6a87e780-57da-11ea-92e9-3aacf4448b4f.png)

**Comment by lindespang** [comment]
Hi! Thanks for using MatBlazor, this has been fixed in recent releases. Closing issue.

**Comment by NPadrutt** [comment]
Funny enough, this was fixed in the last version and for me it seems to be back again in the latest.

**Comment by lindespang** [comment]
Care to share a fiddle? MatBlazor.com looks fine to me.

**Comment by NPadrutt** [comment]
yeah that is what confuses me. I have to check if I missed some upgrade step or something to make it look like this:
![image](https://user-images.githubusercontent.com/1764367/81484595-ee346a80-9246-11ea-9654-44f926b7acd1.png)

I'll get back to you.

**Comment by NPadrutt** [comment]
So I checked in the blazor fiddle and there it looks okey. So far I haven't found any difference to my installation so I keep looking. Will keep you posted if I find something.

**Comment by NPadrutt** [comment]
Alright, I found my issue. I had to add this attribute on the "home" menu item:

`NavLinkMatch="NavLinkMatch.All"`

Otherwise it would match with all links.

**Comment by lindespang** [comment]
@NPadrutt Great to hear it! 👍
