### ISSUE TITLE
Can't see all items within a expansion panel

### ISSUE THREAD

**Issue by NPadrutt** [SamProf/MatBlazor#445]
I have multiple nested expansion panels which works great so far.

![image](https://user-images.githubusercontent.com/1764367/75759434-db2c8800-5d35-11ea-9d2d-32a7f1f4118b.png)

But when I expand all of those at a certain height the other panel doesn't expand anymore. Therefore you can't see all of the items:

![image](https://user-images.githubusercontent.com/1764367/75759514-fe573780-5d35-11ea-8ec8-5351825a2eaf.png)

**Comment by AmigoGringo** [comment]
I ran into the same problem. The max height is hardcoded to 1000px. For now my workaround is to add an extra .css file to the project and load it after the Matblazor one so u can override the Original css. Then add the following to the custom css file:

`.mat-accordion .mat-expansion-panel.mat-expansion-panel--expanded > .mat-expansion-panel__content, .mat-accordion .mat-expansion-panel.mat-expansion-panel--expanded .mat-expansion-panel__actions {
max-height: 100%
}`

100% seems to work fine for me, but u can also change it into 4000px for example to make it's max 4 times more then the original.

**Comment by NPadrutt** [comment]
oh nice, thanks for the work around! would it be possible that you submit a PR with that so that this can be fixed in an upcoming update?

**Comment by AmigoGringo** [comment]
> oh nice, thanks for the work around! would it be possible that you submit a PR with that so that this can be fixed in an upcoming update?

I'm new to GitHub, this was my first post. I will do that as soon as I have a better understanding of GitHub :)

**Comment by lindespang** [comment]
@AmigoGringo Here is a great guide to get started: https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

**Comment by AmigoGringo** [comment]
> @AmigoGringo Here is a great guide to get started: https://git-scm.com/book/en/v2/GitHub-Contributing-to-a-Project

Thank u i'll read into this.

**Comment by lindespang** [comment]
This issue is also described in issue #477 here and has an active PR which seems to fix the issue. Closing this one, thanks for feedback.
