### ISSUE TITLE
Remove dependency of fonts in javascript files.

### ISSUE THREAD

**Issue by nguyenvanbien95** [SamProf/MatBlazor#448]
Do you move linker fonts from absolute url to external link to modify? Some csp policy do not allow any external link from other site.

**Comment by enkodellc** [comment]
This should be resolved as of MatBlazor 2.1.0.  The fonts are still in matBlazor.css but you have more control to remove them in your project as you can edit / include the updated matBlazor.css file. Please re-open if you still have an issue.
