### ISSUE TITLE
Expansion Panel

### ISSUE THREAD

**Issue by enkodellc** [SamProf/MatBlazor#45]
I see other Material Repos with an Expansion Panel. I started building one and was curious if I did one is that something you would want in MatBlazor?  I can build in my repo and have you review it before submitting a PR.

Looking at the angular or the React as examples:

https://material-ui.com/demos/expansion-panels/
https://material.angular.io/components/expansion/overview#action-bar

A couple of questions if you want. Where is the best place to put custom css or javascript? I have not come across any place yet in your repo.

**Comment by SamProf** [comment]
Hey!

Here is web project. You can put css (scss) and js inside this project.
MatBlazor\src\MatBlazor.Web\

**Comment by SamProf** [comment]
I want to implement first version of expansion panels. Did you start?

**Comment by enkodellc** [comment]
@SamProf  I was about to as I was busy with other project for a few weeks. I just saw this repo and was going to review some of their code: https://github.com/chanan/BlazorStrap  If you want to take the lead on it go ahead.

**Comment by SamProf** [comment]
I am already on 70% complete Extension Panels.

**Comment by SamProf** [comment]
Hey!
First version https://www.matblazor.com/ExpansionPanel

Not for release now, but already works.

I want at monday make release 1.0.0 =)

**Comment by enkodellc** [comment]
Looks good,  Sorry for not completing. I needed to get my boilerplate going. So far all the MatBlazor components are working great on it.  I need to have that framework going for a project so it is a good test bed for the components.
