### ISSUE TITLE
Default button type should be button in MatButton

### ISSUE THREAD

**Issue by MarkStega** [SamProf/MatBlazor#452]
I am using MatButtons in an EditForm. The form is getting submitted on button presses. If I override the default type with 'Type="button"' then the unwanted submit does not occur. I'd suggest that the Type parameter should default to 'button' rather than null. This is being observed in FF 74.0

**Comment by Christian-Oleson** [comment]
@MarkStega ,
The button has been changed quite a bit recently. Can you test and confirm if this issue is still present in 2.8?

**Comment by MarkStega** [comment]
I no longer have an appropriate testbed...
