### ISSUE TITLE
Cannot use on Razor Component Library

### ISSUE THREAD

**Issue by endeffects** [SamProf/MatBlazor#460]
I cannot use the MatBlazor Nuget Package on Razor Component Library.
It allways says that the reference is not found and offers to install it.
It works fine on the host project. Any ideas?

**Comment by Alexbits** [comment]
I'm using it without any issues in the library. Check your library cproj file. I have the following.

```
<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <RazorLangVersion>3.0</RazorLangVersion>
    <LangVersion>8.0</LangVersion>
  </PropertyGroup>
</Project>
```

**Comment by endeffects** [comment]
Thank you, the default framework from the razor template was netstandard, changing this fixed the issue.
