### ISSUE TITLE
MatTooltip does not work for MatIcon

### ISSUE THREAD

**Issue by endeffects** [SamProf/MatBlazor#464]
I tried to use the Tooltip Component on MatIcons, but i got an exception:

Microsoft.JSInterop.JSException: e.addEventListener is not a function

Do you plan to fix this or do i have to wrap the icon with a span?

**Comment by endeffects** [comment]
Had to use  Wrap="true"

**Comment by Apollo3zehn** [comment]
Alternatively, set `TargeId`:

```html
<MatTooltip Tooltip="Test" TargetId="my-id">
    <span id="my-id">content</span>
</MatTooltip>
```

The tooltip uses an invalid tooltip content reference that has no property `addEventListener`. By setting the `TargetId` the invalid reference gets overriden by a valid one.
