### ISSUE TITLE
Add CircularProgress

### ISSUE THREAD

**Issue by ydyote** [SamProf/MatBlazor#473]
It would be nice if the CircularProgress was also available.

I made something myself but I'm garbage at these kind of things so it works very weird, maybe it will help somebody for the time being. I wanted it to have also different sizes. I took https://codepen.io/ConAntonakos/pen/ryMaOX put it into a component and something came out. Its pretty bad but maybe it will help somebody or it will inspire somebody.

The math is complete trash (I created some unnecessary and weird math dependencies of things which doesn't correlate at all) and also I don't completely understand css animation but here it is..

[CircularProgressMaterial.cs.txt](https://github.com/SamProf/MatBlazor/files/4395996/CircularProgressMaterial.cs.txt)
[CircularProgressMaterial.razor.txt](https://github.com/SamProf/MatBlazor/files/4395997/CircularProgressMaterial.razor.txt)
[Index.razor.txt](https://github.com/SamProf/MatBlazor/files/4395998/Index.razor.txt)

**Comment by naretto** [comment]
New release contains this: https://www.matblazor.com/ProgressCircle
Would that be what you are looking for?

**Comment by ydyote** [comment]
yeah I think so, therefore this issue can be closed. maybe somebody should add the version or something here so its clear in which version includes this control

**Comment by Christian-Oleson** [comment]
@ydyote ,
Can you please close this issue? I do not have the ability to do so.
