### ISSUE TITLE
remove the launchSettings from the nuget package

### ISSUE THREAD

**Issue by knoxi** [SamProf/MatBlazor#476]
The nuget package contains `launchSettings.json` files, which are automatically added to the project when referencing the nuget package.

Please remove the `launchSettings.json` from the nuget package.

![image](https://user-images.githubusercontent.com/5229316/78130454-9f124300-7419-11ea-9ec2-7977dac83c47.png)

**Comment by Phylum123** [comment]
+1

**Comment by Christian-Oleson** [comment]
@knoxi @Phylum123 ,
What sort of issue is this causing?

**Comment by knoxi** [comment]
I'm not quite sure anymore, but I think it was this problem:

After a restore or upgrade the one of the MatBlazor package, the `launchSettings.json` of the package is used instead.

This can be reproduced by creating a Blazor server app, remove the existing launchSettings and then add the package.

![image](https://user-images.githubusercontent.com/5229316/102749835-ffa92d80-4364-11eb-9b84-d7d370a55ba1.png)

**Comment by SamProf** [comment]
fixed @stefanloerwald
