### ISSUE TITLE
MatNavItem styling

### ISSUE THREAD

**Issue by esso23** [SamProf/MatBlazor#478]
When I applied height style to MatNavItem, the style got overriden by some other MatBlazor styles. Expected behavior: style should be applied last.
Code:
```cs
<Styled @bind-Classname="@NavItemStyle">
    height: auto;
</Styled>

<MatNavSubMenuList>
        @foreach (var station in mStations)
        {
            <MatNavItem @key="station.Id" class="@NavItemStyle">
                <MatIcon Icon="details"></MatIcon>
                <p class="@TextStyle">@station.Name</p>
            </MatNavItem>
        }
</MatNavSubMenuList>

@code
{
    private string NavItemStyle;
}
```

![matblazorstyles](https://user-images.githubusercontent.com/5548662/78230381-8b2a1800-74d1-11ea-9e5e-cd3d3f402ee7.PNG)

**Comment by enkodellc** [comment]
@esso23  Where are you getting the "Styled" component.  Please create a functioning BlazorFiddle for me to recreate your issue.

**Comment by esso23** [comment]
It's a library: https://github.com/chanan/BlazorStyled
Anyway, its seems to be an issue with the library itself and not MatBlazor. I made some research into it recently but forgot about this issue. So i'm closing this one.
