### ISSUE TITLE
Issue when building MatBlazor.Web

### ISSUE THREAD

**Issue by esso23** [SamProf/MatBlazor#479]
I'm getting this error when building MatBlazor.Web project. Any tips how to fix this?

![Screenshot 2020-04-02 17 58 35](https://user-images.githubusercontent.com/5548662/78271080-08727e80-750c-11ea-87b9-a80ed804a6f5.png)

**Comment by RonPeters** [comment]
This may be a silly question, but did you run npm install?

**Comment by esso23** [comment]
I was expecting that question :D Yes I did.

**Comment by esso23** [comment]
Ok, I managed to fix this. It looks like a known issue.
1. I did this: https://github.com/material-components/material-components-web/issues/5502#issuecomment-586061492
`npm uninstall node-sass`

2. this: https://github.com/material-components/material-components-web/issues/5502#issuecomment-587493832
Added to prod.config.js

**Comment by RonPeters** [comment]
Reading the thread on material-components, it looks like we should remove node-sass from package.json

**Comment by lindespang** [comment]
Closing this one as a fix was merged (Works fine for me with a clean git clone)
