### ISSUE TITLE
NavMenu dropdown icon positioning issue

### ISSUE THREAD

**Issue by DrXSsive** [SamProf/MatBlazor#485]
Hi Creators,

I hope you all are doing great. I am having issue with NavMenu. I recently started using Matblazor and copy exact code from your website. Here is the issue I am facing:
![Github issue](https://user-images.githubusercontent.com/40558386/78473059-b4a3a780-774e-11ea-8d23-e7aa35bccde8.PNG)

As you can see the dropdown arrow positioning is not correct. I am also pasting my code for your reference. My NavMenu is in MatDrawer:

```
<MatDrawer @bind-Opened="@DrawerOpened" Style="background-color:#eceff1;">
    <MatNavMenu>
        <MatNavSubMenu>
            <MatNavItem><MatIcon Icon="dashboard"></MatIcon>&nbsp; Dashboard</MatNavItem>
            <MatNavSubMenuHeader>
                <MatNavItem AllowSelection="false"><MatIcon Icon="location_city"></MatIcon>&nbsp; City Management</MatNavItem>
            </MatNavSubMenuHeader>
            <MatNavSubMenuList>
                <MatNavItem Href="#"><MatIcon Icon="list"></MatIcon>&nbsp; Cites</MatNavItem>
                <MatNavItem Href="#"><MatIcon Icon="add"></MatIcon>&nbsp; Add New</MatNavItem>
            </MatNavSubMenuList>
        </MatNavSubMenu>
    </MatNavMenu>
</MatDrawer>
```

I hope someone can help me with this issue.

Thank you
Best Regards
J

**Comment by DrXSsive** [comment]
I had this in my code
`<MatDrawerContainer Style="width: 100vw; height: 100vh;">`

and when I removed width, it's working properly now.

**Comment by DrXSsive** [comment]
Closed issue by mistake.

**Comment by enkodellc** [comment]
@DrXSsive  have a look at the menu on https://blazorboilerplate.com/  

I added this css to my css to adjust the margin to center it better vertically. 

```
.mdc-drawer .mdc-list-item {
    margin: 8px 0 !important;
}
```

**Comment by DrXSsive** [comment]
It was just the issue of line-height. I added "line-height: 1;" in body element, and everything just works fine.

Cheers
