### ISSUE TITLE
MatTextField Label not adhering to Theme colors

### ISSUE THREAD

**Issue by gstew45** [SamProf/MatBlazor#486]
When a theme is applied the default label text does not take the primary color of the theme

![image](https://user-images.githubusercontent.com/6470958/78500344-c0429e80-774d-11ea-81b1-303e3d345c23.png)

![image](https://user-images.githubusercontent.com/6470958/78500419-24656280-774e-11ea-8924-84e64f301ac8.png)

I'm not sure if there is a workaround at the moment but this should take the theme colors like the rest of the TextField does

**Comment by esso23** [comment]
Yes, themes seem to be kinda broken or not completely implemented as of now. See
https://github.com/SamProf/MatBlazor/issues/470
https://github.com/SamProf/MatBlazor/issues/419

**Comment by gstew45** [comment]
Thanks for the reply, sorry I should have had a deeper look into duplicate tickets.

I'll apply a workaround now and might start taking a look at implementing a fix
