### ISSUE TITLE
Issue with MatDrawerContainer height and width

### ISSUE THREAD

**Issue by DrXSsive** [SamProf/MatBlazor#487]
Hi Creators,

I hope you are doing great. When using MatDrawerContainer I am facing a weird issue. I have used following as per your example:
`<MatDrawerContainer Style="width: 100vw; height: 100vh;">`
ideally it should take full screen but it is adding additional space on both bottom and right side of MatDrawerContainer. Please see the attached image for reference
![GitHub Issue](https://user-images.githubusercontent.com/40558386/78508815-d32f9000-779a-11ea-9aa2-e63643bc8425.PNG)

Here is my layout file:
https://gist.github.com/DrXSsive/ea09221c236d3ea4c6848512d8a11aea

Any help will be appriciated.

Thank you
J

**Comment by esso23** [comment]
You have some weird nesting there. Do it like this. And don't use the `<MatAppBarContainer>`.

```html
<MatAppBar Fixed="true" Style="z-index: 100;">
    <MatAppBarRow>
        ...
    </MatAppBarRow>
</MatAppBar>

<MatDrawerContainer Style="width: 100vw; height: 100vh;" Class="mat">
    <MatHidden Breakpoint="@MatBreakpoint.MD" Direction="@MatHiddenDirection.Up" HiddenChanged="@ModelDrawerHiddenChanged">
      ...
    </MatHidden>

    <MatDrawerContent Class="@DrawerContentStyle">
        <AppBarAdjust />
        @Body
    </MatDrawerContent>
</MatDrawerContainer>
```

**Comment by DrXSsive** [comment]
I removed all the container wrappers and added this to MatDrawer
`<MatDrawer @bind-Opened="@DrawerOpened" Mode="@MatDrawerMode.Modal" Style="background-color:#eceff1; height:100vh">`
See styling, I added height:100vh to cover up whole height but still it has extra height on bottom.

**Comment by EduVencovsky** [comment]
If you take a look at [default css values](https://www.w3schools.com/cssref/css_default_values.asp) you will see that `body` have `margin: 8px;` have you tried to remove this? I had that problem once and it was because of the  default css / other library changing the body and making this weird behavior.

**Comment by esso23** [comment]
You're right, I found this in my project in _Host.cshtml:
```html
@* TODO: Find out why the margin: 0 is required *@
<body style="margin: 0">
```

Totally forgot about it :D

**Comment by lindespang** [comment]
@esso23 I take it as clearing the margin resolved the issue? If not, please write back 👍

**Comment by DrXSsive** [comment]
> @esso23 I take it as clearing the margin resolved the issue? If not, please write back 👍

Hi,

sorry for late reply, yeah Margin solved the issue.

Thanks
