### ISSUE TITLE
Question: Is it posible to combine MatTable and MatSortHeader?

### ISSUE THREAD

**Issue by TPIvan** [SamProf/MatBlazor#492]
In [documentation ](https://www.matblazor.com/SortHeader) it is not clearly stated and `<MatSortHeader>` is combined with `<table>`. Is it possible to use `<MatSortHeader>` for sorting `<MatTable>`?

**Comment by PA4WD** [comment]
I made a fix to get this working
https://github.com/PA4WD/MatBlazor/commit/4f709fc83bb3262ab78367eb3360a42e743ead59

**Comment by adrianex03** [comment]
How?

**Comment by adrianex03** [comment]
Hello@enkodellc,

I have tried the solution you provided but a problem with the table designs has happened. I will show you my code and a picture of the table 

    <MatTable Items="@sortedData" class="mat-elevation-z5" ShowPaging="false" UseSortHeaderRow="true">
        <MatTableHeader>
            <MatSortHeaderRow SortChanged="@SortData">
                <MatSortHeader>
                        <MatButton Icon="person_add" Label="Add Movie" OnClick="@(e => dialogIsOpen = true)"></MatButton>
                </MatSortHeader>
                <MatSortHeader SortId="title">Title</MatSortHeader>
                <MatSortHeader SortId="price">Price</MatSortHeader>
                <MatSortHeader SortId="genre">Genre</MatSortHeader>
                <MatSortHeader SortId="releaseDate">Release Date</MatSortHeader>
                <MatSortHeader SortId="rating">Rating</MatSortHeader>
            </MatSortHeaderRow>
        </MatTableHeader>
        <MatTableRow>
            <td>
                <div>
                    <MatIconButton Style="color:purple" Icon="edit" OnClick="@(() => Edit(context))"></MatIconButton>
                    <MatIconButton Style="color:purple" Icon="delete" OnClick="@(() => ConfirmDelete(context))"></MatIconButton>
                </div>
            </td>
            <td>@context.Title</td>
            <td>@String.Format("${0:f2}", context.Price)</td>
            <td>@context.Genre</td>
            <td>@context.ReleaseDate.Value.ToShortDateString()</td>
            <td>@context.Rating</td>
        </MatTableRow>
    </MatTable>


![Screen Shot 2020-05-19 at 8 51 30 PM](https://user-images.githubusercontent.com/38744266/82392695-87673c00-9a12-11ea-9ed7-a5b4fcddad24.png)

**Comment by enkodellc** [comment]
To use the updated code you need to download / build / use the "develop" branch code yourself as it is not fully released yet. This is why you are getting this error.

**Comment by adrianex03** [comment]
ok ,thanks
