### ISSUE TITLE
MatTextField Label not correct when using RTL dirction

### ISSUE THREAD

**Issue by T-Alkathiri** [SamProf/MatBlazor#502]
When using rtl direction the MatTextField Label dos not show to the right of the textfield it stay on left as if it is ltr direction.
Please Is there any solution to fix this issue, or it is like this dos not suppurt rtl.
Thank you very much.

**Comment by EduVencovsky** [comment]
Are you sure? I just added `dir="rtl"` in the `body` and it's working.
![image](https://user-images.githubusercontent.com/37600269/80094958-8a6b2b80-853d-11ea-969c-57769747638f.png)

**Comment by T-Alkathiri** [comment]
Yes with this way it is working good.
I was using direction: rtl in the css but did not work.
Thank you very much for your help.

**Comment by lindespang** [comment]
@T-Alkathiri Have your issue been resolved so we can close this again? Noticed that you reopened it but no comments!:)

**Comment by T-Alkathiri** [comment]
Yes i have your issue been resolved.
Thank you very much.
