### ISSUE TITLE
UI not updating for custom child components

### ISSUE THREAD

**Issue by t0ralf** [SamProf/MatBlazor#506]
I'm using MatBlazor TabGroup, but when I wrap a MatTab in a custom component and perform some action that should update the UI it will not do that.

I'm using .Net Core 3.1 and Visual Studio 2019 16.5.1

To reproduce the behavior, just create a new Blazor Server project, install MatBlazor and remove the markup of index.razor.

The following code works!
```
@page "/"

<MatTabGroup>
    <MatTab Label="My first tab">
        <h1>Counter</h1>

        <p>Current count: @currentCount</p>

        <button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
    </MatTab>
    <MatTab Label="My second tab">

    </MatTab>
</MatTabGroup>

@code
{

    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }

}
```

However, if one wraps the first tab in a custom component (say MyTestComponent.razor) like that:

```
<MatTab Label="My first tab">
    <h1>Counter</h1>

    <p>Current count: @currentCount</p>

    <button class="btn btn-primary" @onclick="IncrementCount">Click me</button>
</MatTab>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;       
    }
}
```

and then replace the first tab in index.razor like that
```
@page "/"

<MatTabGroup>
    <MyTestComponent></MyTestComponent>
    <MatTab Label="My second tab">

    </MatTab>
</MatTabGroup>

@code
{}
```
it will not work anymore. Even calling StateHasChangedMethod in the IncrementCount method like that
```
private void IncrementCount()
    {
        currentCount++;
        InvokeAsync(StateHasChanged);
    }
```

won't do the trick.

I would expect that, at least after calling the StateHasChanged method, the UI would update properly.

What am I doing wrong? Or is that to be expected?

**Comment by lindespang** [comment]
Hi! Thanks for using MatBlazor. Im closing this as a duplicate and ask you to follow this here #495
