### ISSUE TITLE
Edit css

### ISSUE THREAD

**Issue by UrizielTSD** [SamProf/MatBlazor#509]
I want to adjust the styling of the table, but I can´t find the CSS which is supposed to be added under wwwroot/dist
Where can I find it?

**Comment by frankhale** [comment]
Have a look at the MatBlazor.Web project 

https://github.com/SamProf/MatBlazor/tree/master/src/MatBlazor.Web/src

You'll need to compile the project yourself to produce the final assets after your changes. Each component has it's own Sass file which is then ultimately compiled into a CSS file. Find your component, edit it's Sass file and then build a production release to get the assets.

**Comment by frankhale** [comment]
Read issue https://github.com/SamProf/MatBlazor/issues/479 so you can get the MatBlazor.Web project to build

**Comment by UrizielTSD** [comment]
Thanks,
I thought that the library added both files to my project without the need to recompile.

**Comment by lindespang** [comment]
Hope that answered your question @UrizielTSD , I'm closing this issue as it seems solved. Please get back if you don't agree.

**Comment by UrizielTSD** [comment]
It´s not resolved yet,

I managed to set everything up and compile the Web Project.

But every compiled CSS produces this error in usage:
![image](https://user-images.githubusercontent.com/27346238/80358320-82342880-887c-11ea-8566-839f82732760.png)

I even compiled without making any changes to the CSS, same result.

Workflow:
-> NPM Build
-> Build MatBlazor Lib
-> Execute Demo Server Side

**Comment by UrizielTSD** [comment]
Also, whenever I use the compiled MatBlazor bin in my project it result in this error:
![image](https://user-images.githubusercontent.com/27346238/80365084-54a0ac80-8887-11ea-9c32-191fa30ab545.png)

But the Demo Project works just fine, only my project which includes the bin gets errors.

**Comment by frankhale** [comment]
Hmm, yesterday I set up my environment to compile this as well. I ran into the CSS issue right away (eg. npm run build would fail with SASS errors). I followed the information on #479 and that worked for me. You have to remove node-sass and then modify the configuration of the webpack config and add `webpackImporter: false` to the options right beneath `loader: "sass-loader"`. Once I did that the CSS issues went away.

My workflow would be make my modifications to the JS project and then build and run the matblazor-web project. It all worked for me fine. 

@UrizielTSD can you confirm that is the workflow you are doing?

**Comment by UrizielTSD** [comment]
@frankhale 
I did this workflow while setting the project up.
But the errors occur after compiling successfully the new CSS and using it in the demo project.

Does your compiled css/js work without any issue?

**Comment by frankhale** [comment]
> Does your compiled css/js work without any issue?

Yes the CSS/JS work without issue when I compile it and run matblazor-web.

**Comment by UrizielTSD** [comment]
@frankhale Did you try to run the Matblazor.demo.server/clientapp ?

**Comment by frankhale** [comment]
I was testing with the MatBlazor.Web project.

I didn't run Matblazor.demo.server/clientapp

**Comment by enkodellc** [comment]
You should not have to rebuild MatBlazor just to update your CSS.  Refer to #88 for MatTable Styling classes

I just have my styles in  BlazorBoilerplate:  https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.CommonUI/wwwroot/css/site.css  then just make sure you add your custom css after the matblazor.css:

https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.Server/wwwroot/index_csb.html

With #527 and this information it should solve your issues.

**Comment by enkodellc** [comment]
Hopefully this helps:  https://github.com/SamProf/MatBlazor/wiki/How-to-Edit-the-css---scss-styles-for-MatBlazor
