### ISSUE TITLE
MatDrawer right side

### ISSUE THREAD

**Issue by kristof12345** [SamProf/MatBlazor#515]
Hi!

Is it possible to put MatDrawer to the right side of the page?

Thanks.

**Comment by enkodellc** [comment]
I did a quick test and it I think you can just create your own css to change which side the drawer is on. This will get you close:

 ```
   <style>
        app { }

            .mdc-drawer--modal{
                left: initial;
                right: 0;
            }

            .mdc-drawer--animate {
            transform: translateX(-100%); }
            [dir="rtl"] .mdc-drawer--animate, .mdc-drawer--animate[dir="rtl"] {
                transform: translateX(-100%); }

            .mdc-drawer--opening {
            transform: translateX(-11);
            transition-duration: 250ms; }
            [dir="rtl"] .mdc-drawer--opening, .mdc-drawer--opening[dir="rtl"] {
                transform: translateX(0); }

            .mdc-drawer--closing {
            transform: translateX(100%);
            transition-duration: 200ms; }
            [dir="rtl"] .mdc-drawer--closing, .mdc-drawer--closing[dir="rtl"] {
                transform: translateX(100%); }
    </style>
```

**Comment by kristof12345** [comment]
Thanks. A little modification did the trick.
For me this worked:

`.mdc-drawer--modal {
    width: 380px;
    left: initial;
    right: 0;
}

.mdc-drawer--animate {
    transform: translateX(100%);
}

    [dir="rtl"] .mdc-drawer--animate, .mdc-drawer--animate[dir="rtl"] {
        transform: translateX(-100%);
    }

.mdc-drawer--opening {
    transform: translateX(11px);
    transition-duration: 250ms;
}

    [dir="rtl"] .mdc-drawer--opening, .mdc-drawer--opening[dir="rtl"] {
        transform: translateX(0);
    }

.mdc-drawer--closing {
    transform: translateX(100%);
    transition-duration: 200ms;
}

    [dir="rtl"] .mdc-drawer--closing, .mdc-drawer--closing[dir="rtl"] {
        transform: translateX(100%);
    }`

**Comment by enkodellc** [comment]
Also review:  #381

https://stackoverflow.com/questions/59707701/how-to-make-matblazor-rtl-right-to-left
