### ISSUE TITLE
MatTextField two way binding is not working

### ISSUE THREAD

**Issue by DrXSsive** [SamProf/MatBlazor#517]
Hi,

Hope you all doing great. So, I created a form with some details and bound "MatTextField" to variable defined in VM with "@bind-Value" but when I change value in text box and try to get value in function, the value of bound variable is not updated. Here is my code:

        <EditForm Model="Context" OnValidSubmit="() => Context.UpdateCompany(companyid)">

            <DataAnnotationsValidator />

            <div class="mat-layout-grid" style="padding: 0px !important">
                <br />
                <div class="mat-layout-grid-inner">
                    <div class="mat-layout-grid-cell mat-layout-grid-cell-span-6">
                        <MatTextField @bind-Value="@Context.Name" Label="Name" Style="width:100%;"></MatTextField>
                        <br />
                        <br />
                        <ValidationMessage For="@(() => Context.Name)" />
                    </div>
                    <div class="mat-layout-grid-cell mat-layout-grid-cell-span-6">
                        <MatTextField @bind-Value="@Context.MasterKey" Label="Master Key" Style="width:100%;"></MatTextField>
                        <br />
                        <br />
                        <ValidationMessage For="@(() => Context.MasterKey)" />
                    </div>
                </div>
                
                <div class="mat-layout-grid-inner">
                    <div class="mat-layout-grid-cell">
                        <MatButton Raised="true" Icon="update" Type="submit">Update Company</MatButton>
                    </div>
                </div>
            </div>
        </EditForm>

This my Razor component. I have a VM class in this component which is initializing like this:

    private UpdateCompanyVm Context;

    protected override void OnInitialized()
    {
        base.OnInitialized();

        Context = new UpdateCompanyVm(NavigationManager, CompanyService);
    }

And my VM has public properties

        [Required]
        public string Name { get; set; }

        public string Address { get; set; }

Now there is function in my VM which is called when form is submitted successfully. 

        public async Task UpdateCompany(string companyid)
        {
            StartLoading();

            RequestCreateCompany request = new RequestCreateCompany
            {
                Name = this.Name,
                Address = this.Address
            };

            ResponseObject<Company> serviceResponse = await _companyService.UpdateCompany(companyid, request);

            if (serviceResponse.IsSucceeded)
            {
                ShowSuccessMessage("Company updated successfully");
            }
            else
            {
                ShowErrorMessage(serviceResponse.Error);
            }

            StopLoading();
        }

Whenever this function is called, "this.Name" and "this.Address" have old values, although I change them in the text field in the front end.

Any help will be appreciated.

Thank you

Regards
J

**Comment by RonPeters** [comment]
Hi. Thanks for using MatBlazor. Try changing `@bind-Value="@Context.Name"` to `@bind-Value="Context.Name"`. Remove the second @. Also, I assume you meant Address instead of MasterKey in your example. Let us know if this works for you.

**Comment by DrXSsive** [comment]
Hi,

Thank you for your reply. I changed that to @bind-Value="Context.Name" but it's still not working.

Oh yes sorry for that, actually I had many fields and I just put two fields for example.

Cheers

**Comment by lindespang** [comment]
Hello!

I implemented a mock version of your problem in blazorfiddle and it seems to work fine for me:
https://blazorfiddle.com/s/hzzr84t6

Is this what you can't achieve? Or am i missing something?

**Comment by DrXSsive** [comment]
Hi there,

Yes, this is exactly what not happening on my side. Whenever I update value in "MatTextField" and leaves focus, it changes back to the old value. Something strange is happening on my side. I am getting data from my Web Api, then setting it on "OnAfterRenderAsync" method. Maybe I am making my VM class in separate file? That should not be an issue. I really need this to sort out fast, it's my company's project and dead line is coming :(

Regards
J

**Comment by DrXSsive** [comment]
I put an event on "OnInput" to see if actually events are triggering when the value in the text box changed. The event triggered with the changed value, I tired to assign that value in that event call, but same results, bound value jumped back to old value.

**Comment by DrXSsive** [comment]
Ok so, If I declare variable in same component @code, it is working fine, but as soon as I change to "Context.Name" which is my ViewModel class, it reverts back to old value. Very strange behavior. I will keep you guys posted if I will find something.

Cheers

**Comment by DrXSsive** [comment]
Ok here I am again. "@bind-Value" is not working if we bind value from another .cs class in a separate file. I just checked that on "MatSelect"...

**Comment by RonPeters** [comment]
I use view models defined in separate files all the time. There is something else going on here. Perhaps Context is being created twice (OnInitialize will get called twice if RenderMode is ServerPrerendered) and the wrong instance is being bound to the component.

I have yet to get a real benefit from pre-rendering, so I set RenderMode to Server in my projects.

**Comment by DrXSsive** [comment]
"<component type="typeof(App)" render-mode="Server" />" Changed render mode to server, still not working.

**Comment by RonPeters** [comment]
I am quite sure this is not a bug in MatBlazor. I make extensive use of view models contained in external assemblies.

What I find when setting bound values in async handlers is that Blazor renders the DOM before the async call completes. So try calling  StateHasChanged() after you update the values to get synchronized.

**Comment by DrXSsive** [comment]
You are absolutely right Ron, it was all me. After almost 10 hours I found that it was my fault :D. I was taking all data from server in "OnAfterRenderAsync" (I assume it is called every time when we call StateHasChanged?) method. After moving everything to "OnInitializedAsync", it is working like a charm. Thank you so much for your time and your suggestions, it helped a lot.

Cheers
J
