### ISSUE TITLE
Q: Width of the visual elements (select)

### ISSUE THREAD

**Issue by vcaraulean** [SamProf/MatBlazor#521]
Hi

I'm looking to change the width of elements (select, text field) and can't find a way to make it work reliably. Some of elements do have a `FullWidth` property which makes them fill the parent's container, while other don't have this property available.

So, how do I change width of `MatSelectItem` and `MatSelectValue` or make it fill the parent container?

**Comment by RonPeters** [comment]
I've had good experience using flexbox o achieve this. I put a wrapper div for a row of form elements with something like this for CSS:
`.form-field-row {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
    align-items: center;
    margin: 12px -4px;
}`

Then add a utility class for each element:
`.form-field-full-width {
   flex-grow: 1;
   margin: 0 4px;
}`

or 
`.form-field-half-width {
   flex-grow: 2;
   margin: 0 4px;
}`

The flex-grow property controls the relative size of the elements. For selects, I need to add a little more (SASS):
`.form-field-row .mdc-select {
    .mdc-select__anchor {
        width: 100%;
    }
    .mdc-select__menu {
        width: 100%;
    }
}`

This is not really an issue but more of a general question regarding Material Web Components, so I'm going to close this out. Hope this helps!
