### ISSUE TITLE
MatFileUpload size limits

### ISSUE THREAD

**Issue by americanslon** [SamProf/MatBlazor#531]
Is there a file/upload limit on the control or not yet?

MaxMessageLength, MaxMessageSize don't seem to do anything as I set them both to 1024 and was able to upload a 5mbs file.

**Comment by lindespang** [comment]
Hi!

Thanks for using MatBlazor.

Those parameters are for the messages sent to the servers containing chunks of file data, not for restricting file size.

I'll label this as an enhancement suggestion.

**Comment by americanslon** [comment]
I didn't notice this originally but `IMatFileUploadEntry` exposes size property. It's probably the job of the code using MatFileUploader to check the size anyway so as far as I am concerned you can close this.

**Comment by Christian-Oleson** [comment]
@americanslon ,
if you agree this can be closed, will you please close this?
