### ISSUE TITLE
Question: How to increase the size of MatDialog 

### ISSUE THREAD

**Issue by sowsan** [SamProf/MatBlazor#535]
How can I increase the overall size (width and height) of MatDialog ? Its always rendering with a fixed size even though if I specify the heigh and width for MatDialog in the style attribute.

https://www.matblazor.com/Dialog

Thanks for your help!

**Comment by americanslon** [comment]
I don't think it can be done without overriding some MDC classes.
This is how I do it.

`.large {
        .mdc-dialog__surface {
            min-width: 80vw !important;
        }
    }

    .medium {
        .mdc-dialog__surface {
            min-width: 60vw !important;
        }
    }
`

**Comment by PKeeneATX** [comment]
Well that was it!! 
I replaced the above with...

.mdc-dialog .mdc-dialog__surface {
        max-width: none !important;   
    }

**Comment by enkodellc** [comment]
Duplicate #143
