### ISSUE TITLE
MatTextField - FullWidth=true hides the Label

### ISSUE THREAD

**Issue by ribagyula89** [SamProf/MatBlazor#536]
Good morning!

First of all: thank you for this great framework!

I found a bug in the latest release (2.5.0 - preview-005): in my Blazor client-side the MatTextField Label is not visible if I set the FullWidth property to true.

You can check it on the sample page [(https://www.matblazor.com/TextField)](https://www.matblazor.com/TextField) in the "Full Width" section too.

Thank you!

![fw](https://user-images.githubusercontent.com/55386827/81494827-fc68a200-92ab-11ea-9940-ad814009beaf.JPG)

**Comment by enkodellc** [comment]
This should be fixed from these 2 commits in Develop. 

https://github.com/SamProf/MatBlazor/commit/a78754e3920c5645bab9240a6822b746aaf9a185
& 
https://github.com/SamProf/MatBlazor/commit/7e0cf2dbcf83a1f2669859c82ef555280e5bf8ce

**Comment by enkodellc** [comment]
Here is the updated code for the develop branch that fixes it. I am submitting a PR now for others to test:
```

/* Fix Full Width padding issues */
label.mdc-text-field.mdc-text-field--fullwidth:not(.mdc-text-field--textarea) > input.mdc-text-field__input {
  padding: 10px 16px 6px;
}

label.mdc-text-field--fullwidth-with-trailing-icon:not(.mdc-text-field--textarea) > input.mdc-text-field__input {
  padding: 10px 48px 6px 16px;
}

label.mdc-text-field--fullwidth-with-leading-icon:not(.mdc-text-field--textarea) > input.mdc-text-field__input {
  padding: 10px 16px 6px 0px !important;
}

label.mdc-text-field--fullwidth:not(.mdc-text-field--textarea) > span.mdc-floating-label{
  display:inline;
}
```
