### ISSUE TITLE
MatNavMenu Href

### ISSUE THREAD

**Issue by kristof12345** [SamProf/MatBlazor#537]
Hi!

I have a nav menu like this:
```
<MatNavItem Href="/"><MatIcon Icon="home" />Home</MatNavItem>
<MatNavItem Href="/weather"><MatIcon Icon="wb_sunny" />Weather</MatNavItem>
```
If I navigate to baseUrl/weather both items are selected. I tried to use "Multi="false"" but it didn't work. Is there a solution for this?

<img width="376" alt="Képernyőfotó 2020-05-10 - 11 12 20" src="https://user-images.githubusercontent.com/43353335/81495244-40a97180-92af-11ea-96cc-25a7f21053bb.png">

Thanks.

**Comment by enkodellc** [comment]
You will need to set the NavLinkMatch property. I will see why that is not documented.

```
        <MatNavItem Href="@navigationManager.ToAbsoluteUri(" ").AbsoluteUri" NavLinkMatch="NavLinkMatch.All">
            <MatIcon>home</MatIcon> <span class="miniHover">Home page</span>
        </MatNavItem>
```

Here is a real world example:  https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.CommonUI/Shared/Components/NavMenu.razor

**Comment by enkodellc** [comment]
Sorry for closing... please test and close if this works for you.

**Comment by kristof12345** [comment]
It works. Thanks.
