### ISSUE TITLE
MatTable Alignments and Widths

### ISSUE THREAD

**Issue by adrianex03** [SamProf/MatBlazor#543]
Hello, I've been looking for some components for Blazor and I found yours a very complete ones and open source is an A++. I'm looking to have a very nice table design. When the data shows on table it aligns to the left instead of fitting to the screen middle. Also it let a lot of space in the last column instead of distribute the space. I don't know if there's a way to make it done on `MatTable` or if it's a new feature on `MatDataTable`. Also, where can I find documentation about `MatDataTable`?

Thanks!

**Comment by enkodellc** [comment]
Hi @adrianex03 MatDataTable is not released yet so not documentation. For MatTable I recommend putting in a div / span in your <td> and then add a class for alignment / size to customize it as you need.

You can see how I did it in BlazorBoilerplate:
https://blazorboilerplate.com/todo_list
https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.CommonUI/Pages/TodoList.razor

I am going to close this issue and can re-open when MatDataTable is released.

**Comment by adrianex03** [comment]
> Hi @adrianex03 MatDataTable is not released yet so not documentation. For MatTable I recommend putting in a div / span in your and then add a class for alignment / size to customize it as you need.
> 
> You can see how I did it in BlazorBoilerplate:
> https://blazorboilerplate.com/todo_list
> https://github.com/enkodellc/blazorboilerplate/blob/master/src/BlazorBoilerplate.CommonUI/Pages/TodoList.razor
> 
> I am going to close this issue and can re-open when MatDataTable is released.

Thanks.
