### ISSUE TITLE
Can't select item in MatAutocompleteList

### ISSUE THREAD

**Issue by sandrohanea** [SamProf/MatBlazor#545]
**Steps to reproduce:**
1. Navigate to https://www.matblazor.com/AutocompleteList
2. Select option 'One' in the first example.
3. Delete the value from the autocomplete-list
4. Reselect option 'One'.

**Expected behavior:**
Option One will be selected.

**Actual behavior:**
The popup is closed, the selected value is still 'One' but the text is empty.

**Cause:**
When the text value from MatAutocompleteList changes, if some value is selected then this value is not reset to default and when reselecting an option, the value is not changed so the text is not updated.

**Note:**
Because the value is not updated, some other issues can appear as the Value is not synched with the text input.

**Comment by enkodellc** [comment]
@sandrohanea Thanks for such a great Issue and Fix. Was able to replicate and the fix worked great.

**Comment by sandrohanea** [comment]
Thanks, @enkodellc !
I'll close this issue.
