### ISSUE TITLE
Text Button rendering issue

### ISSUE THREAD

**Issue by vignatov** [SamProf/MatBlazor#55]
Text Button is rendered incorrectly in Safari.

<img width="175" alt="Screenshot 2019-04-10 at 10 47 24" src="https://user-images.githubusercontent.com/17622017/55869425-5f09de80-5b7e-11e9-8740-86049ee6ca4f.png">

I think mdc-button has 2 line-height styles on of which is incorrect.

**Comment by SamProf** [comment]
Thank you!

I don't have now access to Apple computer to see what happens. I think in neares feature we will check this.

**Comment by sandrohanea** [comment]
Hi!
I'll look into it :)

**Comment by exocom** [comment]
I'm not able to reproduce. The text is correct for me on OSX and iOS. Please share more details if you are still experiencing.

OSX:
Mojave 10.14.4
Safari 12.1

![Screen Shot 2019-04-16 at 11 57 16 PM](https://user-images.githubusercontent.com/2851652/56267464-be4a8000-60a3-11e9-8da9-9d911273282e.png)


iPad
iOS 12.1.4

![image](https://user-images.githubusercontent.com/2851652/56267600-27ca8e80-60a4-11e9-8504-1237e34118ec.png)

**Comment by lindespang** [comment]
Thanks for using MatBlazor. I cant reproduce either. Please reopen if this is still an issue for you.
