### ISSUE TITLE
MatBlazor Initial Page can be incorrectly set to 0 when navigating

### ISSUE THREAD

**Issue by CSOleson** [SamProf/MatBlazor#559]
**Describe the bug**
On the MatBlazor Table, if you go to the last page of the table by clicking the > button, and then press the |< button, the table page number will then display 0 instead of 1. If you click the > button again, it will then add 1 page to the table view but will be the same data (page 0 = page 1). I've replicated this in multiple Blazor Server Apps using the MatBlazor UI

**To Reproduce**
Reproduction Steps:
1. Launch https://www.matblazor.com/Table
2. Find a table with multiple pages
3. Scroll to bottom of table and click " >| " to reach the last page of results.
4. Click " |< " button to return to the first page.

**Blazorfiddle link**
This is replicable on the matblazor website here: https://www.matblazor.com/Table

**Expected behavior**
The table should return to page 1, not 0

**Screenshots**
![5-23-2020 2-58-08 PM](https://user-images.githubusercontent.com/35151114/82739545-f5a74980-9d05-11ea-8d36-59c0e379816d.png)

**Comment by lindespang** [comment]
Thanks for report, I'll take a look
