### ISSUE TITLE
MatSelectItem stopped displaying value

### ISSUE THREAD

**Issue by americanslon** [SamProf/MatBlazor#560]
**Describe the bug**
Value doesn't seem to be displayed in `MatSelectItem` though the value itself gets set.

**To Reproduce**
Second example from here https://www.matblazor.com/SelectItem doesn't display the value in my application. 

**Blazorfiddle link**
https://blazorfiddle.com/temp/4e50e2e3-83b7-415a-86da-fd5e5025a5bc
Clearly it works in the fiddle but this is the exact code I used to confirm that it's possibly not me doing something wrong. Have blazorfiddle beenupdated to the latest matblazor (and blazor/wasm)

**Expected behavior**
Value is displayed

**Comment by CSOleson** [comment]
This value is being displayed in the BlazorFiddle you provided when you select it:
![5-24-2020 1-16-18 AM](https://user-images.githubusercontent.com/35151114/82747176-3cc02980-9d5c-11ea-82d1-7fadbd65a332.png)
This appears to be working as intended?

**Comment by FelixDamrau** [comment]
I tested the SelectItem examples (the second one of the examples you mentioned and the one from the linked blazor fiddle) locally with MatBlazor 2.6.0 and both work as intended on my system.

**Comment by americanslon** [comment]
@FelixDamrau Are you using the release version of WASM form few days ago?

@CSOleson That's the fiddle from project's site. My point is that exact code doesn't work for me. Also the environment of blazorfiddle is not clear - wasm/server, version, etc.

**Comment by mischa71lab** [comment]
I have the same issue. It doesnt show any items anymore. The dropdown is empty. We just updated to latest wasm v3.2.0. Funny thing is that when I start the app from visual studo on localhost it does work ok, but when i publish the files to my webhost and acces it from there it doesnt work anymore.

**Comment by mischa71lab** [comment]
A couple of times CTRL-F5 fixed this issue for me.....

**Comment by FelixDamrau** [comment]
@americanslon 
I am using dotnet core 3.1.300, that is the version that includes Blazor WASM 3.2.0 according the [Daniel Roth's devblog](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-now-available/).

**Comment by americanslon** [comment]
I fished it out...

In my mdc overrides I had 

`.mdc-select__anchor {
    display: block !important;
}`

I am not sure why at this point. Probably to offset some early matblazor idiosyncrasy. 
Anyway removing it made the value show up, so check your old CSS folks if this is happening to you.
