### ISSUE TITLE
Wrong MatTextField text positioning when using "FullWidth"

### ISSUE THREAD

**Issue by FelixDamrau** [SamProf/MatBlazor#562]
**Describe the bug**
The position of the text inside a `MatTextField` changed from 2.4.3 -> 2.6.0 when using `FullWidth="true"` 

**To Reproduce**
1. Use MatBlazor package 2.6.0
1. Create TextFields in MatBlazor with `FullWidth="true"` 
2. Run project

**Blazorfiddle link**
Since this is an issue the depends on the version, I am not sure if a blazorfiddle link is helpful - here is a link anyway.
* https://blazorfiddle.com/s/mxst4sw4

**Expected behavior**
I think the positioning in 2.4.3 is correct.

**Screenshots**
| 2.4.3 | 2.6.0 |
| ---| --- |
| ![image](https://user-images.githubusercontent.com/20964228/82752020-9d328380-9dbb-11ea-85c7-865e6e48f640.png)  | ![image](https://user-images.githubusercontent.com/20964228/82752067-e1258880-9dbb-11ea-928d-947a6950f587.png)  |

**Comment by CSOleson** [comment]
I've been able to reproduce this in one of my projects. The positioning is correct in 2.4.3, while 2.6.0 causes the same issue in my project.

**Comment by RonPeters** [comment]
The full width demo seems to be correct running v2.6.0: https://www.matblazor.com/TextField

When you moved to the latest MatBlazor, did you notice that the CSS has been separated from the JS? Now you have to include both:
<script src="_content/MatBlazor/dist/matBlazor.js"></script>
<link href="_content/MatBlazor/dist/matBlazor.css" rel="stylesheet" />

**Comment by FelixDamrau** [comment]
I did include `<script src="_content/MatBlazor/dist/matBlazor.js"></script>` in 2.6.

However, I think that was the way it was included in 2.4.3 as well.

**Comment by RonPeters** [comment]
@FelixDamrau It looks like my comment was truncated. In addition to the .js script, you also now have to include the css separately:
`<link href="_content/MatBlazor/dist/matBlazor.css" rel="stylesheet" />`

**Comment by FelixDamrau** [comment]
I did include both files, the js script and the css file.

I uploaded a (somewhat) minimal blazor project that shows the error.
See https://github.com/FelixDamrau/matblazor-textfield

**Repro steps**
* Run the linked project
* Enter sth in the text field -> wrong position

* clean the project directory (I used clean clean -xfd)
* change version of matblazor to 2.4.3 in csproj `ProjectReference`
* rerun
* Enter sth in the text field -> correct position

**Comment by RonPeters** [comment]
Thank you for the project file. It greatly helps for debugging.

If I comment out bootstrap.min.css and app.css, then the text field displays correctly. So there is obviously some conflicting CSS being loaded. Since the point of MatBlazor is to implement the Material Design guidelines, I think loading Bootstrap would be at odds with that goal. I would start with removing Bootstrap. I would also load your own CSS after the MatBlazor CSS in case you want to override any default styles.

**Comment by FelixDamrau** [comment]
Thank you for your reply and time. <3
**I can confirm. The text positioning is correct if I remove the bootstrap css.**

The MS Blazor template uses bootstrap by default. If matblazor is/remains incompatible with bootstrap -- which sounds quite reasonable -- the removal of the bootstrap.css should be in the documentation.

I used the grid layout of bootstrap. I guess I will use the [material design grid layout](https://github.com/material-components/material-components-web/tree/master/packages/mdc-layout-grid).

I will close this issue/bug, since it is not a bug.
