### ISSUE TITLE
Documentation for MatAccordion

### ISSUE THREAD

**Issue by SayusiAndo** [SamProf/MatBlazor#567]
**Describe the bug**
No doc for MatAccordion.

@lindespang Thanks for creating MatAccordion, and if it is possible, could you provide some example how to use it?

**Comment by lindespang** [comment]
I did not create it (however I might have the last edit on it). Is there nothing on www.matblazor.com demo website on it? Something specific you want to know?

**Comment by SayusiAndo** [comment]
Sorry, I saw your name in the commit history. No doc on the site, I want to create one. I spend a half an hour to figure out what does it work, but I failed. That is the reason I created this ticket. I need an example to start with.

**Comment by FelixDamrau** [comment]
The MatAccordion usses MatExpansionPanel. The MatExpansionPanel has a [documentation on the demo website](https://www.matblazor.com/ExpansionPanel).

Does this demo help you?

**Comment by SayusiAndo** [comment]
Uhh, thanks, yes. I didn't look around what we have.
I close this issue down. Sorry for being clumsy. :)
