### ISSUE TITLE
MatAutoComplete: CustomStringSelector is null error when tabbing out of input box

### ISSUE THREAD

**Issue by Gareth064** [SamProf/MatBlazor#577]
When you type a partial term and press tab it causes a NullReferenceException on CustomStringSelector attribute.

1. Type partial term
![image](https://user-images.githubusercontent.com/22307223/83074068-74371a80-a069-11ea-8f18-4ddf9ae3622f.png)

2. Press Tab on the keyboard

3. Error Occurs
![image](https://user-images.githubusercontent.com/22307223/83074331-dee85600-a069-11ea-91a4-8cfcf10a0cdb.png)

**Comment by sandrohanea** [comment]
Hi @Gareth064,
Yes, when you didn't select any item, the selected item will be the default(e.g. null) and the control will try to display check if the string of that value is matched.
As a workaround, you can use 
`i?.PositionAndTeam`
as a CustomStringSelector.

**Comment by DDaemonium** [comment]
I have same issue from 2.6.0 version.

**Comment by Gareth064** [comment]
> Hi @Gareth064,
> Yes, when you didn't select any item, the selected item will be the default(e.g. null) and the control will try to display check if the string of that value is matched.
> As a workaround, you can use
> `i?.PositionAndTeam`
> as a CustomStringSelector.

This worked a treat cheers.
