### ISSUE TITLE
Question: Custom validation

### ISSUE THREAD

**Issue by kristof12345** [SamProf/MatBlazor#579]
Hi!

I have a login form (2 textfields and a button). If the button is clicked I send the username and pw to the server for validation. What I'd like is to show the validation result in the login form eg. add a red outline and an error text to the textfields.
Is there a way to achive this? I did not find an IsValid (or similar) attribute on MatTextField.

Thanks.

**Comment by SeppPenner** [comment]
Maybe this can help you a bit?

```razor
<MatTextField Label="username" @bind-Value="@username" />
<ValidationMessage For="@(() => username)" />
```

What might help you as well, is something like this:

```razor
<EditForm OnValidSubmit="@this.SubmitLogin" Model="LoginState">
   @if (this.ValidatingLogin)
   {
      "Validating"
      <MatProgressBar Indeterminate="true"></MatProgressBar>
   }

   <DataAnnotationsValidator />
   <ValidationSummary />
   <MatStringField @bind-Value="this.LoginState.UserName" Label="UserName" Icon="person" IconTrailing="true"
   FullWidth="true" Required="true" Disabled="@this.ValidatingLogin" />
   <MatStringField @bind-Value="this.LoginState.Password" Label="Password" Icon="lock_outline" IconTrailing="true"
   FullWidth="true" Required="true" Type="password" Disabled="@this.ValidatingLogin" />
   <MatButton Type="submit" Raised="true" Disabled="@this.ValidatingLogin">Login</MatButton>
</EditForm>
```

`SubmitLogin` handles the call to the server.
`LoginState` is just a state variable with username and password that implements `IValidatableObject` and the method `public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)`.
`ValidatingLogin` is a variable indicating whether the server is currently validating the login or not.
