### ISSUE TITLE
async void for UI events

### ISSUE THREAD

**Issue by sblakemore** [SamProf/MatBlazor#585]
In Blazor all Unhandled Exceptions should be send to ILogger instances so they can be recorded. This is the only way to have any kind of global Exception handling at all.

https://github.com/dotnet/aspnetcore/issues/13452#issuecomment-594088975

async void methods for UI events prevents Exceptions being sent to ILogger instances.

https://github.com/SamProf/MatBlazor/blob/master/src/MatBlazor/Components/MatButton/BaseMatButton.cs#L189

Currently an Exception on a MatButton click event brings down the process and the Exception never reaches the ILoggers. This should be changed to async Task instead of async void and the problem is solved.

It's easy to reproduce this with even a regular HTML <button /> by throwing an Exception in the click event and observing the output in the console. If the click handler is async void the process is killed, if the click handler is async Task the Exception is caught and logged with the default WebAssemblyConsoleLogger.

**Comment by Christian-Oleson** [comment]
Opened a PR for this issue @sblakemore :
https://github.com/SamProf/MatBlazor/pull/808

**Comment by SamProf** [comment]
fixed by @Christian-Oleson
