### ISSUE TITLE
BlazoGridView Code Sharing

### ISSUE THREAD

**Issue by arivera12** [SamProf/MatBlazor#59]
Hi @enkodellc I saw your reply. I have been very busy with not too much time. I will share my BlazorGridView component code. Its still lack of missing some features like clicking on header and sort the table but the paging is fully functional server/client side. Let me know if you need some help to get in it to work. I left the code in txt file cause the gridview is pretty long and the BlazorMessageAlert is being used internally. You can remove the blazor message alert component it is in really needed at all, I did't for personal purpose and for the gridview to be self managed by itself. I have other components handcfrated like autocomplete, input, checkbox, listview if you are interest to see them let me know to prepare another project with all the samples running so you can adapt it to you framework more easily. Cheers!
PS: I saw you already have most of them. haha
[BlazorMessageAlert.txt](https://github.com/BlazorComponents/MatBlazor/files/3071193/BlazorMessageAlert.txt)
[BlazorGridView.txt](https://github.com/BlazorComponents/MatBlazor/files/3071194/BlazorGridView.txt)

**Comment by enkodellc** [comment]
@arivera12 Thanks for the code. I will review and submit a PR, and have the owner give you some credit.  @SamProf  has a some ideas on how he wants to run the repo and he is open to suggestions and feedback.  So if you don't have time to do PR's we will definitely be open to feedback on Gitter: https://gitter.im/BlazorComponents/MatBlazor

**Comment by SamProf** [comment]
i will check this code.

**Comment by SamProf** [comment]
It's look like it;s Twitter Bootstrap and not material?

**Comment by arivera12** [comment]
It's both bootstrap and material. For reference this is the templates I used [daemonite.github.io](http://daemonite.github.io/material/)
