### ISSUE TITLE
apply MatTheme to MatToaster if Type == MatToastType.Primary or Type == MatToastType.Secondary

### ISSUE THREAD

**Issue by jan-ai** [SamProf/MatBlazor#604]
**Describe the bug**
If a `MatToaster` is created with Type `MatToastType.Primary` or `MatToastType.Secondary` the color of the text is always white.

**To Reproduce**
Let me know if more information is needed.

**Expected behavior**
The text color of the current `MatTheme` (either `OnPrimary` or `OnSecondary`) should be used.

**Comment by lindespang** [comment]
@jan-ai Hi I've submitted a PR for this #612 , thanks for letting us know!
