### ISSUE TITLE
Enhancement: Validation styles for outlined fields

### ISSUE THREAD

**Issue by kristof12345** [SamProf/MatBlazor#619]
Hi!

The current validation looks like this:

<img width="775" alt="Képernyőfotó 2020-06-22 - 11 46 00" src="https://user-images.githubusercontent.com/43353335/85273783-5a2d0400-b47e-11ea-98ff-f8839a1c5c20.png">

Setting the border color instead would look much better:

<img width="784" alt="Képernyőfotó 2020-06-22 - 11 48 45" src="https://user-images.githubusercontent.com/43353335/85273831-6add7a00-b47e-11ea-91ae-2c07224f6677.png">

I hope this will be included in a future release. Thanks.

**Comment by kristof12345** [comment]
The following styles solve the problem:

```
.mdc-text-field__input.invalid {
    border-bottom: none !important;
}

.invalid + .mdc-notched-outline > .mdc-notched-outline__leading, .invalid + .mdc-notched-outline > .mdc-notched-outline__notch, .invalid + .mdc-notched-outline > .mdc-notched-outline__trailing {
    border-color: red !important;
}
```

**Comment by enkodellc** [comment]
@kristof12345  thanks for finding a solution. Do you want to submit a PR on develop for this fix?

**Comment by kristof12345** [comment]
@enkodellc Ok. I tried to create a new branch, but I’m not allowed to push it. (This would be my first contribution to a public repo, so I might be doing something wrong. )

Another question: what do you use to compress the css to a single line?

**Comment by enkodellc** [comment]
@kristof12345 you do not have rights to create a new branch or push. You will need to Fork the repo on your account. Then submit a PR using your Fork, don't forget to change the branch to develop.

Once you submit a PR I can revew and merge it into Develop. I don't have rights to merge to master.  

This will help:  https://opensource.com/article/19/7/create-pull-request-github

I know it is not super straight forward but it is a skill you will use in the future as you contribute more and it is an asset in your developer arsenal :)

**Comment by enkodellc** [comment]
Fix is in Develop Branch.
