### ISSUE TITLE
MatSlider ValueChanged does not fire

### ISSUE THREAD

**Issue by yocabanes** [SamProf/MatBlazor#62]
Hello there, 

Thanks for all great razor components.

I'm using the MatSlider component, but the ValueChanged event does not fire, and examples in the doc don't show anything about it. Please, could anybody help me on this? Also, the Step property does not make any change on the slider.

Thanks in advance.

**Comment by SamProf** [comment]
Here down is example of MatSlider event https://www.matblazor.com/Slider  and it works

```
      <MatSlider bind-Value="@Val3" Discrete="true"></MatSlider>
 
        @functions
        {
 
            public decimal Val3
            {
                get => _val3;
                set
                {
                    _val3 = value;
                    this.StateHasChanged();
                }
            }
 
            private decimal _val3 = 0;
        }
```

**Comment by SamProf** [comment]
@yocabanes, Your problem is solved?

**Comment by yocabanes** [comment]
Yes, it was, thanks a lot.
