### ISSUE TITLE
Matblazor css file "breaks" other components

### ISSUE THREAD

**Issue by tlynn1985** [SamProf/MatBlazor#622]
The matblazor css file contains something that interfers with telerik and Radzen UI components, namely drop down list and date time pickers.

![image](https://user-images.githubusercontent.com/54050659/85289038-6a33ec00-b45c-11ea-9953-6d6051d1a29d.png)

![image](https://user-images.githubusercontent.com/54050659/85289113-88015100-b45c-11ea-8ffa-ba1c83c5b87e.png)

and when you scroll it gets worse.

When the drawer menu is open the alignment is off and if you scroll on the page to reach other controls/components the dropdown menu flys away and is unsynced to its relative position.

When i disable the matblazor.css file in _host everything is fine (minus the drawer and app menu of course but i need those for my application.

Please advice.

**Comment by enkodellc** [comment]
You might want to start by adding reviewing the material design css. Most likely it is something with Material Design that is causing the issue as 95% of the CSS / JS in MatBlazor is imported from MDC. From there you can track down what the conflict might be. Just my 2 cents.

https://github.com/SamProf/MatBlazor/wiki/How-to-Edit-the-css---scss-styles-for-MatBlazor
