### ISSUE TITLE
Feature/Question: MatSelect drop focus after selecting an item

### ISSUE THREAD

**Issue by kristof12345** [SamProf/MatBlazor#623]
Hi!

Is it possible to automatically drop focus from MatSelect after clicking an element from the dropdown? If not, this would be a useful feature.

Thanks.

**Comment by kristof12345** [comment]
This is a really annoying issue, because the validation is only updated after the focus is dropped. So currently users have to click somewhere else (after selecting an item) to see the updated validation styles

**Comment by lindespang** [comment]
Hi @kristof12345!

1. MDC components doesn't leave focus by default - therefor MatBlazor doesn't do it either (we have had a previous discussion about this if we were to make this a global setting)

2. Dropping focus on a HTML element is not supported in Blazor (as far as I know) and you have to use JS interop.

Example code below:

**Blazor**
```
<MatSelect Label="Pick a Food Group" TValue="string" @ref="matSelect" ValueChanged="@Blur">
    <MatOptionString Value="grains">Bread, Cereal, Rice, and Pasta</MatOptionString>
    <MatOptionString Value="vegetables">Vegetables</MatOptionString>
    <MatOptionString Value="fruit">Fruit</MatOptionString>
</MatSelect>


@code{
    public MatSelect<string> matSelect;
    public void Blur()
    {
        JSRuntime.InvokeVoidAsync("BlurActiveElement");
    }

}
```
**Javascript**
```
window.BlurActiveElement = () => {
    document.activeElement.blur();
}
```

**Comment by kristof12345** [comment]
Thanks @lindespang. It works for dropping the focus, but seems like something else caused the validation problem. I created a different issue for that: #628
