### ISSUE TITLE
Hoe use MatIconButton inside the MatTextField

### ISSUE THREAD

**Issue by novfal** [SamProf/MatBlazor#632]
We have use icon inside the text field how write onclick function for that icon.

**Comment by SigurdJanson** [comment]
You can hook into the `IconOnClick`callback as demonstrated in this [Blazor Fiddle](https://blazorfiddle.com/temp/5270c04b-6fb6-40b3-a416-1f2206712623):

Here is the code:
```
@page "/"
 
<MatTextField @bind-Value="@myStringValue" Label="Standard" IconOnClick="@TrailingIconClicked" Icon="clear" IconTrailing="true" />

@code
{
    string myStringValue = "Default string";

    protected void TrailingIconClicked()
    {
        myStringValue = "My Value";
    }
}
```
Hope this is what you're looking for...
