### ISSUE TITLE
MatTab @bind-ActiveIndex initialization doesn't bind to a number besides 0

### ISSUE THREAD

**Issue by PeteJobi** [SamProf/MatBlazor#633]
**Describe the bug**
MatTab's default tab is always set to the first one (zero) regardless of the value binded to ActiveIndex. This issue is also present in the TabIndex example from the MatBlazor docs.

**To Reproduce**
Create the below component and run
```
<MatButton` OnClick="@ChangeTab">Change Tab</MatButton>
<div>
    Active tab index: @tabIndex
</div>
<MatTabGroup @bind-ActiveIndex="@tabIndex">
    <MatTab Label="First">
        First Content
    </MatTab>
    <MatTab Label="Second">
        Second Content
    </MatTab>
    <MatTab Label="Third">
        Third Content
    </MatTab>
    <MatTab Label="Fourth">
        Fourth Content
    </MatTab>

</MatTabGroup>


@Code  {
    public int tabIndex = 2; //notice that this is set to 2. In the docs, it is set to zero
    //what I expect is the active tab on initialization to be the third one

    void ChangeTab(MouseEventArgs e)
    {
        tabIndex = tabIndex < 3 ? tabIndex + 1 : 0;
    }
}
```

**Expected behavior**
I expect the active tab to be set to the tabIndex on initialization

**Additional context**
I need this to work to be able to "remember" the user's last clicked tab.

**Comment by americanslon** [comment]
Try calling `StateHasChanged();`
I dynamically set active tab (though not through a button click) and it doesn't work without `StateHasChanged();`

**Comment by PeteJobi** [comment]
@americanslon Oh my God, thank you so much. It works. I completely forgot about the `StateHasChanged()` method.

**Comment by fellowshipdevs** [comment]
Where exactly do you need to put the StateHasChanged() method? I've tried putting it inside OnInitializedAsync, din't work.

**Comment by PeteJobi** [comment]
Call it in OnAfterRender().

**Comment by Ogglas** [comment]
Remember that `StateHasChanged()` causes the component to be rerendered.

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#state-changes-statehaschanged

If you want to change to another tab it will just loop on setting value `OnAfterRender`. You can use parameter `firstRender` to solve this though. 

https://docs.microsoft.com/en-us/aspnet/core/blazor/components/lifecycle?view=aspnetcore-6.0#after-component-render-onafterrenderasync

Example to change tab via optional URL parameter:

```
@page "/product/{Id:int}/{TabId:int?}"

<MatTabGroup @bind-ActiveIndex="@tabIndex">

</MatTabGroup>

@code {
    [Parameter]
    public int Id { get; set; }

    [Parameter]
    public int? TabId { get; set; }

    private int tabIndex = 0;

    protected override void OnAfterRender(bool firstRender)
    {
        if (firstRender)
        {
            if (TabId == null)
            {
                TabId = tabIndex;
            }
            tabIndex = TabId.Value;
            this.StateHasChanged();
        }
    }
}
```
