### ISSUE TITLE
Textfield inside EditForm and MatDialog shows the underline and text in the wrong place

### ISSUE THREAD

**Issue by SeppPenner** [SamProf/MatBlazor#635]
**Describe the bug**
The Textfield shows the underline and the text in the wrong place. (See screenshot).

**To Reproduce**
Add the code from the fiddle to a project and check whether it fails and shows the same behaviour as the screenshot below.

**Blazorfiddle link**
I tried to put the code into a fiddle, but it doesn't get rendered in there properly: https://blazorfiddle.com/s/tr7bd2fv.

**Expected behavior**
The underline and the text should be centered into the field, not shown below.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/9639361/86101656-dd6fda80-baba-11ea-8695-d7e8021f28f8.png)

**Additional context**
MatBlazor 2.6.0.

**Comment by kristof12345** [comment]
Any update on this?

**Comment by SeppPenner** [comment]
Not from me... I didn't have the time to check this and provide a pull request.

**Comment by Christian-Oleson** [comment]
@kristof12345 @SeppPenner ,
If either of you wanted to open a PR for the project, that would be appreciated!

**Comment by SeppPenner** [comment]
I will see what I can do here :)

**Comment by SeppPenner** [comment]
Does this problem still occur for you, @kristof12345?

I wasn't able to reproduce it on the latest version anymore (I just used the mat blazor project's `MatBlazor.Demo.ServerApp` to test...

![grafik](https://user-images.githubusercontent.com/9639361/103481796-5a1ea100-4ddd-11eb-902c-02dec23798e3.png)

**Comment by CSOleson** [comment]
Can you close this issue then @SeppPenner

**Comment by SeppPenner** [comment]
Sure, for me it's solved :)
