### ISSUE TITLE
DataAnnotationsValidator renders Box in MatTextField

### ISSUE THREAD

**Issue by minimalisticMe** [SamProf/MatBlazor#645]
Hi,

I'm doing my first steps in Blazor and MatBlazor.
I have a question regarding validation.
Whenever a validation fails, I am displayed a red bounding box instead of just a red underline.

My razor page:
```
@page "/login"
@using ClientB.Models

<h1>Login</h1>

<EditForm Model="login">
    <DataAnnotationsValidator />

    <p>
        <MatBlazor.MatTextField @bind-Value="@login.Mail" Label="Mail-Address" Icon="mail_outline" Dense="true"></MatBlazor.MatTextField>
        <ValidationMessage For="@(() => login.Mail)" />
    </p>
    <p>
        <MatBlazor.MatTextField @bind-Value="@login.Password" Label="Password" Icon="lock_outline" Type="password"></MatBlazor.MatTextField>
        <ValidationMessage For="@(() => login.Password)" />
    </p>
    <p>
        <MatBlazor.MatButton OnClick="@LoginClick" Label="Login"></MatBlazor.MatButton>
    </p>
</EditForm>

@code {
    private LoginModel login = new LoginModel();

    public void LoginClick(MouseEventArgs e)
    {

    }
}
```

However a failed validation attempt renders a red bounding box instead of just a read underline, like in the example here: https://samprof.github.io/MatBlazor/EditContext
Expected (like in the example):
![grafik](https://user-images.githubusercontent.com/13404680/87243757-d2149b80-c438-11ea-9ded-6294c54600c8.png)

Actual:
![grafik](https://user-images.githubusercontent.com/13404680/87243786-038d6700-c439-11ea-8ec9-70c68befa9f3.png)

How can I get rid of that red bounding box during a validation error and show it like in the example?

**Comment by thedigitaltailor** [comment]
I had the same problem. 

The default site.css rolled out with the template has the line:
`.valid.modified:not([type=checkbox]) {
    outline: 1px solid #26b050;
}`

This is what caused it. I commented it out and it fixed the issue.
Hope this helps.

**Comment by minimalisticMe** [comment]
I removed the part with

```
.invalid {
outline: 1px solid red;
}
```
from file `\wwwroot\css\app.css`

and now everthing looks like expected.
Thank you very much @thedigitaltailor !!
