### ISSUE TITLE
MatButton don't show in MatAppBar

### ISSUE THREAD

**Issue by srxqds** [SamProf/MatBlazor#647]
**Describe the bug**

**To Reproduce**

my blazor code in
```html
<MatAppBar Fixed="true">
    <MatAppBarRow>
        <MatAppBarSection Align="@MatAppBarSectionAlign.Start">
            <MatIconButton Icon="menu" Link="/"></MatIconButton>
            <MatButton Link="/console" >1</MatButton>
            <MatButton Link="/console" Label="模块">2</MatButton>
            <MatButton Link="/console" Label="设备">3</MatButton>
            <MatButton Link="/console" Label="项目">4</MatButton>
        </MatAppBarSection>
        <MatAppBarSection Align="@MatAppBarSectionAlign.End">
            <MatIconButton Icon="favorite"></MatIconButton>
        </MatAppBarSection>
    </MatAppBarRow>
</MatAppBar>
```

**Blazorfiddle link**
Please provide a mock implementation of your code on www.blazorfiddle.com. This makes it a lot easier for us and you can get faster feedback on your issue. 😉
Hit save and post the URL under this header.

https://blazorfiddle.com/s/8ykp2gvn

**Expected behavior**

**Screenshots**
If applicable, add screenshots or .GIF captures to help explain your problem.
![image](https://user-images.githubusercontent.com/5187024/87543489-6f8cfb00-c6d7-11ea-9c09-164455a15b13.png)

**Additional context**

**Comment by srxqds** [comment]
thank you

**Comment by stefanloerwald** [comment]
For people running into the same issue: The problem is that the font color for buttons is the same as the background color of the app bar. By setting a custom color, or using a raised or unelevated button, the buttom becomes visible.
