### ISSUE TITLE
Overlap of UI elements in MatTextField

### ISSUE THREAD

**Issue by stefanloerwald** [SamProf/MatBlazor#659]
**Describe the bug**

For a `<MatBlazor.MatTextField TValue="string" Placeholder="placeholder" Label="label" FullWidth="true" />`, the UI elements label and placeholder overlap. This does not occur for `FullWidth="false"`.

**To Reproduce**
See above.

**Blazorfiddle link**
https://blazorfiddle.com/s/wskutlab

**Expected behavior**

Either the placeholder needs to be invisible when the element is not focused, or the label needs to be small already.

**Screenshots**
![image](https://user-images.githubusercontent.com/10850250/88792044-f1caf400-d19a-11ea-9753-c3395b044ee2.png)

**Comment by erlendp** [comment]
![image](https://user-images.githubusercontent.com/34012855/89607967-e7f66e80-d8c7-11ea-8cdb-dff63e3e69a5.png)
Note that this still happens when `FullWidth="false"` if you first enter some text, then delete the text and hit enter.

**Comment by Christian-Oleson** [comment]
@stefanloerwald ,
The above PR has been merged. Can we close this out?

**Comment by stefanloerwald** [comment]
Hi @Christian-Oleson,

I currently can't spend time on verifying this as I'm fairly busy with other work. Let's close this issue for now (same as the others where you've notified me). We can always re-open them, should there be any remaining issue.

Thanks
Stefan
