### ISSUE TITLE
Provide FullWidth on MatSelect

### ISSUE THREAD

**Issue by stefanloerwald** [SamProf/MatBlazor#660]
**Describe the feature request**

There is currently no `FullWidth` parameter on MatSelect. It would be nice if one could make elements full width, just as, e.g. a`MatTextField`.

**Expected behavior**
Same behavior as MatTextField: Apply `width: 100%` as an element style.

(Sadly, writing `<MatSelect Style="width: 100%" ...>` does not suffice)

**Comment by stefanloerwald** [comment]
I've tried adding this with MDC (as according to the docs, fullwidth is supported on mdc-select), but no luck: https://github.com/material-components/material-components-web/issues/6324

**Comment by stefanloerwald** [comment]
I've managed to implement this using `width: 100%` on both the main div, and the menu div. The css class `mdc-select--fullwidth` isn't available anymore, so this is the only way to do it. For the menu, there's theoretically `mdc-menu-surface--fullwidth`, but it's only a `width: 100%` anyway, so rather useless to pollute the MatBlazor css with that. PR: #670.

**Comment by alharthyw** [comment]
> I've managed to implement this using `width: 100%` on both the main div, and the menu div. The css class `mdc-select--fullwidth` isn't available anymore, so this is the only way to do it. For the menu, there's theoretically `mdc-menu-surface--fullwidth`, but it's only a `width: 100%` anyway, so rather useless to pollute the MatBlazor css with that. PR: #670.

Hi Stefan,
Have you heard back yet? The width is fixed even when shrinking the page. Using MatSelect in a Grid Layout is disastrous!
I've tried the latest development version 2.7.0 but it's still not reacting to width:100%

**Comment by Christian-Oleson** [comment]
@stefanloerwald ,
The above PR has been merged. Can we close this out?
