### ISSUE TITLE
Update Value for MatSlider from code doesn't work

### ISSUE THREAD

**Issue by stefanloerwald** [SamProf/MatBlazor#661]
**Describe the bug**

This is probably a similar issue to https://github.com/SamProf/MatBlazor/issues/658: Changing the value of a MatSlider from code doesn't update the slider.

**To Reproduce**
```
<MatBlazor.MatSlider @bind-Value="Value" ValueMin="0" ValueMax="100"></MatBlazor.MatSlider>
@Value

<MatBlazor.MatButton OnClick="() => Value = 20">Set to 20</MatBlazor.MatButton>
<MatBlazor.MatButton OnClick="() => Value = 80">Set to 80</MatBlazor.MatButton>

@code
{
    public double Value { get; set; }
}

```

**Blazorfiddle link**
https://blazorfiddle.com/s/z7dwpg27

**Comment by Christian-Oleson** [comment]
@stefanloerwald ,
The above PR has been merged. Can you close this out if it is no longer an issue?
