### ISSUE TITLE
Icons are scattering when I reload the page.

### ISSUE THREAD

**Issue by Thirdyyyyyyy** [SamProf/MatBlazor#675]
![Untitled](https://user-images.githubusercontent.com/67768594/89625590-f3588400-d84c-11ea-8bae-250355ec8882.jpg)
**Describe the bug**
Everytime I reload the page the icons and labels of the items in the NavMenu scatters at the TopMenu

**Comment by lindespang** [comment]
@Thirdyyyyyyy Update this issue with the required information in the tempplate or this will be closed. This isn't anywhere close to enough information of the problem.

**Comment by Thirdyyyyyyy** [comment]
![Untitled](https://user-images.githubusercontent.com/67768594/89758563-f944a400-da9c-11ea-935d-d151a892d9ff.jpg)
