### ISSUE TITLE
MatAutocompleteList with Async Data / Large Data Sets

### ISSUE THREAD

**Issue by groogiam** [SamProf/MatBlazor#687]
**Describe the question**
The MatAutocompleteList component does not seem to support async data loads from the server very effectively. It seems like you use OnTextChanged to initiate a call to the server and replace the items collection but this gets very clunky when the server performs a complex search over multiple fields and returns a complex object. The returned objects gets filtered again based on an arbitrary string selector which is really not necessary for data filtered on the server. It seems like there should be away to disable the inbuilt filtering and just use the results returned directly from the server. Is there any way to do this with the current control and if not are there plans to include more functionality around server filtering and potentially a virtual scroll for this component? I think these would really make this component much more usable for filtering larger datasets.

**Comment by sandrohanea** [comment]
Hi,
Indeed, the current MatAutocompleteList wasn't designed to work with async data / large data sets but the MatAutocomplete component should be:
please, take a look at https://github.com/SamProf/MatBlazor/pull/550

Thanks

**Comment by groogiam** [comment]
Thanks.
