### ISSUE TITLE
Textfield Label white backgroud

### ISSUE THREAD

**Issue by vudzero** [SamProf/MatBlazor#694]
**Describe the bug**
The TextField label background is set to white

**To Reproduce**
1. Use a Textfield on a color background

**Blazorfiddle link**
N/A

**Expected behavior**
The TextField label background to be transparent

**Screenshots**
If applicable, add screenshots or .GIF captures to help explain your problem.
![image](https://user-images.githubusercontent.com/2973549/90992557-9e23ae80-e57e-11ea-96ff-17e08e60228e.png)

**Additional context**
Version 2.7.0-develop-017

**Comment by enkodellc** [comment]
@vudzero If you inspect the mdc-floating-label css you can see that it uses the 
--mdc-theme-surface for the background color and if not set the defaults to white. So maybe it should default to transparent.  

https://github.com/SamProf/MatBlazor/blob/2a7931c4004471cba74b38de4e4aadf94075c93f/src/MatBlazor.Web/src/matTextField/matTextField.scss#L37

.mat-floating-label--float-above-outlined {
    background-color: var(--mdc-theme-surface, #fff) !important;
}

**Comment by Christian-Oleson** [comment]
@vudzero @enkodellc ,
If this issue is resolved with the above PR, can we close it?

**Comment by vudzero** [comment]
All good!
