### ISSUE TITLE
Checkbox Label Incorrect Position

### ISSUE THREAD

**Issue by quajak** [SamProf/MatBlazor#695]
**Describe the bug**
When giving a standard checkbox a label, the label has a wrong vertically position and is not aligned with the checkbox.

**To Reproduce**
Open https://blazorfiddle.com/s/hnmvt5sy or simply create a checkbox with TValue=bool (`<MatCheckbox Label="Checkbox" TValue="bool"></MatCheckbox>`)

**Screenshots**
![image](https://user-images.githubusercontent.com/8559822/91023348-bafbc880-e5f6-11ea-8bc7-9b7b1458faba.png)

**Comment by CSOleson** [comment]
You have a link to the bootstrap style sheet in the blazorfiddle. Bootstrap and Material cannot be mixed and cause issues since they are opposing designs. Remove bootstrap and change the css to be correct and this should go away.

**Comment by quajak** [comment]
Thanks!
