### ISSUE TITLE
MatTable OData support

### ISSUE THREAD

**Issue by prajaybasu** [SamProf/MatBlazor#70]
MatTable with OData (or any API support) should be a part of a separate library.

OData API offers support for filtering, paging, etc. naturally with minimal effort in .NET Core, so if you are planning to add filtering/paging support to MatTable you should consider making a component with native support for OData, it is a perfect choice for SPAs where filtering/paging should be offloaded to the server.

It is [really simple to add OData to an existing API](https://www.youtube.com/watch?v=ZCDWUBOJ5FU).

**Comment by Christian-Oleson** [comment]
@prajaybasu @SamProf ,
Is this one still an issue?
