### ISSUE TITLE
Circular progress indicator

### ISSUE THREAD

**Issue by stefanloerwald** [SamProf/MatBlazor#705]
There is a linear progress indicator (aka ProgressBar, https://www.matblazor.com/ProgressBar), but not a circular one. See https://material.io/develop/web/components/circular-progress Would be great if there could be a component to do that (same API as ProgressBar, I'd guess).

**Comment by Christian-Oleson** [comment]
@stefanloerwald ,
This has been merged and released. Can we close out the issue?
