### ISSUE TITLE
MatButton OnClick UIMouseEventArgs passing CommandParameter

### ISSUE THREAD

**Issue by valentasm1** [SamProf/MatBlazor#71]
Hi,

I am not sure how archive this results. I have a list with buttons. After button click i would like to remove that button from list, show SnackBar and then redirect to other page. I think it would be nice that attach command parameter to UIMouseEventArgs (or new type args). After that it would be easy to take button id and remove it from list.
Maybe i am doing it all wrong?

**Comment by SamProf** [comment]
Maybe this way you need?

https://blazorfiddle.com/s/nmfaykb9

**Comment by valentasm1** [comment]
Exactly. Overlooked. Thank you.
