### ISSUE TITLE
Toaster add extension not working properly

### ISSUE THREAD

**Issue by Luk164** [SamProf/MatBlazor#710]
**Describe the bug**
`Toaster.Add("string")` extension function is not working. IDE states this: `"The type 'MatBlazor.IMatToaster' must be convertible to 'MatBlazor.BaseMapper' in order to use it as parameter 'T' in the generic method 'T MatBlazor.BaseMapperExtensions.Add<T>(this T, string)'"`

**To Reproduce**
1. Create a new project (server side)
2. Add MatBlazor and prepare the Toaster
3. Try to use the example way to show toast
4. See the error

**Expected behavior**
Toaster.Add("whatever"); will not show any errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/30559213/92690291-03c6b780-f341-11ea-9a03-d3b3a7a0a533.png)

**Comment by BlowaXD** [comment]
Did you try adding a MatToastType after the message parameter ? as your IDE shows, this parameter does not seem to be optional.
![image](https://user-images.githubusercontent.com/16936368/92911951-a35f7500-f429-11ea-8d5e-51831f1331ba.png)

**Comment by Christian-Oleson** [comment]
Maybe I am missing something, but to me this just looks like you're calling the method to add toast with an incorrect method signature.

**Comment by Luk164** [comment]
> Maybe I am missing something, but to me this just looks like you're calling the method to add toast with an incorrect method signature.

Yeah, found that out later. The problem is https://www.matblazor.com/Toast - the documentation shows that only a single string is required for one of the overloads.

**Comment by Christian-Oleson** [comment]
@Luk164 ,
Would you like to open the PR to fix the documentation, or shall I?

**Comment by Luk164** [comment]
> @Luk164 ,
> Would you like to open the PR to fix the documentation, or shall I?

Feel free to do so, I am playing with JAVA rmi rn

**Comment by Christian-Oleson** [comment]
@Luk164 ,
Added a PR for this
