### ISSUE TITLE
Datepicker

### ISSUE THREAD

**Issue by rynsantos** [SamProf/MatBlazor#72]
Datepicker component would be a great addition to list. :)

**Comment by SamProf** [comment]
Yes, in plans

Thank you.

**Comment by valentasm1** [comment]
As for some kind alternative it is possible to use [BlazorNodaTimeDateTimePicker](https://github.com/nheath99/BlazorNodaTimeDateTimePicker)

**Comment by SamProf** [comment]
I think i will get some ideas from https://github.com/FreddyFY/material-datepicker

**Comment by SamProf** [comment]
@rynsantos Hey! I am working on DatePicker now.
It;s not completed yet, in progress

https://www.matblazor.com/DatePicker

**Comment by redbaty** [comment]
Hey, @SamProf nice work! A label would be a great idea too 😉
