### ISSUE TITLE
TrailingIconClick doesn't work on MatChip

### ISSUE THREAD

**Issue by TuRz4m** [SamProf/MatBlazor#724]
**Describe the bug**
The event TrailingIconClick  on MatChip is never fired.

**To Reproduce**
1. Add a MatChip with a TrailingIcon and an event TrailingIconClick.
2. Click on the trailing icon
3. Nothing happens

**Blazorfiddle link**
https://blazorfiddle.com/s/0fnvij3v

**Expected behavior**
Event is fired.

**Comment by Geert-Navara** [comment]
I also encountered this issue, for now I just used the @onlick event as a temporary workaround

**Comment by kylepope-ge** [comment]
I suspect it might be due to this, but I haven't been able to try it out yet: https://github.com/material-components/material-components-web/issues/6136

**Comment by Christian-Oleson** [comment]
@TuRz4m @Geert-Navara ,
It looks like PR #750 fixes the issue reported. Can we please close this out?
