### ISSUE TITLE
Clearing MatSelectItem value

### ISSUE THREAD

**Issue by d1p3shn0mad** [SamProf/MatBlazor#743]
I have a MatSelectItem element with dynamic items. Every time the items source list is cleared, I would like to clear the selected value from the element.  
I can't find anything for this documentation. Is there anything that can be done to clear the selected value?

**Comment by Christian-Oleson** [comment]
@d1p3shn0mad ,

Can you mark this with the question label? I'm not certain but could take a look. Likewise, a PR is always appreciated if you find an issue!

**Comment by Christian-Oleson** [comment]
@d1p3shn0mad ,
I think this may be a bug that is blocking what you are trying to do:
https://github.com/SamProf/MatBlazor/issues/651

**Comment by d1p3shn0mad** [comment]
Shall I close this as duplicate to #651?

**Comment by Christian-Oleson** [comment]
Yes please. Once that is fixed, we should have clear info documented on how to do so. Or, really, just the fact that it should be capable of doing so, as it's just removing an item from a list

**Comment by d1p3shn0mad** [comment]
Duplicate of #651
