### ISSUE TITLE
Improving performance

### ISSUE THREAD

**Issue by jasiunaz** [SamProf/MatBlazor#758]
I would like to ask if there is a way to shorten load times and reduce network payload. 

Perhaps there is a way to customize and compile the source files individually, and to cut back on unused MatBlazor components, given the fact that the only components that I use are MatExpansionPanel, MatToast and MatChip. Seems like an overkill to load the whole package just for these 3 components. 

Or maybe it's just that resources are uncompressed? 

Any help would be appreciated.

**Comment by damianog** [comment]
@jasiunaz maybe we should wait for .NET 5 for some speed improvements, have a look at https://visualstudiomagazine.com/articles/2020/09/14/aspnet-5-rc1.aspx
