### ISSUE TITLE
Question about MatTextField and how to deal with numeric values

### ISSUE THREAD

**Issue by ctrl-alt-d** [SamProf/MatBlazor#76]
Hi Mr Vladimir,

first of all, congrats about your project and about your first 100 stars and thanks to share this clean code. My question is about `MatTextField`: 

**Intro** 

I know that, on `MatTextField`,  `type` is a [parm](https://github.com/SamProf/MatBlazor/blob/master/src/MatBlazor/Components/MatTextField/BaseMatTextField.cs#L99) on this control and it is easy to change default type value to other input type like `number`. However, the `value` parameter ( `bind` ) remains as type `string`. 

**Question**

How is `MatBlazor` designed to deal with numeric input? I mean, maybe, by design, it's better to have a kind of 'backup' string field for the numeric value (stored on a `int` or `Decimal` var ) and casting in both ways each time of numeric value should appear on UI or updated. Or, maybe, `MatNumericField` has not been written yet and will be written in the future. How to deal with numeric variables on a `MatBlazor` form?

**Related**

For ERP software will be interesting a kind `MatMoneyField` that would allow formatting values with decimal points, fix decimal places and thousands separators. Maybe it is related with the question and the right way is, another time, to use strings, as backup field, to improve UX. Would be wonderful to know your opinion.

Thanks, dani herrera.

**Comment by SamProf** [comment]
Hey!

Thank you for your support!
I think that it would be good make separate controls for different types of values. 
For Text - TextField
For Date - DateTimePicker
For Number - NumericField
For Money - I dont know... maybe it can be merged with Numeric.
And so on...
I think that it is good idea, what should be impelemented in feature.
