### ISSUE TITLE
Use MatBlazor inside Razor Component Library

### ISSUE THREAD

**Issue by xizzor77** [SamProf/MatBlazor#781]
First of all thanks for the **GREAT** Work!

Right now i plan to migrate some Angular Projects to Blazor. 

Because they share a lot of code and UI I would like to use a Razor Component Library for sharing the Company design Frontend. 

Right now it seems not possible to use the MatBlazor package inside a Component Library. Visual Studio complains about not finding the `<MatIconButton Icon="menu"></MatIconButton>` or any othe Component.

I followed theses steps [Razor Library](https://docs.microsoft.com/en-us/aspnet/core/blazor/components/class-libraries?view=aspnetcore-3.1&tabs=visual-studio ) to build a library. 

Am I missing something or is it just not possible?

Thanks in advance for any help you are able to provide.

**Comment by StefanSoderberg** [comment]
Seems to be something to do with the @using MatBlazor
this needs to be present, have you tried registering the using in the _Imports.razor file?
This should take effect all across you application, alternatively you need to set this using statement on every page where a MatBlazor component is used

**Comment by dorana** [comment]
Have you tried registering @using MatBlazor in the
_Imports.razor

This should asign it AppWide.
Else you will need to set the using in every component that uses MatBlazor

**Comment by xizzor77** [comment]
> Have you tried registering
> `@using MatBlazor`
> in the
> _Imports.razor
> 
> This should asign it AppWide.
> Else you will need to set the using in every component that uses MatBlazor
> 
> And I mean to do this in the Imports of your component library.
> 
> as for the projects using the Library you might need to set imports such as
> `@usingMyLibrary.MatBlazor`
> 
> Now these suggestions are 100% guesses as I have not done this myself


Hi @dorana,

tried both of your suggestions but nothing seems to work. I will try a newer Dotnet Version today.

**Comment by xizzor77** [comment]
With the following configuration in the .csproj file the import works as expected.


> Net Core SDK 3.1.401


```
<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <IsPackable>true</IsPackable>
    <LangVersion>8.0</LangVersion>
    <RazorLangVersion>3.0</RazorLangVersion>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="MatBlazor" Version="2.8.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.1.10" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="3.1.10" />
  </ItemGroup>

</Project>
```
