### ISSUE TITLE
MatAutocompleteList re-render list on items update

### ISSUE THREAD

**Issue by hailstorm75** [SamProf/MatBlazor#790]
**Describe the feature request**
The component doesn't update the autocompletion list when the bound list items are changed.
The bound list items change _asynchronously_ based on the entered text - the text is used to query a Db using Full-text search.

**Expected behavior**
A user should see the autocomplete list change based on what they write.

The autocomplete component should support reloading the completion list on the fly.

A user should be able to either select a hint from the autocomplete list to navigate to the item or press enter/click submit to view all search suggestions.

**Comment by jan-ai** [comment]
I stumbled over the same problem. Solved it with the following

In class `BaseMatAutocompleteList` in function `GetFilteredCollection` change 

```
            if (searchResult == null || searchResult.SearchText != searchText)
            {
                searchResult = new AutocompleteListSearchResult<TItem>()
                {
                    SearchText = searchText,
                    ListResult = Items.Select(x => new MatAutocompleteListItem<TItem>()

```
to

```
            if (searchResult == null || searchResult.SearchText != searchText || searchResult.Items != Items)
            {
                searchResult = new AutocompleteListSearchResult<TItem>()
                {
                    SearchText = searchText,
                    Items = Items,
                    ListResult = Items.Select(x => new MatAutocompleteListItem<TItem>()
```

and add

```
        public IEnumerable<TItem> Items { get; set; }
```

to class `AutocompleteListSearchResult`

**Comment by SamProf** [comment]
fixed
