### ISSUE TITLE
BaseMatButton

### ISSUE THREAD

**Issue by felixkjoseph** [SamProf/MatBlazor#792]
**Describe the bug**

Error	CS0246	The type or namespace name 'BaseMatButton' could not be found (are you missing a using directive or an assembly reference?)	

**To Reproduce**
After updating from 2.7.0 to 2.8.0

**Comment by damianog** [comment]
@felixkjoseph BaseMatButton doess not exist anymore due to #762

**Comment by Christian-Oleson** [comment]
@felixkjoseph ,
Since this is expected per #762, can we close this out?
