### ISSUE TITLE
Cleanup console logs

### ISSUE THREAD

**Issue by Codinkat** [SamProf/MatBlazor#799]
Version 2.8.0 writes "matdialog-log-setIsOpen" log in console each time a dialog is opened or closed. Please remove or provide a way to disable this logging.

Edit 2020-12-08: Noticed also "MatSelect.init" logs in console

**Comment by Christian-Oleson** [comment]
@dbpyxis ,
Thanks for the report. I've opened https://github.com/SamProf/MatBlazor/pull/804 for this

**Comment by enkodellc** [comment]
@Codinkat @Christian-Oleson  it looks like 804 was merged so can this be closed?

**Comment by Christian-Oleson** [comment]
Yes, I believe this can be closed @enkodellc
