### ISSUE TITLE
Using Href in MatBlazor components cause to navigate twice.

### ISSUE THREAD

**Issue by ngothanhluan** [SamProf/MatBlazor#802]
**Describe the bug**
I am using MatBlazor in my enterprise project and thanks to all people who contribute into this awesome UI components.
I just detect when using Href in all MatBlazor components will navigate twice.
I am using it in .Net 5

**To Reproduce**
Open https://www.matblazor.com/NavMenu.
Click on "Internal Href Checkbox" item.
It will navigate to https://www.matblazor.com/Checkbox.
If you want to back to https://www.matblazor.com/NavMenu. page you have to click back button on browser twice.
**Blazorfiddle link**

**Expected behavior**
Should navigate once and can be back to previous page with one click on back button on browser.

**Screenshots**
If applicable, add screenshots or .GIF captures to help explain your problem.

**Additional context**

**Comment by Christian-Oleson** [comment]
@ngothanhluan ,
If this is an issue, would you be willing to open a PR for it?

**Comment by PeteJobi** [comment]
Hello, @ngothanhluan. In what other components did you notice this bug besides NavItem and ButtonLink?

**Comment by ngothanhluan** [comment]
HI @PeteJobi , I think that's only NavItem and ButtonLink components for this issue.

**Comment by SamProf** [comment]
fixed by @PeteJobi
