### ISSUE TITLE
New Component: Canvas

### ISSUE THREAD

**Issue by yiyoMX** [SamProf/MatBlazor#81]
A canvas component, so it can be used to capture signatures, or any kind of drawing.

**Comment by SamProf** [comment]
What exactly you expect? Native js API for canvas or drawing surface?

for native api we have https://github.com/BlazorExtensions/Canvas

**Comment by yiyoMX** [comment]
> What exactly you expect? Native js API for canvas or drawing surface?
> 
> for native api we have https://github.com/BlazorExtensions/Canvas

Yeah, I know about that one, I thought it would be better to have this component inside MatBlazor.

**Comment by SamProf** [comment]
MatBlazor planned as AIO (ALL in One), but this is not point of interest of MatBlazor. Maybe I will make another package MatBlazor.Canvas. 
But I see https://github.com/BlazorExtensions/Canvas and they was great. I dont think. that I can really improve something.

**Comment by GeorgeS2019** [comment]
@SamProf Canvas is a critical part of any Javascript UI framework. There are so many variants. However, all come with ease of use in implementing event binding and mouse event handling.

I think this is currently missing in all Blazor [attempts ](https://github.com/BlazorExtensions/Canvas/issues/19)I have [seen](https://github.com/aspnet/AspNetCore/issues/15440). I wish I am wrong. 

Please others comment on this.

I think we need talents into these GAPs among all canvas, svg  blazor implementations.
