### ISSUE TITLE
MatBlazor Client side demo link on Github is pointed to older version of MatBlazor

### ISSUE THREAD

**Issue by Christian-Oleson** [SamProf/MatBlazor#818]
**Describe the bug**
If you look at the documentation on GitHub here: https://github.com/SamProf/MatBlazor
You will see a link to the ClientSide demo of MatBlazor. If you click on that link, the demo that pulls up is based on an older version of MatBlazor

**To Reproduce**
1. Go to https://github.com/SamProf/MatBlazor
2. Click on the client side demo link: https://samprof.github.io/MatBlazor/
3. Notice the demo is on version 2.6.0 (at the time of writing the bug, the current version is 2.8.0)

**Blazorfiddle link**
N/a

**Expected behavior**
This should be kept up to date and deployed regularly with new versions

**Comment by enkodellc** [comment]
It now appears to be 2.9.
