### ISSUE TITLE
MatChip filter selected color

### ISSUE THREAD

**Issue by YTN0** [SamProf/MatBlazor#828]
I have just started using Blazor (and MatBlazor) and have a question regarding using MatChip. I am creating a selection of tags that the user can toggle or select (a subset of the listed tags), and am using the MatChipSet and filter option. 

Is there a way to have the selected chips be a specific color and choose not to show the checkmark?

It would be great to have the option to set the unselected chip colors as well as the selected chip colors, and choose whether to use the checkmark or not.

TIA.

**Comment by KacperNiwczyk** [comment]
Hi @YTN0 U can try using SelectedChipChanged method in your MatChipSet and provide method in which you can manipulate a style I've just did something like this 

`    private void OnChipChanged(MatChip chip)
    {
        chip.Style = "color: green";
        chip.IsSelected = false;
    }`

Try it on your own

**Comment by Christian-Oleson** [comment]
@YTN0 ,
Has your question been answered? Can this be closed?

**Comment by YTN0** [comment]
@Christian-Oleson Yes, thanks for following up!
