### ISSUE TITLE
MatSelectItem seems to be sending debug messages cluttering the console

### ISSUE THREAD

**Issue by dbowser** [SamProf/MatBlazor#837]
**Describe the bug**
When I use MatSelectItem, the JavaScript console in the browser (Chrome) is flooded with:
MatSelect.init {fullWidth: false}

This adds no value or information that I can discern. Every line is the same. It makes it hard to find my own debug messages. 

**To Reproduce**
1. Include a MatSelectItem on your page.
2. Go to the page populated by this.
3. Press 'Ctrl-Shift-j' to open the console
4. See the list of 'MatSelect.init {fullWidth: false}'
**Expected behavior**
None of the other components seem to be writing anything to the console window. 
I don't see any value or information provided by this one. 
It does add a lot of clutter.
It seems to me that nothing should be in the console from the MatBlazor components since they should be already tested.
Maybe I am missing something.

**Screenshots**
A small snip of the output is attached below but the list is very long.
![Capture](https://user-images.githubusercontent.com/3384531/105864029-81712400-5fbf-11eb-8e82-65e441534b55.JPG)

**Additional context**

**Comment by Christian-Oleson** [comment]
@dbowser ,
I believe I solved this issue in 2.9. (Issue #804). Can you please confirm?

**Comment by dbowser** [comment]
Yes! It seems to be working great now. I do not see any extraneous messages. 
Thank you for fixing this and for your part in creating a great component!

**Comment by Christian-Oleson** [comment]
NP! Can you close the issue @dbowser ?

**Comment by dbowser** [comment]
Works great now!
