### ISSUE TITLE
Documentation not very useful - Code snippets needed

### ISSUE THREAD

**Issue by MhAllan** [SamProf/MatBlazor#843]
I can't see how to use components, there are no code snippets

for example you get nothing from these pages, no good explanation nor snippets:

https://mudblazor.com/api/grid
https://mudblazor.com/components/grid
https://mudblazor.com/features/breakpoints

And this does not load: https://try.mudblazor.com/snippet

**Comment by PeteJobi** [comment]
Looks like you opened an issue on the wrong github repository.

If you're looking for the documentation for **MatBlazor**, go to https://matblazor.com.

**Comment by MhAllan** [comment]
I am so sorry for this :)
