### ISSUE TITLE
Clicking on Icon in DatePicker doesn't show the calender selection window.

### ISSUE THREAD

**Issue by schwarzie2478** [SamProf/MatBlazor#86]
A small UI annoyance:

I was trying the DatePicker example on the MatBlazor website today and I tried to get the selection window of DatePicker to open. 

But I clicked on the icon embedded in the control and nothing happened. 
It just showed a selection box around the icon.
If I clicked anywhere else in the control, it was okay!

I don't know if this is easy to fix. 
I could  investigate it on my own if you don't want to divert your attention too much yet to these kinds of bug. It will just take me a while  longer to get to know the code base first!

**Comment by MatthewS2077** [comment]
Very annoying for users. Angular Material lets users click the icon. IMHO MatBlazor should follow Angular Material styling/operation as closely as possible.
(https://material.angular.io/components/datepicker/overview)
