### ISSUE TITLE
When using MatButton with Link and Target="_blank" the button will work as expected but throw an error in console.

### ISSUE THREAD

**Issue by Ogglas** [SamProf/MatBlazor#864]
**Describe the bug**
When using MatButton with Link and Target="_blank" the button will work as expected but throw an error in console. 

_blazor.webassembly.js:1 Uncaught (in promise) TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Window'
    --- property 'window' closes the circle
    at JSON.stringify (<anonymous>)
    at blazor.webassembly.js:1_

Using MatButtonLink works as expected.

```
<MatButtonLink Href="https://github.com/BlazorComponents/MatBlazor" Target="_blank">
    <i class="fa fa-github" aria-hidden="true"></i> &nbsp; Github
</MatButtonLink>
```
https://www.matblazor.com/ButtonLink

**To Reproduce**

```
<MatButton Link="https://github.com/BlazorComponents/MatBlazor" Target="_blank">
    <i class="fa fa-github" aria-hidden="true"></i> &nbsp; Github
</MatButton>
```

https://www.matblazor.com/Button

**Blazorfiddle link**

Since HTML Links (Hyperlinks) does not work in blazorfiddle it can't be reproduced there. Code anyway:

https://blazorfiddle.com/s/buk2gsc3

**Expected behavior**
Work as MatButtonLink

**Comment by enkodellc** [comment]
The current code in MatButton
```
            if (Link != null)
            {
                if (!string.IsNullOrEmpty(Target))
                {
                    try
                    {
                        await JsInvokeAsync<object>("open", Link, Target);
                    }
                    catch (TaskCanceledException ex)
                    {
                        Console.WriteLine(ex);
                    }
                }
                else
                {
                    UriHelper.NavigateTo(Link, ForceLoad);
                }
            }
```

This issue appears to be with Blazor. I submitted a fix in the develop branch

https://stackoverflow.com/questions/62769031/how-can-i-open-a-new-window-without-using-js
https://github.com/dotnet/aspnetcore/issues/16632

**Comment by SamProf** [comment]
fixed in develop. will be in nearest release.
Thank you @enkodellc
