### ISSUE TITLE
DatePicker - Setting Maximum to Today does not allow selection of today as the date

### ISSUE THREAD

**Issue by ralfbalzer** [SamProf/MatBlazor#900]
When I set "Maximum="@DateTime.Today", the dropdown calender shows todays as a selectable date but clicking it, does not select the date. 

![Screenshot 2021-07-23 134442](https://user-images.githubusercontent.com/22136154/126777571-4fcaad82-cab3-4534-8c63-ad3be5fa1a63.jpg)

**Comment by enginexon** [comment]
@SamProf It looks like combination of flags

**Comment by ralfbalzer** [comment]
@enginexon your comment made me think and I found the solution. I need to use `Maximum="@DateTime.Now"` instead of `@DateTime.Today`. Today obvioulsly only retruns the date. DateTime,Now allows the picking of the date as long as the time is before the current time. 
Thanks for your help :-)

**Comment by enginexon** [comment]
@ralfbalzer You are welcome. I am glad that accidentally helped you to solve the issue.
