### ISSUE TITLE
Table reload data

### ISSUE THREAD

**Issue by jrobertshawe** [SamProf/MatBlazor#91]
I am having issues changing the length of the table.  If I change an item's content in the array it will update the table but if I remove an item from the array it will not refresh the table to remove the row.

Is there something I need to do here

**Comment by arivera12** [comment]
Did you call StateHasChanged() after removing the item?

**Comment by Rocky-25** [comment]
I've found this, if changing the objects in the list behind the Items property it doesn't update the table.
I've called StateHasChanged() after updating the list.
Changing the properties of the items in the list does update the table.

**Comment by ViRuSTriNiTy** [comment]
If you change the items in an `EventCallback<T>` then `StateHasChanged()` is called automatically after the callback returns. But be aware that doing async stuff (like requesting things from a REST api) in such a callback might result in a call to `StateHasChanged()` before the async stuff is even finished. Hence you have to call `StateHasChanged()` manually after the async code.

There's a nice example showcasing how this can be handled:

https://github.com/aspnet/samples/tree/master/samples/aspnetcore/blazor

**Comment by Christian-Oleson** [comment]
You can use the asynchronous version of StateHasChanged. @jrobertshawe , can you confirm that this is no longer an issue?
