### ISSUE TITLE
Treeview - not rendering correctly

### ISSUE THREAD

**Issue by drma-dev** [SamProf/MatBlazor#917]
![image](https://user-images.githubusercontent.com/12803050/136087295-e6b8243f-b075-470e-94c4-07499a2bf019.png)

**Comment by ddslawson** [comment]
Hi I am having this same issue, did you find a resolution?

**Comment by yoya93** [comment]
@ddslawson , @drma-dev  any new news on this topic??

**Comment by ddslawson** [comment]
Yes, the fix is to use the latest development package on nuget and not the latest stable. I'm currently using 2.9.0-develop-042.

**Comment by drma-dev** [comment]
the project is abandoned. go to another.

**Comment by yoya93** [comment]
@drma-dev , @ddslawson  Thanks a lot
