### ISSUE TITLE
IMatDialogService + BUnit

### ISSUE THREAD

**Issue by drma-dev** [SamProf/MatBlazor#919]
I don't know if you guys use BUnit, component to test Blazor.

I'm trying to initialize the IMatDialogService, but I can't manually initialize this service.
`ctx.RegisterDialogService(typeof(ChangeDialog), new());`
```
public static void RegisterDialogService(this TestContext ctx, Type componentType, Dictionary<string, object> attributes)
{
    var services = new MatPortalService();
    services.Add(componentType, attributes);
    ctx.Services.AddSingleton<IMatDialogService>(new MatDialogService(services));
}
```

```
var cut = ctx.RenderComponent<ChangeDialog>(parameters => parameters
    .Add(p => p.DialogReference, new MatDialogReference() { Service = new MatDialogService(new MatPortalService()) })
);
```
```
var att = new Dictionary<string, object>
{
    { "VariableName", "xyz" },
    { "VariableValue", "xyz" },
    { "VariableType", VariableType.SingleLine }
};

await cut.Instance.DialogReference.Service.OpenAsync(typeof(ChangeDialog), new MatDialogOptions() { Attributes = att });
```
when I run that last line of code, the system crashes.

**Comment by egil** [comment]
> when I run that last line of code, the system crashes.

To get more help, you might want to share what the exception message is.

**Comment by drma-dev** [comment]
there is no error message. the execution just stops.

**Comment by egil** [comment]
> there is no error message. the execution just stops.

So the system doesn't crash as you wrote before, the test completes without an error?

I don't know how the MudDialog works, but my guess is that it calls triggers something in a other component, perhaps in MatPortalHost, and that shows the dialog.

So the question is. Why would you want to test the internal dialog feature of MudBlazor?

Why not just render the content you want to show in the dialog and trust that the dialog itself works correctly.

Sorry, it's super hard to help any more. I'm not a MudBlazor dev, so don't know how it works. MudBlazor is using bUnit for testing it's component (awesome), so perhaps look for at MudBlazors own test for inspiration.

**Comment by drma-dev** [comment]
I don't know what the word crash means exactly.

but the execution stops, doesn't finish. if you debug the method, debugging will stop at that line, and not continue. as if there was an internal error, but this exception doesn't come back to you, so you don't know what's going on.

I use this functionality to open a popup a lot, so my test has to respect that, to be as close as possible to an interacting user.
