### ISSUE TITLE
Card more features to add the header/image/icons

### ISSUE THREAD

**Issue by sowsan** [SamProf/MatBlazor#92]
Are there more capabilities coming up on matcard? 

https://material.io/design/components/cards.html#anatomy

**Comment by SamProf** [comment]
Yes, will be in nearest releases

**Comment by jorgy343** [comment]
I'll take a look at this and see if I can implement everything on https://material.io/develop/web/components/cards/

**Comment by SamProf** [comment]
Hey!
I have improved MatCard in version 1.5.0. Soon more examples and possibilities.
 
https://www.matblazor.com/Card
