### ISSUE TITLE
MatTextField: FullWidth disables Outline

### ISSUE THREAD

**Issue by anddrzejb** [SamProf/MatBlazor#98]
I cannot mix FullWidth with Outline. If FullWidth = "true" then there is no outline. I tried adding "mdc-text-field--fullwidth" to the MatTextField Class, but that messes up things royally.

**Comment by SamProf** [comment]
Thank you.
This is known problem.

**Comment by SamProf** [comment]
https://github.com/material-components/material-components-web/issues/4815#issuecomment-500958527
